### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by EryouHao** [lusaxweb/vuesax#102]
I run `npm run build` and `npm run dev`, and the console show 
```
WARNING in ./docs/.vuepress/enhanceApp.js 14:10-17
"export 'default' (imported as 'Vuecode') was not found in './vuecode.js/dist/vuecode.common.js'
```
browser console show 
```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
```
how to fix it? thanks

**Comment by luisDanielRoviraContreras** [comment]
Can you give me some repo to reproduce the problem? and the specifications could pass them?

**Comment by luisDanielRoviraContreras** [comment]
I made a change in the import of that js you could check if it works by downloading the last repo and testing many thanks for the contribution

**Comment by EryouHao** [comment]
I still show this. Can you  run dev in localhost?

![image](https://user-images.githubusercontent.com/17328747/41187844-a24677d2-6be5-11e8-8180-5f3d20dda985.png)
![image](https://user-images.githubusercontent.com/17328747/41187847-b8f4c38a-6be5-11e8-8629-fd2a20238960.png)

**Comment by w3cj** [comment]
@EryouHao I believe I have fixed this. Can you try it out to make sure?

Clone my fork in a totally separate folder, checkout the branch, npm install, and npm run dev:

```sh
git clone git@github.com:w3cj/vuesax.git vuesax-fix
cd vuesax-fix
git checkout fix-102-add-vuepress-dev-dependency
npm install
npm run dev
```

**Comment by EryouHao** [comment]
@w3cj thanks, it's works.
