### ISSUE TITLE
Any plan for Vue 3 suppport?

### ISSUE THREAD

**Issue by JenuelDev** [lusaxweb/vuesax#1021]
**Is your feature request related to a problem? Please describe.**
Most of our projects are in Vue 3. Vuesax really looks nice but it seems it's not being continued...

**Describe the solution you'd like**
Be able to use in vue 3 projects.

**Describe alternatives you've considered**
Using another framework instead if no support for vue 3.

**Comment by lk77** [comment]
@BroJenuel You can use vuesax3 instead of vuesax if you need Vue 3 support

https://www.npmjs.com/package/vuesax3

https://github.com/lk77/vuesax

original Vuesax package is not maintained anymore
