### ISSUE TITLE
Clicking a vs-sidebar-item that has a "to" property doesn't close the sidebar.

### ISSUE THREAD

**Issue by Pitu** [lusaxweb/vuesax#104]
Not sure if this is intended or not, but since the documentation doesn't mention it I'm opening an issue just in case. While using vuesax's latest version, adding a `to` property to a `<vs-sidebar-item>` element doesn't trigger closing the sidebar. Example:

```html
<vs-sidebar :vs-active.sync="isSidebarActive">
	<vs-sidebar-item to="/news">
		News
	</vs-sidebar-item>
</vs-sidebar>
```
As of now, the way I found to make it close after clicking on it is to add a native click event like this:

```html
<vs-sidebar :vs-active.sync="isSidebarActive">
	<vs-sidebar-item to="/news" @click.native="isSidebarActive = false">
		News
	</vs-sidebar-item>
</vs-sidebar>
```

Is there a fancier way to achieve this?

**Comment by luisDanielRoviraContreras** [comment]
If there is already a way but I think it is not in the documents you can add the property `vs-click-close`, it would be something like this

```
<vs-sidebar vs-click-close  :vs-active.sync="isSidebarActive">
	<vs-sidebar-item to="/news">
		News
	</vs-sidebar-item>
</vs-sidebar>
```

Please check if it works for you to add the documents about this

**Comment by Pitu** [comment]
That directive indeed works 👌🏻.
Thanks for the help!
