### ISSUE TITLE
 how to build dashboard admin,  

### ISSUE THREAD

**Issue by EliasChampi** [lusaxweb/vuesax#109]
I want to build an admin panel with vuesaxb sidebar  and menu, but I do not achieve it, what would be the correct layout of the components? thank :(

**Comment by luisDanielRoviraContreras** [comment]
You could give me an example of what you can not do or try to thank

**Comment by luisDanielRoviraContreras** [comment]
Closed for a long time of inactivity and thanks for the contribution
