### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by cristijora** [lusaxweb/vuesax#11]
I'd like to contribute with some stuff on this UI lib but there are a couple of things missing.

- The dev server (npm run dev) doesn't seem to open anything
- The sources for docs (it seems) are not in git which makes it hard to test the components right away.
- Maybe a small stack description, things to watch for contributors

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much friend I am in process regarding everything so that you can contribute more easily and with the corresponding documents when you are ready to notice you so you can check it

**Comment by luisDanielRoviraContreras** [comment]
Good friend is the documentation to contribute thank you very much I hope you review and help vuesax
