### ISSUE TITLE
Autocomplete Select component does populate with the value that has been selected if enter is pressed

### ISSUE THREAD

**Issue by fahada95** [lusaxweb/vuesax#113]
OS - MacOS High Sierra
Node - 8.11.2
Vuesax - 3.1.1
Browser - Chrome 66.0.3359.18
Package Manager - npm

If you begin typing the beginning of an item in the component and try to hit enter, the field will not populate with the input that had been highlighted. 

https://lusaxweb.github.io/vuesax/components/selects.html#autocomplete

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much for the message to review the problem most likely is that there is no option to be selected at the previous value do you think it would be good functionality or would it be better otherwise?

**Comment by fahada95** [comment]
![autocomplete issue](https://user-images.githubusercontent.com/21221766/41367581-6f77ed9c-6f0d-11e8-8eb9-25f681442921.gif)

I think it would be good functionality. Maybe I am doing something incorrectly however I tried it in Safari as well and got the same result. I was not expecting to select square when I actually meant to select rectangle in the recording attached to this comment. I hope this helps.

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much I understand better I will fix it and I will advise you to check if it works as it should :+1:

**Comment by luisDanielRoviraContreras** [comment]
Ready and the update was completely complete thanks for the contribution please check if it works as it should thanks
