### ISSUE TITLE
Remove console.log

### ISSUE THREAD

**Issue by pedrogustavo** [lusaxweb/vuesax#114]
Hello,
First of all, I would like to congratulate the creators of the project. I found the Vuesax fantastic.

I'm using some components, and I noticed there are some `console.log` in some of them, such as: `vs-select ` and `vs-button`. I wonder if there would be any specific reason to be there?

If there are no problems, I wonder if I can send a PR by removing the console.log?

**Comment by luisDanielRoviraContreras** [comment]
If I would love the truth they are console.log that can pass me the PR without problem and if they also eliminate the comments it would be great to thank you very much for the contribution and use vuesax
