### ISSUE TITLE
Buttons get an "activo" class, and an extra element added on click. They do not get removed when clicked again.

### ISSUE THREAD

**Issue by Morthor** [lusaxweb/vuesax#116]
On the examples page, most buttons will remain in an active visual state once clicked.
The class that the buttons are receiving for the visual state is called "activo" instead of "active".
`<span class="relleno"></span>` gets added everytime the button is clicked. This can be reproduced in the examples in the documentation: https://lusaxweb.github.io/vuesax/components/#border

- MacOS
- Node.js v8.9.1
- Vuesax v3.1.1
- Firefox 60.0.1 (64-bit)
- NPM

**Comment by luisDanielRoviraContreras** [comment]
If you are right, the buttons are the first component created and will be improved in a new update to create them with a stylus and a better approach. Thank you very much for the contribution

**Comment by Morthor** [comment]
It seems like the onBlur function is not being triggered. I can see all the code there to remove the "activo" class and delete the span with the "relleno" class, but for some reason, that code is just not running.

**Comment by luisDanielRoviraContreras** [comment]
Well you are already literally doing the whole component again to solve that and fix the support SSR in all components when I just update it I notice you to verify it thank you very much

**Comment by luisDanielRoviraContreras** [comment]
The whole buttons component has been updated thanks for the contribution please check if everything works as it should thanks

there are new functionalities and another approach in `vs-type`
