### ISSUE TITLE
$vs.confirm is not function

### ISSUE THREAD

**Issue by mdtm94** [lusaxweb/vuesax#117]
I updated my previous Vuesax version from v3.0.50 to v3.1.16 and I noticed that the $vs.confirm function is no more available on this version. When is too useful to access directly to that property and avoid to create an element on the DOM and variables on the component.

I wanna if this characteristic is gonna be added on a future version.

**OS:** Ubuntu 16.04
**Node.js:** 8.10
**NPM:** 5.7.1
**Vuesax:** 3.1.16
**Browser:** Firefox Development Edition 61.0b.13

BTW, I found amazing the work around this library, congrats.

Greetings.

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much this component was updated to improve the operation but it may be added after only `$vs.alert` and` $vs.confirm` that do not need so much interaction with the user would it seem good?

**Comment by mdtm94** [comment]
In that case, til the change is published. It would be convenient to add `textConfirm` and `textCancel` to the `vs-dialog` component properties for multi-language apps.

**Comment by luisDanielRoviraContreras** [comment]
It's a very good idea you can do a PR on this? :+1:

**Comment by luisDanielRoviraContreras** [comment]
In the latest version `3.1.7`, the functions` $vs.alert` and `$vs.confirm` were added again, this is not the desired end. You have to change that component for SSR support and better approach. Thank you very much

**Comment by luisDanielRoviraContreras** [comment]
These have already updated the dialogues with a feature functionality for those of type **alert** and **confirmed** and with component type for **indicator** and thus give more flexibility and handling

Thank you very much for the contribution

**Comment by fergardi** [comment]
This is related to https://github.com/lusaxweb/vuesax/issues/160#issuecomment-403192675
