### ISSUE TITLE
v-tooltip doesn't work with Mozilla Firefox

### ISSUE THREAD

**Issue by mdtm94** [lusaxweb/vuesax#118]
When I try to use the `vs-tooltip` property on any element, I got a message indicating:
- `n.toElement is undefined` when the pointer goes inside the element.
- `t.toElement is undefined` when the pointer goes outside the element.

I wanna know if this property is properly supported by every browser or only is supported on Chrome browser.

**OS:** Ubuntu 16.04
**Node.js:** 8.10
**NPM:** 5.7.1
**Vuesax:** 3.1.16
**Browser:** Firefox Development Edition 61.0b.13

Greetings.

**Comment by luisDanielRoviraContreras** [comment]
Excuse these using `vs-tooltip` or` v-tooltip`? because it is `v-tooltip`. that component is going to change to an element of the sun for better manipulation and functionalities if you have any idea or want to help to do it, thank you very much for the contribution.

**Comment by mdtm94** [comment]
Sorry, my mistake, I'm using `v-tooltip`. In that case I'm gonna check how it works the property and how can be optimized, nice work.

Greetings.

**Comment by luisDanielRoviraContreras** [comment]
Easy, thank you very much for the contribution
