### ISSUE TITLE
Buttton type gets ignored

### ISSUE THREAD

**Issue by RickCardoso** [lusaxweb/vuesax#121]
After the last update, the button type could be set manually overriding Vuesax default as "button". So we could set a button to be submit using:
```
<vs-button
    type="button"
   ...
</vs-button>
```

Now the type gets ignored and the button is always set as `type="button"`. This makes forms stop working when the button calls the form submit.

- OS: Windows 10
- Node.js version: 8.11.2
- Vuesax version: vuesax3.1.7
- Browser version: Chrome 67.0.3396.87
- Package manager: npm v6.1.0

**Comment by luisDanielRoviraContreras** [comment]
Ready and the problem is solved when I upload you notice to review it I'm updating the select just finished upload the latest version with the arrangement thank you very much

**Comment by pitchinnate** [comment]
Also it messed with buttons that an icon specified, all the sudden they now float left.

**Comment by luisDanielRoviraContreras** [comment]
You could pass images of the problems, thank you very much for the contribution the documents were updated

**Comment by luisDanielRoviraContreras** [comment]
You can now add the type property without problem please check thanks

**Comment by pitchinnate** [comment]
Here is how Dialogs look now:

![image](https://user-images.githubusercontent.com/2814435/41724876-8ca7f2c4-753c-11e8-96f7-5e80602a1f27.png)

**Comment by pitchinnate** [comment]
Also here is how adding an icon affects it:
![image](https://user-images.githubusercontent.com/2814435/41725031-df7d279e-753c-11e8-80d7-7989661ee51f.png)

Then with just adding `vs-icon` you get this:
![image](https://user-images.githubusercontent.com/2814435/41725066-f56db03c-753c-11e8-8eae-699728abd352.png)

**Comment by pitchinnate** [comment]
For now I've had to work around it by putting the icon in myself doing something like this:

```
<vs-button
          v-on:click="$emit('creator-click')"
          vs-color="success"
          vs-type="filled"
          class="addButton">
        <i class="material-icons">add_circle</i>
        {{creatorText}}
      </vs-button>
```

But it requires some more css changes to get the icon to be the right size and line up correctly.

**Comment by luisDanielRoviraContreras** [comment]
Do you have the latest version?

**Comment by pitchinnate** [comment]
Ok that seemed to fix it I just did another upgrade. Any idea why material icons are broke now?

**Comment by pitchinnate** [comment]
Also the floating left on a button with a `vs-icon` still happens with latest upgrade.

**Comment by luisDanielRoviraContreras** [comment]
but in the documents does not happen that if it's weird you could give me a repo or something to verify the problem and fix it

**Comment by pitchinnate** [comment]
Any quick instructions in docs for installing library icons?

**Comment by pitchinnate** [comment]
Nevermind I found I can just add
```
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```
to my index.html for now.

**Comment by luisDanielRoviraContreras** [comment]
If that is the idea, it is very easy to add it but it gave many problems in compilation and unnecessary loaders if you can add the documents on this in a RP would be great thanks

**Comment by pitchinnate** [comment]
Yeah I don't mind loading it from a CDN I'm loading other google fonts the same way I'm sure some people will want it locally downloaded but works fine for me. Yeah I can add it to the documentation.

**Comment by safiullahsarhandi** [comment]
`<vs-button button="submit" color="success" type="gradient" class="float-right">Click Me </vs-button>`
the default type of button is set to button which cause preventing submitting form add `button="submit"`  to change the behavior with in  form

**Comment by gautam-patadiya** [comment]
@safiullahsarhandi you save my day buddy thanks!
