### ISSUE TITLE
on doc page, some text missing: font color is white the same color with background

### ISSUE THREAD

**Issue by zhang-quan-yi** [lusaxweb/vuesax#126]
hello:

https://lusaxweb.github.io/vuesax/components/notifications.html

![image](https://user-images.githubusercontent.com/12481444/41572495-c0c72f22-73aa-11e8-9da5-d7f33393421e.png)

ps: my Browser is chrome on windows 10

**Comment by luisDanielRoviraContreras** [comment]
Ready is already solved the problem is that in the new update of the buttons change the property `vs-type`
