### ISSUE TITLE
Selects on iOS 

### ISSUE THREAD

**Issue by SSmale** [lusaxweb/vuesax#13]
Hi, I love the look of this component library. It’s the first one I can se myself using. 

When viewing a select in iOS safari the native select scroller that appears at the bottom of the mobile screen is empty and makes it hard to use

Keep up the good work

**Comment by luisDanielRoviraContreras** [comment]
thank you very much friend for the contribution I will review it and fix it as soon as I do you notice so that you review it greetings

**Comment by luisDanielRoviraContreras** [comment]
Good friend apparently solve the problem I would love you to review it to see many thanks
