### ISSUE TITLE
Does it support SSR?

### ISSUE THREAD

**Issue by jayserdny** [lusaxweb/vuesax#132]
Hello,

Is this framework compatible with SSR? Since some components do DOM manipulation, not sure if it will work with SSR.

Overall, nice framework! You may also consider to add unit testing to ensure everything is working properly :D

**Comment by jayserdny** [comment]
Okay, I didn't notice #83 . I tried using Meteor for SSR (not nuxt.js) but it also fails. Will provide a log as soon as I can :D

**Comment by luisDanielRoviraContreras** [comment]
For now there is no support for SSR but it is working on it for now only the components **vs-bottons** and **vs-select** work as it should

the problem is that the css (var) styles do not work and you are migrating to stylus

Thank you very much for the contribution

**Comment by jayserdny** [comment]
What about unit testing? It is highly important to be able to have automated tests for any incoming PR.

**Comment by luisDanielRoviraContreras** [comment]
IF that is very important but I do not know which is the best if you can help me in that would be great thank you very much

**Comment by jayserdny** [comment]
Imagine the following scenario:

A big pull request is incoming and involving some refactor of the code. Will you manually test all the components of the framework to ensure its functionality? At scale, this is not efficient. But, if there are the proper unit test set up, you can test them all by running just 1 command :)

I am not sure how to do unit testing in Vue but I can learn it and collaborate with a PR. Meanwhile, think about it.

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much if I had contemplated adding them but I am somewhat busy in the migration for full support to SSR, if you can help us in this would be great and thank you very much for the contribution

**Comment by luisDanielRoviraContreras** [comment]
#176

**Comment by brunokunace** [comment]
YES!!!  now,  all components have support to ssr,  thanks @luisDanielRoviraContreras for awesome work.

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much ! I hope we keep improving and creating for the community
