### ISSUE TITLE
Need help translating from Spanish to English?

### ISSUE THREAD

**Issue by jayserdny** [lusaxweb/vuesax#133]
I saw some of the text in the website that does not really make sense in English plus they are mixed up with some Spanish. If you guys need help translating Spanish to English, don't hesitate in contact me.

**Comment by luisDanielRoviraContreras** [comment]
If the truth I need a lot of help and in what you see that is not understood or is misunderstood we would love the help and any RP on this welcome is thanks

**Comment by jayserdny** [comment]
If you are in social media, feel free to share it to connect so I can point out what text is obscure. A pure Spanish version of the docs can help to make the English version from it. So, if you somehow can provide the text in Spanish to me, I can translate them :+1:

**Comment by luisDanielRoviraContreras** [comment]
Good to have both languages ​​would be excellent but when I finished the update of all the components there is if I put in that when it is more stable Vuesax and have no problems or accessibility or SSR are very important issues, when you have the documents in Spanish notice to help me in that thanks 👍

**Comment by jayserdny** [comment]
I think you misunderstood what I said. I said that in order to fix the actual documentation (In English) I need those texts in Spanish to really understand what it is trying to say.

**Comment by luisDanielRoviraContreras** [comment]
That's why I would have to do all the documents in Spanish and that takes a lot of time, I can only do it so that you can pass it to English thanks

**Comment by jayserdny** [comment]
Up to you. But I still believe that a better-written documentation is needed so even if it takes a lot of time, it should be a priority for end users.
