### ISSUE TITLE
Swipe right gesture opens 4 drawers in mobile device

### ISSUE THREAD

**Issue by jayserdny** [lusaxweb/vuesax#134]
#### Expected Behavior
When I swipe to the right on this page: https://lusaxweb.github.io/vuesax/components/sideBar.html I expect to only open the global drawer instead of any other drawer.

#### Current Behavior
Four drawers are open when you swipe to the right in the page mentioned above. They open like a stack.

#### Steps to reproduce

1. In a mobile device, go to the following website: https://lusaxweb.github.io/vuesax/components/sideBar.html

2. Do a right swipe and notice all the drawers open.

#### Environment
Mobile Device:  Samsung Galaxy S9+
OS: Android 8.0.0
Browser: Samsung Internet 7.2.10.33

**Comment by luisDanielRoviraContreras** [comment]
Well that is something expected because each drawer has that clear functionality is that in an application are not going to put as many as one maximum and will come out only but that happens only for documents thanks for the contribution
