### ISSUE TITLE
slider component doesn't work properly.

### ISSUE THREAD

**Issue by get-Haque** [lusaxweb/vuesax#135]
As seen in official websites doc's slider doesn't work properly.

I noticed lot's of little things not working as it should. If it's in beta or Alpha you should make it clear up front, maybe add a beta icon in the logo and show the currently released version.

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much and verify and if in fact you have a problem the component just solve it I warned you and if it would be good to add the BETA icon so that users know it thank you very much

**Comment by luisDanielRoviraContreras** [comment]
The logo with the BETA has already been added, thank you very much for the contribution

**Comment by luisDanielRoviraContreras** [comment]
The slider in my case works as it should please add some repo or file to verify the error thanks for the contribution
