### ISSUE TITLE
One button's appearance depends on another button's appearance

### ISSUE THREAD

**Issue by Gargo** [lusaxweb/vuesax#137]
- Windows 10
- Node.js version - 10.5.1
- Vuesax version - 3.1.24
- Browser version - Vivaldi 1.15.1147.36
- package manager - npm

Just took your "hello world" html example from readme and added a button:
`
...
<div id="app">
        <vs-button vs-color="success" vs-type="primary-filled">Hola Mundo</vs-button>
        <vs-button vs-color="primary" vs-type="filled">Primary</vs-button>
  </div>
...
`

"Hola Mundo" is displayed and invisible. If I delete "Primary" button - "Hola Mundo" becomes visible and black. Note - it is 2 fully different buttons which should be independent from each other

**Comment by luisDanielRoviraContreras** [comment]
The buttons were changed from `vs-type =" primary-filled "` to only `vs-type =" filled "` for better functionality if you need to change the color to use `vs-color`

The README.md had the old example already updated thank you very much for the contribution
