### ISSUE TITLE
'vs-danger-text' on input components doesn't work in conjunction with vs-label-placeholder

### ISSUE THREAD

**Issue by TimonLukas** [lusaxweb/vuesax#139]
Hello!

I am using Vuesax 3.1.26 (the latest version as of writing this). I have the problem that the `vs-danger-text` property of the `input` component (referenced [here](https://lusaxweb.github.io/vuesax/components/input.html#validations)) does **not** work in conjunction with the `vs-label-placeholder` attribute. The label does not ever get replaced.

I managed to around it (by dynamically binding the `vs-label-placeholder` and then giving either the standard text or the danger text based on validity). Still, this would be really nice to have fixed.

Thank you!

**Comment by luisDanielRoviraContreras** [comment]
For now the `vs-danger-text` is a title that is shown when perched on the icon something like that

![screenshot_26](https://user-images.githubusercontent.com/31676496/41786757-5d3bc884-7614-11e8-967c-22faf454d70c.png)

I think you mean this, thank you very much for the contribution

**Comment by TimonLukas** [comment]
Oh, all right, that makes sense!

Do you think that you'll extend the component in the future to allow what I've talked about? I think there are very valid use-cases, and the component can handle that a lot more efficiently by itself.

**Comment by luisDanielRoviraContreras** [comment]
Yes clear in the update for support ssr and better accessibility is added this improvement
