### ISSUE TITLE
Feature Request: Custom colours on buttons. 

### ISSUE THREAD

**Issue by SSmale** [lusaxweb/vuesax#14]
Like the other components it would be awesome to have custom colours on buttons.

Keep up the good work

**Comment by luisDanielRoviraContreras** [comment]
Excellent friend the most likely is that you have it for the next update I warn you to review it thank you very much for the contribution

**Comment by Javier-Solis** [comment]
Just have a sass file for us to extend from that would be cool, I don't see one in the repo

**Comment by luisDanielRoviraContreras** [comment]
there is already support for `vs-color` on the buttons thank you very much for the contribution
