### ISSUE TITLE
Datepicker component

### ISSUE THREAD

**Issue by ayZagen** [lusaxweb/vuesax#142]
Any plans to create a datepicker/timepicker component ?

**Comment by luisDanielRoviraContreras** [comment]
There is still no plan for this, we believe that it should be one of the last components to be created because of the difficulty and that there are many libraries on this.

**Comment by natxocc** [comment]
It would be great to have the datepicker. I have tried to integrate some out of there on vuesax, but the integration on inputs, style... is not satisfactory.

++1 for datepicker
