### ISSUE TITLE
font-size in em instead of px

### ISSUE THREAD

**Issue by DRogueRonin** [lusaxweb/vuesax#143]
I noticed that for example the `vs-sidebar-item` uses a `font-size` of `15px`. In contrast to my other elements that's rather small.
`em` values should be used there so they scale with everything else.

The same with `padding`s and `margin`s and everything else that can/should use `em`.

**Comment by luisDanielRoviraContreras** [comment]
if you are absolutely right it is better to use `em` you could do a PR on this where you see pertinent thank you very much

**Comment by DRogueRonin** [comment]
Alright, will do. :)
