### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by VerzatileTom** [lusaxweb/vuesax#145]
- Windows 10
- Node 8.9.1
- "vuesax": "^3.1.30"
- Chrome 67
- I used npm to install

I installed 3.1.30 and buttons has no colors and you can only see white texts. Icons are not showing too.

**Comment by VerzatileTom** [comment]
Okay I figured it out. There are changes in the components too. Before its
```html
<vs-button type="warning-line-down">Warning</vs-button>
```
Now it became
```html
<vs-button type="line" vs-color="warning">Warning</vs-button>
```

**Comment by gsmitto** [comment]
Same issue here....

**Comment by luisDanielRoviraContreras** [comment]
The icons are no longer incorporated in the library by compatibility issue please add material icons independently if you can help me in the documents in the readme.md on this I would appreciate very much, thanks for the contribution

**Comment by daniel-farina** [comment]
I created a pull request to warn users about this. I tested it and I got icons working. 
Pull request #152 

Cheers.
