### ISSUE TITLE
Functions import

### ISSUE THREAD

**Issue by tridcatij** [lusaxweb/vuesax#148]
Hey! Tried to import functions like this:
```js
import Vue from 'vue'
import vsFunctions from 'vuesax/dist/functions'
import 'vuesax/dist/vuesax.css'

Vue.use(vsFunctions)
```
but received an error:

> Uncaught Error: Module build failed: Error: Couldn't find preset "@ vue/app" relative to directory "/var/www/blabla/node_modules/vuesax"

[This is the file example](https://github.com/cretueusebiu/laravel-vue-spa/blob/master/resources/assets/js/plugins/axios.js), where I want to replace sweetalerts to the Vuesax notify module.

Thank you!

**Comment by luisDanielRoviraContreras** [comment]
If you use vuesax completely does it give you the same error? You could try something like that :
```js
import Vue from 'vue'
import Vuesax from 'vuesax'
import 'vuesax/dist/vuesax.css'

Vue.use(Vuesax)
```

**Comment by luisDanielRoviraContreras** [comment]
Closed for inactivity
