### ISSUE TITLE
checkbox with Array default color is wrong

### ISSUE THREAD

**Issue by jkhaoqi110** [lusaxweb/vuesax#15]
vsCheckBox.vue
code in line 3 should be 
`<span :style="{'border':(!value || !value.length)?'2px solid rgb(160, 160, 160)':'2px solid '+backgroundx()}" class="cuadro">`

**Comment by luisDanielRoviraContreras** [comment]
Ready friend the final solution for the error was:

`<span :style="{'border':typeof value == 'boolean'?!value?'2px solid rgb(160, 160, 160)':'2px solid '+backgroundx():!valueArray?'2px solid rgb(160, 160, 160)':'2px solid '+backgroundx()}" class="cuadro">
`

thank you very much for the contribution this change will be in the next update I warn you to review it
