### ISSUE TITLE
Update vuesax script in Quick-start CDN code from Getting Started docs

### ISSUE THREAD

**Issue by jonbesga** [lusaxweb/vuesax#151]
The [current code](https://lusaxweb.github.io/vuesax/vuesax/#quick-start-cdn) doesn't render the button with the proper style.

This is because the current code is pointing to

`https://cdn.jsdelivr.net/npm/vuesax/dist/vuesax.min.js` (version 2.5.3)

instead of

`https://cdn.jsdelivr.net/npm/vuesax/dist/vuesax.umd.js` (version 2.5.7) as in the README file.

**Comment by luisDanielRoviraContreras** [comment]
Ready thank you very much already arranged

**Comment by luisDanielRoviraContreras** [comment]
![screenshot_1](https://user-images.githubusercontent.com/31676496/42044270-902c557c-7ac6-11e8-93dd-dbf2cbceb5d8.png)
