### ISSUE TITLE
Removable sidebar backdrop

### ISSUE THREAD

**Issue by antonio-costa** [lusaxweb/vuesax#153]
Is it impossible to remove the backdrop that appears in a sidebar? If I have a larger than 270px static 
sidebar, the backdrop starts to expand instead of the bar itself. (Or if I reduce it, the backdrop will remain in the sidebars position).

Is it possible to add a directive to remove the backdrop completely? Or does it already exist and I just can't find it?

Below images of examples of what I mean (sorry for the bad quality)

<img src="https://user-images.githubusercontent.com/14340661/42113689-16dd13f4-7be4-11e8-89dc-392ba286fef3.png" alt="alt text" width="400" height="600">

<img src="https://user-images.githubusercontent.com/14340661/42113730-4ad99bbe-7be4-11e8-85ff-549fe3948a8b.png" alt="alt text" width="400" height="600">

**Comment by luisDanielRoviraContreras** [comment]
ready now add the property `vsBackgroundHidden` and when it is in `vsStatic` by default the background is now deleted.

thank you very much for the contribution 👍
