### ISSUE TITLE
Sidebar collapsable menu disappears after click

### ISSUE THREAD

**Issue by fergardi** [lusaxweb/vuesax#154]
Windows10
Node 8.9.3
Vuesax@latest
Chrome 67.0.3396.99
Npm 6.0.0

When you try to close the submenu, it dissapears forever.

Before clicking the caret:

![image](https://user-images.githubusercontent.com/3602272/42262553-e7d8cc66-7f6b-11e8-9b30-a45c0299eab0.png)

After clicking the caret:

![image](https://user-images.githubusercontent.com/3602272/42262587-04a36e82-7f6c-11e8-843d-069b3f9b0143.png)

**Comment by luisDanielRoviraContreras** [comment]
It works well, you can pass a gif or video to see the flow thanks

**Comment by luisDanielRoviraContreras** [comment]
I can not reproduce the problem could you specify it better?

**Comment by fergardi** [comment]
I can only reproduce the problem in Chrome.

![image](https://user-images.githubusercontent.com/3602272/42305285-90398af8-802a-11e8-81b3-e36bf903f1bd.png)

To the left, latest Chrome version. To the right, latest Firefox version.

**Comment by luisDanielRoviraContreras** [comment]
I'm going to verify but I do not understand why it does not work for you, thanks, and if you can do a git it would be perfect to see the exact steps

**Comment by luisDanielRoviraContreras** [comment]
I could not duplicate the problem please if you persist to warn me to reopen the issues and look for a solution and if you can take a video or gif it would be great thanks

**Comment by jeffjonasson** [comment]
Hi, I'm experiencing the same problem, also with chrome.

![sidebar-group-bug](https://user-images.githubusercontent.com/6640376/42877897-78c1023c-8a8b-11e8-8c9f-08a8d690256d.gif)

Hope you can see what's happening here, it disappears until I reload the site.

**Comment by jeffjonasson** [comment]
Can add that I've had no problem with it on safari, both on your site and running an example locally.

**Comment by luisDanielRoviraContreras** [comment]
I'm going to review it, thank you very much for the contribution

**Comment by luisDanielRoviraContreras** [comment]
The component was completely updated, please check if the problem persists
