### ISSUE TITLE
Pagination seems broken

### ISSUE THREAD

**Issue by fergardi** [lusaxweb/vuesax#155]
I'm not sure if is intended, but the pagination styling seems a bit broken for me.

![image](https://user-images.githubusercontent.com/3602272/42262961-010b4d98-7f6d-11e8-8eb8-1ec00038941c.png)

There is no cursor pointer on hover, the borders are a bit ugly, and the overall styles does not fit with the rest of the framework. The pagination buttons should look more like the normal buttons, and there should be animation effects as well.

Just my opinion.

**Comment by luisDanielRoviraContreras** [comment]
The styles are changing from normal css to independent stylus I think I know where the problem is, thank you very much for the contribution I'm going to fix it and I'll let you know

**Comment by luisDanielRoviraContreras** [comment]
Ready and this is how I should thank you very much just missing some styles css

**Comment by fergardi** [comment]
Thank you, much better this wa.
