### ISSUE TITLE
Apply the same css animations of the Dialog component to the Popup component

### ISSUE THREAD

**Issue by fergardi** [lusaxweb/vuesax#156]
The appearing css animations of the Dialog component is really cool. Can we have the same into the Popup component? Now it seems a little bit boring.

And even better. Can we have the same css animations when we close those components as well, but reversed? It would look really cool when you dismiss a Dialog or Popup and it shrinks when dissapears.

Just my opinion.

**Comment by luisDanielRoviraContreras** [comment]
It is a very good idea and I had it contemplated, the components are being made almost from 0 for support ssr for now I go for the input when the popup update is added a better animation, thank you very much

**Comment by fergardi** [comment]
Are you making a complete rework for the components again? Will they be compatible with pervious versions, or will they break backwars compatibility?

**Comment by luisDanielRoviraContreras** [comment]
Almost all the components will be the same in logic but what really changes is the css for stylus support and accessibility, but some if it will change a bit and impact on the compatibility of previous versions

**Comment by luisDanielRoviraContreras** [comment]
Already the component was updated and has the animation, thank you very much
https://lusaxweb.github.io/vuesax/components/popup.html
