### ISSUE TITLE
 How to introduce on demand？

### ISSUE THREAD

**Issue by XcXerxes** [lusaxweb/vuesax#157]
If I only want to use some of the features of the framework, how to introduce it on demand, reduce the volume after packaging？

**Comment by luisDanielRoviraContreras** [comment]
You can add only the necessary components

https://github.com/lusaxweb/vuesax#or-use-individual-components

**Comment by XcXerxes** [comment]
I found some problems with the introduction of individual components.
**1**.  The size introduced on demand is only 30kb smaller than the size of all references.


**2**.  The size of the css file introduced on demand is even larger than the direct introduction.

**Comment by luisDanielRoviraContreras** [comment]
You could give me a contextual example of what you want to say thank you very much for the contribution
