### ISSUE TITLE
Feature Request: keyboard accessibility

### ISSUE THREAD

**Issue by somascope** [lusaxweb/vuesax#16]
Does your team have plans for adding keyboard accessibility to your components? For example, using the left/right arrow keys do not adjust the knob position in the Slider component, and using the up/down arrow keys don't change the selection of the Select component.

**Comment by luisDanielRoviraContreras** [comment]
I love I'm going to implement it, my friend, sure, it's going for the next update, thank you very much for the contribution.

**Comment by somascope** [comment]
That is great! Things look wonderful, visually, and I guessed that accessibility would be coming later on in 2018. Thank you very much.

**Comment by cristijora** [comment]
@luisDanielRoviraContreras could help with that if you want

**Comment by luisDanielRoviraContreras** [comment]
@cristijora I would love friend

**Comment by cristijora** [comment]
@luisDanielRoviraContreras getting an error when trying to run `npm run dev` command
but without any stacktrace or something like that
