### ISSUE TITLE
Dialog buttons styles

### ISSUE THREAD

**Issue by fergardi** [lusaxweb/vuesax#160]
It would be great to add the same styles of the normal Buttons into the Dialog buttons, to maintain the same styles in all the app.

For example, vs-type="relief".

**Comment by luisDanielRoviraContreras** [comment]
It's a very good idea, I'm just in that component, thank you very much for the contribution

**Comment by luisDanielRoviraContreras** [comment]
Ready and the component is updated and has the functionality `vs-accept-text` and `vs-cancel-text` thanks for the contribution in the case of being a confirm or alert is `acceptText` and `cancelText`
