### ISSUE TITLE
vs-upload component is designed for images

### ISSUE THREAD

**Issue by jonbesga** [lusaxweb/vuesax#162]
We should make [vs-upload](https://github.com/lusaxweb/vuesax/blob/master/src/components/vsUpload/vsUpload.vue) more generalist. The current viewer attached to it is unnecessary is you are uploading files, not images.

**Comment by luisDanielRoviraContreras** [comment]
It is very good idea in the update to ssr you can add that functionality

**Comment by luisDanielRoviraContreras** [comment]
The component has been completely updated with new features and support for any file
![upload](https://user-images.githubusercontent.com/31676496/43689168-196d0cbc-98c4-11e8-8cd9-352b02e17d8f.gif)

Thank you very much for the contribution

**Comment by razzul** [comment]
![demo](https://photos.app.goo.gl/KVS3FcGs5gpTpDYh6)

for image upload there is no h4 tag where I can get the name of the file, I only need to show the file name not the preview.
what should I do?
