### ISSUE TITLE
Buttons don't use the custom colors of the theme

### ISSUE THREAD

**Issue by fergardi** [lusaxweb/vuesax#163]
When you change the theme colors, the buttons are unaffected by the change.

https://jsfiddle.net/tyd0m82n/1/

**Comment by luisDanielRoviraContreras** [comment]
The theme colors can no longer be changed that way because the support ssr is working to change all the components and when ready to add the new methodology that is by stylus and change the global variables

**Comment by luisDanielRoviraContreras** [comment]
Already all the components have support for the change of color by means of `$ vs.theme`, thank you very much for the contribution
