### ISSUE TITLE
VsTabs throws an error when they are binded to an empty array

### ISSUE THREAD

**Issue by fergardi** [lusaxweb/vuesax#166]
When I use `vs-tab` with `v-for` it throws an error when the array is empty (in the initial state, before I fetch the content from the database for example).

```html
<vs-tabs>
  <vs-tab v-for="(tab, index) in tabs" :vs-label="tab.name" :key="index">
    <p>{{ tab.text }}</p>
  </vs-tab>
</vs-tabs>
```

```js
data: () => {
  return {
    tabs: [] // initial state
  }
},
mounted () {
  // fetch from database
  this.tabs.push({ name: 'tab1', text: 'hello1' })
  this.tabs.push({ name: 'tab2', text: 'hello2' })
}
```

![image](https://user-images.githubusercontent.com/3602272/42434200-7fb4610a-8352-11e8-9641-79eec7cfd27b.png)

Reproduction link: https://jsfiddle.net/xLvuoqda/3/

Also, it has a wrong list style:

![image](https://user-images.githubusercontent.com/3602272/42434212-8f4e1264-8352-11e8-9d7d-20810b8c375f.png)

Which I think it comes from here:

![image](https://user-images.githubusercontent.com/3602272/42434231-b3546cd0-8352-11e8-9561-d9aae8511625.png)

It should be fixed with `ul { list-style-type: none; }`

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much that component I'm going to redo for better functionality and support when you have it ready you notice to verify these errors thank you very much for the contribution

**Comment by luisDanielRoviraContreras** [comment]
This component was completely updated, please check if the problem persists, thank you very much for the contribution
