### ISSUE TITLE
i need update guide.

### ISSUE THREAD

**Issue by dasisyouyu** [lusaxweb/vuesax#169]
I upgraded from vuesax@3.1.7 to vuesax@3.1.36, but the layout broke.
Several CSS properties and js methods do not seem to work.

before
<img width="413" alt="2018-07-11 13 07 36" src="https://user-images.githubusercontent.com/16145243/42550221-722c547e-850b-11e8-8543-a25c9474f56a.png">

after
![2018-07-11 13 06 13](https://user-images.githubusercontent.com/16145243/42550220-6f6b056e-850b-11e8-9861-630a162d4b18.png)

**Comment by luisDanielRoviraContreras** [comment]
For more flexibility, the margins of the components were removed if the only thing missing is to add margins so that they work as they should in your case

to change the styles of the input we have the class `vs-input`

it would be something like that to add margins

```css
.myClassContainer .vs-input {
  margin: 8px
}
```

**Comment by dasisyouyu** [comment]
thanks you!!
does not patch note describe the update method

this one not work.

`vs-type="password"`

![2018-07-11 15 02 26](https://user-images.githubusercontent.com/16145243/42553322-7418f11a-851b-11e8-8175-c8799dab8075.png)
![2018-07-11 15 01 56](https://user-images.githubusercontent.com/16145243/42553323-7444574c-851b-11e8-8be5-be4b9cc9d753.png)

**Comment by dasisyouyu** [comment]
@luisDanielRoviraContreras N/O

**Comment by luisDanielRoviraContreras** [comment]
For support issues, the vs-type was removed and you can use the normal type and the default validations are also eliminated. Now they are manual for better handling and flexibility

**Comment by dasisyouyu** [comment]
i see. thanks u!

**Comment by dasisyouyu** [comment]
@luisDanielRoviraContreras i think that 'type="password"' not working.

**Comment by dasisyouyu** [comment]
How do you expect to specify the type setting?

```
<vs-input type="hoge" /> no
```

**Comment by luisDanielRoviraContreras** [comment]
I already solve it in the last version, thank you very much for the contribution to improve Vuesax

https://lusaxweb.github.io/vuesax/components/input.html#label

**Comment by dasisyouyu** [comment]
sry i dont Understand.
What item is referring to?

` <vs-input disabled="true" vs-label="Password" vs-placeholder="Disabled" v-model="value2"/>`

**Comment by dasisyouyu** [comment]
@luisDanielRoviraContreras N/O

**Comment by luisDanielRoviraContreras** [comment]
Sorry that documents do not change the idea is to try if it works with the latest version
