### ISSUE TITLE
Making component API developer friendly

### ISSUE THREAD

**Issue by abhaywawale** [lusaxweb/vuesax#172]
**Is your feature request related to a problem? Please describe.**
We have component name as `vs-button` with `vs` prefix which is great. But the API also have unnecessary `vs` prefix like `vs-type`, `vs-color` and so on. This looks like they are also component.

**Describe the solution you'd like**
What I would propose is the removal of the prefix from API and we can change name of some which will collide with the native attributes of the HTML.

**Comment by luisDanielRoviraContreras** [comment]
it is unnecessary but it is to determine the properties of the component as `vs-color` if we add only `color` it could be somewhat confusing, besides now if we change all the properties by removing the **vs** it would have problems with the previous versions

you have to think very well before changing them all or make a complete migration plan

**Comment by abhaywawale** [comment]
Maybe it can be done for next major release.

**Comment by luisDanielRoviraContreras** [comment]
If exact as for the **4.0** also thank you very much and if I need help you notice
