### ISSUE TITLE
vs-popup not expanding vertically to contain list

### ISSUE THREAD

**Issue by goofballtech** [lusaxweb/vuesax#174]
Windows OS 
npm v6.1.0
node v8.11.3
Chrome 67

I have a page made with some Vuesax tables. Within my page there is an option to open a selection of items in a popup. This popup is styled for printing so it's just black text on a white background. 

Nothing really fancy in the popup. Just a couple buttons and a v-for to display the array. The popup window properly sizes as long as there aren't more item in the array than can fix vertically within the screens frame.

**Comment by goofballtech** [comment]
as directed by @dasisyouyu on discord the below code worked for me. 

```
.con-popup>>>.vs-popup {
  overflow: scroll;
}
```

**Comment by luisDanielRoviraContreras** [comment]
I will implement it in the component and I will advise you to review it, thank you very much for the contribution
