### ISSUE TITLE
Binding image in card with relative url

### ISSUE THREAD

**Issue by nordbit** [lusaxweb/vuesax#177]
Os: linux
Node: 8.11.3
Vuesax: 3.1.43
PM: yarn 1.7

The API returns image thumbnail  relative url:
`"/uploads/images/photo1_thumb.jpg"`

It works when consumed within clean Vue:
`<img v-bind:src='image.thumb' >`

but not when I try using it in in Vuesax like this:
`<vs-card-media vs-media='image.thumb'></vs-card-media>`
or
`<vs-card-media vs-media={{ image.thumb }}></vs-card-media>`

**Comment by luisDanielRoviraContreras** [comment]
In the update of the `vs-card` component, I will solve the problem. Thank you very much when you update it.

**Comment by nordbit** [comment]
It works.
<vs-card-media :vs-media='image.thumb'></vs-card-media>
<vs-card-media v-bind:vs-media='image.thumb'></vs-card-media>
