### ISSUE TITLE
Updating progress bar percentage doesn't showing the bar

### ISSUE THREAD

**Issue by REBELinBLUE** [lusaxweb/vuesax#178]
I have a progress bar which is being updated every second, if I look in vue-devtools the `vsPercent` is being updated by my code but `data.percent` remains unchanged.

I am possibly being really stupid but how do I update the progress bar?

**Comment by REBELinBLUE** [comment]
Thanks, you can see it if you check out http://github.com/REBELinBLUE/pomodoro.git

http://dropshare.rebelinblue.com/vl2fAkpnaB.gif

The progress bar at the top should change

**Comment by luisDanielRoviraContreras** [comment]
Ready and updated in the latest version, thank you very much for the contribution
