### ISSUE TITLE
Unknown custom element: <vs-button>

### ISSUE THREAD

**Issue by jupox** [lusaxweb/vuesax#179]
After install Vuesax via npm install version 3.1.45, we have this error message on console:

_**"Unknown custom element: <vs-button> - did you register the component correctly? For recursive components, make sure to provide the "name" option."**_

When open dialog:
<vs-button @click="openAlert('primary')" vs-color="primary" vs-type="flat">Alert Primary</vs-button>

openAlert(color){
      this.colorAlert = color || this.getColorRandom()
      this.$vs.dialog({
        color:this.colorAlert,
        title: `Dialog - ${this.colorAlert}`,
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        accept:this.acceptAlert
      })
    },
    acceptAlert(){
      this.$vs.notify({
        color:this.colorAlert,
        title:'Accept Selected',
        text:'Lorem ipsum dolor sit amet, consectetur'
      })
    },
    getColorRandom(){
      function getRandomInt(min, max) {
        return Math.floor(Math.random() * (max - min)) + min;
      }
      return `rgb(${getRandomInt(0,255)},${getRandomInt(0,255)},${getRandomInt(0,255)})`
    }

For this.$vs.dialog doesn't work:
![dialogvsbutton](https://user-images.githubusercontent.com/4061504/43012699-7a51b07e-8c0c-11e8-8c18-7803ff3bb3a7.png)

But if change for this.$vs.confirm or this.$vs.alert buttons works fine

![alert](https://user-images.githubusercontent.com/4061504/43012782-b41143ce-8c0c-11e8-972a-c54b2591bdd0.png)
![confirm](https://user-images.githubusercontent.com/4061504/43012783-b42f56d4-8c0c-11e8-8cef-6204e00c1768.png)

on this.$vs.dialog buttons are broken.

Thanks!!!

**Comment by luisDanielRoviraContreras** [comment]
You could pass me a codepen or a repo to duplicate the error and fix it thank you very much

**Comment by brunokunace** [comment]
@jupox working fine here, you have problem yet?

example:
https://codepen.io/anon/pen/MqvLYR

**Comment by JhonatanPereira** [comment]
Any way to fix this? I'm having the same problem
