### ISSUE TITLE
Textarea

### ISSUE THREAD

**Issue by quangIO** [lusaxweb/vuesax#180]
We already have `<vs-input />` but not `<vs-textarea />`

**Comment by luisDanielRoviraContreras** [comment]
I'm going to add the ** vs-textarea ** component after finishing the ssr support in all the components already created. Thank you very much for the contribution, when you have created, I will notify you so you can check it

**Comment by luisDanielRoviraContreras** [comment]
The component vs-textarea was added in the last update, thank you very much for the contribution

http://localhost:7070/vuesax/components/textarea.html#label
![textarea-vuesax](https://user-images.githubusercontent.com/31676496/46095739-3cd4e400-c18b-11e8-81a1-6acb7332e71f.gif)

**Comment by fergardi** [comment]
Shouldn't be this the same style as the normal input?

![image](https://user-images.githubusercontent.com/3602272/48491978-134e4580-e829-11e8-96f9-26138a7b86a6.png)

- The font style is smaller
- There are no primary colors applied by default
- The textarea label is different from the input label
- The textarea label does not jump top like the input label does

**Comment by ngekoding** [comment]
How can I make textarea style same with input? Like border, color, etc. 
Because when I use input and textarea at same page with different style, it's look so bad.

**Comment by luisDanielRoviraContreras** [comment]
we are going to add a variant so that it is equal to the input, thank you very much for the contribution

**Comment by luisDanielRoviraContreras** [comment]
Ready and the style is similar

**Comment by amirabbasTehrani** [comment]
how can I use this component? is it made for version 4?
