### ISSUE TITLE
vs-dialog's vs-accept-text not changing the text

### ISSUE THREAD

**Issue by VerzatileTom** [lusaxweb/vuesax#182]
Vuesax version: "^3.1.30"

```vue
<vs-dialog
    @vs-cancel="menu.name = ''"
    @vs-accept="createNewMenu"
    :vs-active.sync="createMenuPrompt"
    :vs-is-valid="validName"
    vs-title="Create a new menu"
    vs-accept-text="Create"
>
    <div class="con-exemple-prompt">
        Enter the name of the menu.
        <vs-input placeholder="Name" v-model="menu.name" />

        <vs-alert :vs-active="!validName" vs-color="danger" vs-icon="new_releases" >
            Please enter the menu name.
        </vs-alert>
    </div>
</vs-dialog>
```

I tried to change the text of the confirm button from "Accept" to "Create" but it seems not changing the text at all. Console is not showing any errors too.

**Comment by luisDanielRoviraContreras** [comment]
What kind of dialog is what you want to show?

**Comment by VerzatileTom** [comment]
@luisDanielRoviraContreras A prompt. 

In the docs, it says you call the component like `<vs-prompt></vs-prompt>` but it does not work, then I found out it has to be called like `<vs-dialog></vs-dialog>`.

**Comment by luisDanielRoviraContreras** [comment]
You could try the latest version
