### ISSUE TITLE
vsDropDownMenu not removed from body when destroyed

### ISSUE THREAD

**Issue by REBELinBLUE** [lusaxweb/vuesax#183]
When the vsDropDownMenu is mounted you insert the real dropdown as the first child of the body, but when the vsDropDownMenu is destroyed it isn't removed, that means as you navigate around a SPA you can end up with lots of them dropdowns in the document

I solved this with

https://github.com/REBELinBLUE/pomodoro/blob/master/src/components/Settings/Dropdown.vue#L42

but obviously it isn't the best way as the component should clean up after itself

**Comment by luisDanielRoviraContreras** [comment]
The error was corrected in the latest version, thank you very much
