### ISSUE TITLE
Сlosing the dropdown list (Select component)

### ISSUE THREAD

**Issue by Alexeykhr** [lusaxweb/vuesax#185]
When we select the maximum possible number of elements, other elements become inactive. But when you click on this part of the area (where empty) - the list does not close. When you click on the text or an invisible icon - the list closes.

Does not close - [https://prnt.sc/kc7sqa](https://prnt.sc/kc7sqa)
Closes - [https://prnt.sc/kc7ss7](https://prnt.sc/kc7ss7)

Is it possible to make the closure of the list, and when you click on an empty space? Or it is better to pass a parameter through props, which with an inactive button hides the list, or did nothing. I prefer the second option :)

P.S. I found part of the code that closes the list

```vue
Path: src/components/vsSelect/vsSelectItem.vue

blur: (event) => {
  if(event.relatedTarget?!event.relatedTarget.closest('.vs-select-options'):true) {
    this.$parent.closeOptions()
  }
},
```

**Comment by luisDanielRoviraContreras** [comment]
Could you tell me what version of Vuesax you are using and if this same problem persists in the documents, thank you very much for the contribution

**Comment by Alexeykhr** [comment]
I'm sorry that I did not immediately add the version.

Just installed, version: 3.1.51

Link where I checked: https://lusaxweb.github.io/vuesax/components/selects.html#multiple

**Comment by luisDanielRoviraContreras** [comment]
It works for me as it should, does the problem still persist?

**Comment by luisDanielRoviraContreras** [comment]
![selectissues](https://user-images.githubusercontent.com/31676496/43360842-763e961e-928d-11e8-916f-220de04393ec.gif)

**Comment by Alexeykhr** [comment]
Yes, just tried it again through Firefox Developer Edition (62.0b12).

Result: [https://prnt.sc/kc8ey9](https://prnt.sc/kc8ey9)

Try to open the drop-down list when it is almost at the bottom of the screen and preferably a larger list.

**Comment by Alexeykhr** [comment]
Yes, I just updated Google Chrome to 68.0.3440.75, the problem is.
In Firefox Developer Edition (62.0b12) there is no problem

The problem is observed. And the list should choose the rightmost:
[http://prntscr.com/kc8gws](http://prntscr.com/kc8gws)

**Comment by Alexeykhr** [comment]
Maybe not properly explained.

When the button is disabled. Click on the blue area (it contains text and a hidden icon) - closes the drop-down list.

[Screen](https://prnt.sc/kc8jxl)

P.S. Through what to do such gif, as you?

**Comment by luisDanielRoviraContreras** [comment]
Okay I got it, thank you very much. I'm going to fix it and let you know

**Comment by luisDanielRoviraContreras** [comment]
Ready has been updated by correcting the error

Thank you very much for the contribution

**Comment by vishnu-smbe** [comment]
hi, i am unable to close the pop up for the vs-select when i use multiselect.

**Comment by khanhhaquang** [comment]
Hi, i still cant close the popup for vs-select multiple, any solutions for this ?

**Comment by vishnu-smbe** [comment]
no solution yet, but if i press the TAB button, i am able to close the multi select. but that is not the right way, if i click outside it should automatically close!.

**Comment by shirodkarpushkar** [comment]
Unable to close vs-select dropdown when i click outside.
Porblem persists for single as well as multi select 
I am using vuesax version 3.8.75

**Comment by kirtan403** [comment]
Not sure if this is relevant to this version or not, but I've did this with `javascript` on `vuesax-next` and it worked for me:

```
const delegate = function(element, eventName, elementSelector, handler) {
      console.log('adding event listner')
      element.addEventListener(
        eventName,
        function(e) {
          // loop parent nodes from the target to the delegation node
          for (
            var target = e.target;
            target && target != this;
            target = target.parentNode
          ) {
            if (target.matches(elementSelector)) {
              handler.call(target, e)
              break
            }
          }
        },
        true
      )
    }

    delegate(document, 'blur', '.vs-select__input', e => {
      document.querySelector('.vs-select__options').remove()
      e.target.parentElement.classList.remove('activeOptions')
    })
```

jQuery would look like this (not tested):

```
$(document).on('blur', '.vs-select__input', () => {
    $(this).parent().removeClass('activeOptions')
    $('.vs-select__options').remove()
})
```

I hope this helps someone, who are trying to work with keyboard navigation.
