### ISSUE TITLE
Opening the dropdown list (Select component)

### ISSUE THREAD

**Issue by Alexeykhr** [lusaxweb/vuesax#186]
Vuesax: 3.1.51
Browser: Chrome 67
OS: Windows 10

When there is not enough screen height (from the list to the bottom of the screen) to open the drop-down list - it opens at the top of the site.

[Screen - http://prntscr.com/kc84p6](http://prntscr.com/kc84p6)

And errors in the console:
"Uncaught TypeError: Cannot read property 'clientHeight' of undefined"

In this file:
/src/utils/index.js:15

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much and review and the problem if it is happening I will fix it and I will notify you thanks for the contribution

**Comment by luisDanielRoviraContreras** [comment]
It works in the latest version, thank you very much

**Comment by Alexeykhr** [comment]
Thank you, the components look amazing
