### ISSUE TITLE
No debe especificar el ancho directamente para un elemento

### ISSUE THREAD

**Issue by dasisyouyu** [lusaxweb/vuesax#187]
<img width="1014" alt="2018-07-30 19 07 13" src="https://user-images.githubusercontent.com/16145243/43391543-e2160544-942b-11e8-8b76-e3c757a4aa34.png">

<img width="99" alt="2018-07-30 19 08 24" src="https://user-images.githubusercontent.com/16145243/43391571-f8f8ab86-942b-11e8-833c-94467d665f61.png">

No debe especificar el ancho directamente para un elemento
clientWidth no funciona bien?

**Comment by luisDanielRoviraContreras** [comment]
What is the problem? the width of the component is based on its content

**Comment by dasisyouyu** [comment]
![2018-07-31 13 08 21](https://user-images.githubusercontent.com/16145243/43437235-ddcdefc8-94c2-11e8-993b-12de8bf90346.png)
![2018-07-31 13 08 17](https://user-images.githubusercontent.com/16145243/43437236-de0561f6-94c2-11e8-83aa-8caa54c49cee.png)

vuesax@^3.1.51

No sé la causa, entonces investigaré.

**Comment by luisDanielRoviraContreras** [comment]
The component verifies how much of total width it has to automatically implement the width
