### ISSUE TITLE
The close button of the dialog is not work.

### ISSUE THREAD

**Issue by dasisyouyu** [lusaxweb/vuesax#188]
`:vs-active="$store.state.editBook.isActiveEditPopup"`
 Does not work if you refer directly to the state in the store like this

not work this.
`vuesax/src/functions/vsDialog/index.vue :158`
`this.$emit('update:vsActive',false)`

- macOS: 10.13.5
- node: v10.6.0
- Vuesax: 3.1.51
- Browser version: chrome 67.0.3396.99
- Which package manager did you use for the install?: yarn

**Comment by luisDanielRoviraContreras** [comment]
You could try adding something like this

```html
:vs-active.sync="$store.state.editBook.isActiveEditPopup"
```

**Comment by dasisyouyu** [comment]
TY!!!! I was able to confirm that it works.

**Comment by dasisyouyu** [comment]
`:vs-active.sync` 

```
//don't work.
@vs-cancel="$store.commit('addBook/addPopupToggle')"
```

addPopupToggle is popup show toggle flag.

**Comment by luisDanielRoviraContreras** [comment]
Try a method that internally calls the commit

**Comment by thukuwanjiku** [comment]
Not sure if I should ask this one here, but my vs-popup close button shows the word 'close' instead of  'x' (like those in the documentation). How do I fix this please?
![vs-popup](https://user-images.githubusercontent.com/17809323/44332379-918e8c00-a474-11e8-8cc9-419b176ff0d6.png)

**Comment by dasisyouyu** [comment]
@thukuwanjiku 
https://lusaxweb.github.io/vuesax/vuesax/#use

```
npm install material-icons --save
import 'material-icons/iconfont/material-icons.css';
```
I have to import it separately

**Comment by luisDanielRoviraContreras** [comment]
@thukuwanjiku Did you manage to solve the source?

**Comment by thukuwanjiku** [comment]
Thank you for that @dasisyouyu  Looks like I had forgot the import for the material icon css. 
@luisDanielRoviraContreras yes, @dasisyouyu  answer solved it for me.
