### ISSUE TITLE
Error on importing functions 

### ISSUE THREAD

**Issue by cristi200915** [lusaxweb/vuesax#193]
when i try to use 
Vue.use(vsFunctions)

Error: Couldn't find preset "@vue/app" relative to directory

- OS: Win10
- Node -v: v8.11.3
- Vuesax: 3.2.0
- Browser Chrome 67.0.3396.99 x64
- npm

**Comment by luisDanielRoviraContreras** [comment]
you could add all the js to see how you imported the library

**Comment by luisDanielRoviraContreras** [comment]
You could try removing the full Vuesax import to verify that the error is only in **vsFunctions**, thank you very much

```js
...
-- Vue.use(Vuesax, {
    theme: {
        colors: {
            primary: 'rgb(96, 31, 255)',
            success: 'rgb(23, 201, 100)',
            danger: 'rgb(242, 19, 93)',
            warning: 'rgb(255, 130, 0)',
            dark: 'rgb(36, 33, 69)'
        }
    }
}) // delete this import and check if the error persists

...

**Comment by cristi200915** [comment]
Actually the error still without the full Vuesax import

**Comment by cristi200915** [comment]
I'm using Laravel Mix for compilation

**Comment by cristi200915** [comment]
I've finally solved removing the presest on vuesax package.json 

"babel": {
    "presets": [
      "@vue/app"
    ]

**Comment by luisDanielRoviraContreras** [comment]
@cristi200915 Does the error persist using the entire framework?

**Comment by cristi200915** [comment]
No @luisDanielRoviraContreras eveything is right

**Comment by luisDanielRoviraContreras** [comment]
@cristi200915 then the problem is only when importing the functions independently I will review it to give you an answer at the moment just use vuesax completely, thank you very much

**Comment by luisDanielRoviraContreras** [comment]
Still have the error?

**Comment by gopal-g** [comment]
I am getting an error similar to this one while trying to use the vsLoading individually

I have tried following ways to import just the loading component no other component. 
1. ` import vsLoading  from 'vuesax/dist/functions/vsLoading `
2. ` import vsLoading  from 'vuesax/dist/functions/vsLoading/index ` 
3. ` import {vsLoading} from 'vuesax/dist/functions `

This is the error I am getting 

 `Couldn't find preset "@vue/app" relative to directory <my project directory>/node_modules\vuesax ` 

How can I fix this ? 

Thank you.
