### ISSUE TITLE
Remove dist directory and using .gitignore and .npmignore

### ISSUE THREAD

**Issue by potato4d** [lusaxweb/vuesax#199]
**Is your feature request related to a problem? Please describe.**

Repository Size and Maintainability.

**Describe the solution you'd like**

1. for NPM package, include `dist` dir and exclude `src` dir.
2. for Git Repo, include `src` dir and exclude `dist` dir.

**Describe alternatives you've considered**

1. Delete `dist` dir
2. add `dist` dir to `.gitignore`
3. create `.npmignore`
4. **Do not write** `dist` in the `.npmignore`

**Comment by luisDanielRoviraContreras** [comment]
is already using `.gitignore` and `.npmignore` except for the dist folder in the repository that I think is good for this hay, but do you think we should remove it?

**Comment by potato4d** [comment]
@luisDanielRoviraContreras 

Sorry, The files already existed.

- - -

I think that it is good to delete it.
When dist is deleted...

### Pros

- It is possible to prevent code in dist from being accidentally committed
- Contribute to lightening the Git repository
- It is clear that a person wishing to contribute is a file that `src` should edit.

**Comment by luisDanielRoviraContreras** [comment]
Ready already added to `.gitignore` tnks
