### ISSUE TITLE
Feature request : Notification

### ISSUE THREAD

**Issue by ChangJoo-Park** [lusaxweb/vuesax#2]
I found  notification in document. When I click dialog (confirm and prompt too) awesome notification showed up right bottom on screen. But, I can't find notification API in document.

**Comment by lusaxweb** [comment]
Good friend when you refer to the notification the documentation is in

https://lusaxweb.github.io/vuesax/#/docs/Notifications

and the one to execute it when approving the dialog can be this

      this.$vs.confirm({
          title:'Dialog Confirm Default',
          text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
          color:'danger',
          confirm:()=>{


            // notification confirm 
            this.$vsNotify({   //<---------
              title:'Eliminado',
              text:'Lorem ipsum dolor sit amet',
              color:'danger',
            }) 


          }

**Comment by ChangJoo-Park** [comment]
Oh, really sorry 😭 

thank you for made this awesome components!
