### ISSUE TITLE
Sidebar to does not change the active item in sidebar (Screenshot attached)

### ISSUE THREAD

**Issue by iharmanpannu** [lusaxweb/vuesax#201]
I am using the sidebar to route between different views but for some reason, it won't change the active item in the sidebar even when I am on a different page in the router.

Screenshot attached
<img width="509" alt="screen shot 2018-08-08 at 7 25 02 pm" src="https://user-images.githubusercontent.com/26369180/43874514-1715c8a8-9b41-11e8-9a3d-a201a9995c86.png">

**Comment by luisDanielRoviraContreras** [comment]
You are using the property `vs-active` ? , could you pass me the code thanks

**Comment by Mee1ad** [comment]
i have same issue, when i use the "to" property this issue happend
this work fine:
<vs-sidebar-item @click="actives=2" :vs-active="actives==2" vs-icon="movie">
   Dashboard1
</vs-sidebar-item>

this not:
<vs-sidebar-item @click="actives=1" :vs-active="actives==1" vs-icon="account_box" to="card">
    Dashboard2
</vs-sidebar-item>

**Comment by luisDanielRoviraContreras** [comment]
#154
