### ISSUE TITLE
Bug using vs-type in vs-input

### ISSUE THREAD

**Issue by IsraelDCastro** [lusaxweb/vuesax#206]
I was trying to use vs-type with vs-input, but it doesn't work, I have to use type as the common attribute in HTML.

Doesn't work

`
<vs-row vs-type="inline-flex" vs-justify="center" vs-align="center">
			<vs-col vs-xs="12" vs-sm="8" vs-lg="6" vs-type="inline-flex" vs-justify="center" vs-align="center">
				<div class="register-form">
					<h1 class="text-center">Register</h1>
					<form action="">
						<vs-input vs-type="email" vs-label="Name" vs-placeholder="Placeholder" v-model="value1"/>
					</form>
				</div>
			</vs-col>
		</vs-row>
`

It works
`
<vs-row vs-type="inline-flex" vs-justify="center" vs-align="center">
			<vs-col vs-xs="12" vs-sm="8" vs-lg="6" vs-type="inline-flex" vs-justify="center" vs-align="center">
				<div class="register-form">
					<h1 class="text-center">Register</h1>
					<form action="">
						<vs-input type="email" vs-label="Name" vs-placeholder="Placeholder" v-model="value1"/>
					</form>
				</div>
			</vs-col>
		</vs-row>
`

**Comment by luisDanielRoviraContreras** [comment]
In the last update of the component, the `vs-type` property was removed and left as the normal property of a `type` input, thank you very much for the contribution, you have to change the documents and remove it from the API

**Comment by luisDanielRoviraContreras** [comment]
The API has already been updated thanks for the contribution
