### ISSUE TITLE
Vs-select-item do not show properly in vs-popup

### ISSUE THREAD

**Issue by EanKeen** [lusaxweb/vuesax#207]
**Operating System:** Microsoft Windows 10
**Vuesax Version:** 2.5.17
**Browser:** Mozilla Firefox 61.0.2 and Google Chrome 68

When I use the vs-select component inside of the vs-popup, each of its vs-select-item components does not show above the vs-popup component. Instead, it appears behind the vs-popup component.

I have A [JSFiddle](https://jsfiddle.net/dmov694t/3/) that replicates the issue.
![Photograph](https://user-images.githubusercontent.com/24364012/44073251-c804cde4-9f47-11e8-9719-f22ee911cf01.png)

**Comment by luisDanielRoviraContreras** [comment]
That sure is a problem of `z-index` I'm going to verify and fix it thank you very much

**Comment by luisDanielRoviraContreras** [comment]
Ready and the problem is solved in the latest version thank you very much for the contribution !
![vuesax-example-select-popup](https://user-images.githubusercontent.com/31676496/44074561-0e81b600-9f67-11e8-91e2-934dd4250022.gif)

**Comment by EanKeen** [comment]
Thank you very much!

**Comment by ziltonvasconcelos** [comment]
This error continues inside vs-prompt

**Comment by jsinhSolanki** [comment]
@ziltonvasconcelos Please create a new issue for vs-prompt component(this is for popup component). And this is just an issue of z-index. You can also create a pull request for this.
Thank You

**Comment by xkris6x** [comment]
Hi. how did you solve your problem

**Comment by luisDanielRoviraContreras** [comment]
the error has already been fixed

thank you
