### ISSUE TITLE
i want show different text in select component after item option tag

### ISSUE THREAD

**Issue by webafra** [lusaxweb/vuesax#214]
hello .

i want show different text in select component option tag
for example : 

```

<vs-select
      v-model="select"
      >
      <vs-select-item :key="index"  :vs-value="item.value" :vs-selectedText="item.selectedText" :vs-text="item.text" v-for="(item,index) in options" />
    </vs-select>


or 

<vs-select
      v-model="select"
      >
      <vs-select-item :key="index"  :vs-value="item.value" :vs-text="item.text" v-for="(item,index) in options" >{{ item.selectedText }}</vs-select-item>
    </vs-select>


```

```
data() {
  return {
     select : null,
     options: [
           {value: 1, label: 'label 1', selectedText: 'show after select label 1'},
           {value: 2, label: 'label 2', selectedText: 'show after select label 2'},
           {value: 3, label: 'label 3', selectedText: 'show after select label 3'},
      ]
  }

}
```

thanks .

**Comment by luisDanielRoviraContreras** [comment]
Now if I understand you well I will do the update and I will warn you to review it

**Comment by luisDanielRoviraContreras** [comment]
The component has already been updated with the new functionality, it has a different approach but the result is as expected

https://lusaxweb.github.io/vuesax/components/selects.html#is-selected-item

thanks for the contribution

**Comment by webafra** [comment]
@luisDanielRoviraContreras , Thanks for added this Futures but my idea is : 

before Select ( show list item ) : 
![image](https://user-images.githubusercontent.com/8689072/44943696-14520800-ade0-11e8-9c82-433b0b300dfa.png)


after select item : 
![image](https://user-images.githubusercontent.com/8689072/44943703-27fd6e80-ade0-11e8-814c-6d68e295758a.png)

my idea is : 
1 - remove ---- ( or other character ) in selected item ( example => :vs-selectedText="item.text.replace( /-/g, '' )"  ) only when show selected item ( closed lists modal )

![image](https://user-images.githubusercontent.com/8689072/44943745-e8835200-ade0-11e8-9d3c-354f01d08e56.png)


example with code : 
```
<vs-select-item :key="index"  :vs-value="item.value" :vs-selectedText="item.value.replace(/-/g, '' )" :vs-text="item.text" v-for="(item,index) in options" />
    </vs-select>
```

**Comment by luisDanielRoviraContreras** [comment]
Now you can manipulate the selected one as you want with the boolean that returns `is-selected.sync`

**Comment by webafra** [comment]
thank you .

this method don't work on computed property ?

**Comment by luisDanielRoviraContreras** [comment]
Now what you need can be done you just have to manipulate the property `is-selected.sync`
![select-example](https://user-images.githubusercontent.com/31676496/47183109-2ab31500-d2f5-11e8-95fc-5de97ebbfd60.gif)
