### ISSUE TITLE
Reposition tooltip on mobile devices to position at bottom

### ISSUE THREAD

**Issue by gkarmas** [lusaxweb/vuesax#215]
When i set it to left or right, it squeezes on the sides of the screen. It would be convenient to re-position automatically at bottom on small devices
![lensexec - corporate photography 2018-08-31 13-47-53](https://user-images.githubusercontent.com/8575682/44928253-536f5300-ad25-11e8-941b-0b64dc27ecfe.png)

**Comment by luisDanielRoviraContreras** [comment]
Ready and the problem was solved in the latest version

thanks for the contribution

**Comment by gkarmas** [comment]
@luisDanielRoviraContreras just tested the new version. Thank you for the update. The tooltip is not positioned at the bottom, instead it repositions to the bottom-left outside of the screen
<img width="383" alt="screen shot 2018-08-31 at 5 56 19 pm" src="https://user-images.githubusercontent.com/8575682/44937434-3fd4e400-ad47-11e8-80bc-5540ed0a4d60.png">

**Comment by luisDanielRoviraContreras** [comment]
You have a repository to test live and fix it to the extent or if you can pass me the code of how you implement the tooltip would be great

**Comment by brunokunace** [comment]
@gkarmas you can send a example of this? or talking about if you fix it.  Thanks!

**Comment by luisDanielRoviraContreras** [comment]
When I try to duplicate the problem everything works well, thank you very much for the contribution

![tooltip-example-iphone](https://user-images.githubusercontent.com/31676496/47181705-bd51b500-d2f1-11e8-877d-32a9d299f4b4.gif)
