### ISSUE TITLE
please add automatic upload file

### ISSUE THREAD

**Issue by webafra** [lusaxweb/vuesax#217]
hello lusaxweb and thanks for this package 👍 

please add Automatic upload file or image after select in uploader Component .
this Feature required for create product on ecommerce !

thank You :)

**Comment by luisDanielRoviraContreras** [comment]
It's a very good idea, I'm going to add it and I'll let you know

**Comment by luisDanielRoviraContreras** [comment]
@webafra The upload functionality is now added automatically, thank you very much for the contribution

https://lusaxweb.github.io/vuesax/components/upload.html#automatic
