### ISSUE TITLE
every new alert create a div on body, closing it isn't removing it

### ISSUE THREAD

**Issue by ilanbenyos** [lusaxweb/vuesax#225]
when opening an alert - a div element is being created on the body, closing it just give's it display:none, not removing it. opening a new one adds another element so you ends with plenty of hidden divs you can do nothing with. 

is that the right way?

**Comment by luisDanielRoviraContreras** [comment]
I'm going to verify to eliminate the element of the DOM, thank you very much for the contribution

**Comment by brunokunace** [comment]
@ilanbenyos it solve your problem?

**Comment by luisDanielRoviraContreras** [comment]
@brunokunace thanks for warning, I happened to close it
