### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by lion-man44** [lusaxweb/vuesax#228]
https://github.com/lusaxweb/vuesax/blob/master/src/components/vsSlider/main.styl#L92

Typo?
Or Spanish?

I think spelling `isEquals` .

**Comment by luisDanielRoviraContreras** [comment]
it's a mistake the idea was `isEquals`, can you make a PR fixing this?

**Comment by lion-man44** [comment]
OK.

I make a PR when workspace arrive.
