### ISSUE TITLE
Ability to have custom colors for the background of vs-popup

### ISSUE THREAD

**Issue by StuffBySpencer** [lusaxweb/vuesax#23]
The current popup box is pure white, and it would be nice to be able to change the color of it.
I've tried doing this directly by targeting `.vs-popup` in css but it doesn't work. Even with the `!important` tag.

Also, being able to change the color of the close button would be helpful as well.
Maybe something like `vs-color` and `vs-close-button-color` on the `vs-popup` tag?

**Comment by luisDanielRoviraContreras** [comment]
excellent friend to add support and I would like to thank you very much for your contribution.
