### ISSUE TITLE
Add support for vue-router to vs-button

### ISSUE THREAD

**Issue by DobaKung** [lusaxweb/vuesax#230]
**Is your feature request related to a problem? Please describe.**
The `Topbar` component uses `vs-button` as a navigation link, but `vs-button` doesn't work with vue-router.

**Describe the solution you'd like**
Add support for vue-router to `vs-button`.

**Describe alternatives you've considered**
Wrapping `router-link` around `vs-button` works, but breaks original styling.

**Additional context**
None

**Comment by luisDanielRoviraContreras** [comment]
The component will be updated completely to do so I add this functionality, thank you very much for the contribution

**Comment by emanuelmutschlechner** [comment]
@luisDanielRoviraContreras did you already implement this feature?

**Comment by luisDanielRoviraContreras** [comment]
If you are right, it has already been implemented, thank you very much for advising and the contribution you are giving us.

**Comment by edimitchel** [comment]
You misunderstood @emanuelmutschlechner, he asked you if it's done..
I'm front of the problem currently.. By passing a button in a `vs-navbar-item` component as this : 
```
<router-link to="/path" tag="vs-button" type="gradient" vs-icon="edit"></router-link>
```
... it's working but `vs-icon` prop seems to not be taken..

**Comment by edimitchel** [comment]
Yes, it's good, I have see this prop just few minutes after posting my comment :P
