### ISSUE TITLE
please add ajax search on Autocomplete select component

### ISSUE THREAD

**Issue by webafra** [lusaxweb/vuesax#231]
hello .

please add ajax search on Autocomplete select component for find item after search .

Similar component : select2

thanks 👍

**Comment by luisDanielRoviraContreras** [comment]
@kaungmyatlwin If it is the best idea! so the user has more flexibility and can manipulate and obtain the data in the way that he considers best

if you can do a PR on this it would be great

**Comment by kaungmyatlwin** [comment]
Sure! I'll look into it
