### ISSUE TITLE
workflow to contribuiting with vuesax

### ISSUE THREAD

**Issue by brunokunace** [lusaxweb/vuesax#232]
Hi @luisDanielRoviraContreras , 

first, sorry for this issue, i dont have any channel to make this conversation with you, you can close after read.

I try to help vuesax repo, but i can make a workflow to fast and right way to test modifications for this.
Vuesax use the compiled source on node_modules, it makes to no chances get effect when change anything directly on node_modules files.

You have/can make to call with me/us for explain a best way to create app for work and make PR's for vuesax?

Thanks for read.

**Comment by luisDanielRoviraContreras** [comment]
we can speak for personal discord and that's how we fit better and I help you

**Comment by brunokunace** [comment]
thanks for read, 
please, when we have a time,  call me on discord,  Brun00#6695.

waiting for you,  ty ty...
