### ISSUE TITLE
Table in Layout - Grid Contains Spanish in English Docs

### ISSUE THREAD

**Issue by Bshally** [lusaxweb/vuesax#24]
Some of the table headings are in Spanish, as well as the content in the columns labeled "Descripción".
https://lusaxweb.github.io/vuesax/#/en/docs/layout/grid
This seems to be the case with other tables as well.

I see also that the "Atras" & "Siguiente" buttons at the bottom of each page are left untranslated as well.

I'm not sure how the translation works, as I've never worked with a multilingual project, but here are what I believe to be accurate english translations for the table cells from the grid section:

- Ancho del vs-row o vs-colum
  - Width of the vs-row or vs-colum
- Distancia a la izquierda del col
  - Distance on the left side of the vs-col
- Defina la alinacion verticalmente de los elementos dentro del vs-row o vs-col	
  - Define the vertical alignment of the elements within the vs-row or vs-col
- Defina la alinacion horizontal de los elementos dentro del vs-row o vs-col	
  - Define the horizontal alignment of the elements within the vs-row or vs-col
- Cambia el orden del vs-col respecto a sus hermanos vs-col	
  - Changes the order of the vs-col with respect to sibling vs-col elements

If someone could explain how to implement translations in the project I could try my best to put english in where needed.

**Comment by luisDanielRoviraContreras** [comment]
the translation part is in process but if you can contribute changing any text in Spanish to English that would help me a lot and change the documentation of the layouts thank you very much for the contribution
