### ISSUE TITLE
Nuxt vuesax project: Seems missing Montserrat font

### ISSUE THREAD

**Issue by cocodrino** [lusaxweb/vuesax#242]
Hi guys, I'm trying to use vuesax inside my nuxt project, the components are imported ok and seems work right, but the font doesn't look good

check the image
![deepinscreenshot_seleccionar area_20180917114240](https://user-images.githubusercontent.com/616412/45633876-f555a600-ba6e-11e8-9bd1-e645b2a0bad0.png)

I notice that this code is missing in my project
```css
h1, h2, h3, h4, h5, h6 {
    font-family: MontserratThin;
}
```

my project is really basic right now...I created the plugin vuesax with this code inside
```ts
import Vue from 'vue'
import Vuesax from 'vuesax'
import 'material-icons/iconfont/material-icons.css';


import 'vuesax/dist/vuesax.css' //vuesax styles
Vue.use(Vuesax, {
    server:true,
    theme:{
      colors:{
        primary:'#5b3cc4',
        success:'rgb(23, 201, 100)',
        danger:'rgb(242, 19, 93)',
        warning:'rgb(255, 130, 0)',
        dark:'rgb(36, 33, 69)'
      }
    }
})

```
and my nuxt config
```js
plugins: [
    '~/plugins/vuesax',
  ],

```

also I think that would be great if you can include a template inside create-nuxt-app or at least https://github.com/nuxt/nuxt.js/tree/dev/examples...

thank you!!!

**Comment by luisDanielRoviraContreras** [comment]
We are going to make a template when we have a bit more mature components and framework structure

To change the primary colors you can do it with the Stylus variables so that it can work in SSR

**Comment by luisDanielRoviraContreras** [comment]
To change the colors in SSR https://lusaxweb.github.io/vuesax/theme/#change-colors-ssr
