### ISSUE TITLE
Is there any plans to develop a "Table" component?

### ISSUE THREAD

**Issue by yinjunonly** [lusaxweb/vuesax#249]
**Is your feature request related to a problem? Please describe.**
I need to develop a management type page, and this time the "table" component is essential.

**Describe the solution you'd like**
Add a "table" component

**Describe alternatives you've considered**
Using a third-party "table" component?can be yes, but the overall feeling of style is not very good.

**Comment by luisDanielRoviraContreras** [comment]
#96
Just working on that component at this time, would be created today in 2 days or so or 3 days for the complexity you want to achieve

As soon as I finish I update to add it and I can review it

thank you very much

**Comment by yinjunonly** [comment]
> [＃96此时](https://github.com/lusaxweb/vuesax/issues/96)
> 正在处理该组件，将在2天左右或3天内创建，以实现您希望实现的复杂性
> 
> 我一完成就更新添加它，我可以查看它
> 
> 非常感谢你



> #96
> Just working on that component at this time, would be created today in 2 days or so or 3 days for the complexity you want to achieve
> 
> As soon as I finish I update to add it and I can review it
> 
> thank you very much

Thank you.

**Comment by yinjunonly** [comment]
> #96
> Just working on that component at this time, would be created today in 2 days or so or 3 days for the complexity you want to achieve
> 
> As soon as I finish I update to add it and I can review it
> 
> thank you very much

Thank you.

**Comment by byrnecode** [comment]
Hi, to add to the table request, I hope it handles complex datas like datatable plugin. When our team are trying new frameworks, we always check their table components because that is the most tricky one. :)

**Comment by luisDanielRoviraContreras** [comment]
Added the vs-table component in the latest version, thank you very much

https://lusaxweb.github.io/vuesax/components/table.html#default

**Comment by ridvankaradag** [comment]
Hey, @luisDanielRoviraContreras is there any problem on site? Your link redirects to 404 (and some other links), correct link is https://lusaxweb.github.io/vuesax/vuesax/components/table.html

**Comment by luisDanielRoviraContreras** [comment]
@ridvankaradag Thank you very much for letting us know it has been fixed so that the links work as before, thanks for letting us know 

this should work again
https://lusaxweb.github.io/vuesax/components/table.html#default

**Comment by jrglaber** [comment]
Are you planning to add search, filtering, and server-side pagination?
