### ISSUE TITLE
website scrolling does notre work

### ISSUE THREAD

**Issue by reeslo** [lusaxweb/vuesax#25]
Scrolling with firefox mobile on Android not working :(

**Comment by luisDanielRoviraContreras** [comment]
in which component exactly does not scroll work? or is on the page

**Comment by reeslo** [comment]
Homepage I cant scroll, I can use navigation bar on right. But touch scrolling doesn't work.

On chrome ans firefox (OT3, Android 8)

On documentation page it very strange I can scroll, at bottom without problems and I go to top and (random) I can re-scroll at bottom and sometime just after hit top scroll wont work.

This just with firefox (tested mobile only)

**Comment by luisDanielRoviraContreras** [comment]
Ready friend and I have solved the scroll thank you very much for the contribution you can review it

**Comment by reeslo** [comment]
Chévere ;)
