### ISSUE TITLE
Can list groups be expanded and collapsed like sidebar groups?

### ISSUE THREAD

**Issue by CheyenneForbes** [lusaxweb/vuesax#250]

**Comment by luisDanielRoviraContreras** [comment]
Please explain the problem better, with an example of code and an image if possible to be able to assist you, thank you very much

**Comment by CheyenneForbes** [comment]
![image](https://user-images.githubusercontent.com/8251976/46034871-b5766a80-c0cf-11e8-854e-514a8d72f665.png)

**Comment by CheyenneForbes** [comment]
Would be great if there could be 2 versions

1. one for the rows of the Table component to make it look like above
2. a simpler one that's for the List component to make it look like this:

![image](https://user-images.githubusercontent.com/8251976/46035503-28341580-c0d1-11e8-93b4-efa29d931f00.png)

**Comment by luisDanielRoviraContreras** [comment]
For what you need you can use the table

https://lusaxweb.github.io/vuesax/components/table.html#expandable-data

Apart from the fact that the accordion component will be created soon, I think it would work too

**Comment by CheyenneForbes** [comment]
Oh wow, vuesax is even more amazing than I thought... regarding accordions, when will this be added?

**Comment by luisDanielRoviraContreras** [comment]
It is going to be implemented between these days, it is working on the correction of errors and then work on that new component, thank you very much continues to improve
