### ISSUE TITLE
Validation Input

### ISSUE THREAD

**Issue by natxocc** [lusaxweb/vuesax#26]
On the demo page, seems the validation is not working correctly.
Example:
On email input, doesn't appear the "vs-success-text" or "vs-danger-text" anywhere.
But the green o red color on validation works well.

PD: Felicidades por el elegante diseño!

**Comment by luisDanielRoviraContreras** [comment]
for the moment the `vs-success-text` or` vs-danger-text` are a title of the icon to see the text you have to pose on the test to see if it works and thank you very much
