### ISSUE TITLE
Responsive layout (vs-xs) grid does not work

### ISSUE THREAD

**Issue by hahuy95** [lusaxweb/vuesax#27]
Responsive layout (vs-xs) appearing the number as a text only

**Comment by luisDanielRoviraContreras** [comment]
you could tell me the exact case and where the problem occurs thank you very much

**Comment by luisDanielRoviraContreras** [comment]
Ready friend was just a detail many thanks I hope you review [Release](https://github.com/lusaxweb/vuesax/releases/tag/v3.0.4)
