### ISSUE TITLE
WYSIWYG editor Component

### ISSUE THREAD

**Issue by periscuelo** [lusaxweb/vuesax#272]
It's would be sounds good if we have in vuesax a component like `summernote` or something similar.
In some cases, it can be very helpfull.

Example: [https://summernote.org/](https://summernote.org/)

Thanks again for your excellent work.

**Comment by edimitchel** [comment]
See this WYSIWYG built (or wrappep) with Vue.js : **Vueditor**
https://github.com/hifarer/vueditor

**Comment by periscuelo** [comment]
It's a good example to try wrap it in vuesax. Then i would haven't other dependency in my build. Thanks 🙂

**Comment by edimitchel** [comment]
Here an more precise solution.
https://tiptap.scrumpy.io

I understand that you want but I think these complex components need to be done by third party..
