### ISSUE TITLE
Select (Multiselect option) Enhancement

### ISSUE THREAD

**Issue by natxocc** [lusaxweb/vuesax#28]
Great Framework!

A good enhancement would be have multiselect on select input.
For example, have a checkbox to select various options.

**Comment by luisDanielRoviraContreras** [comment]
Ready and there is support for multiple selection, thank you very much for the contribution

![screenshot_15](https://user-images.githubusercontent.com/31676496/40880692-98a3fc98-6683-11e8-92fb-2e55d4abe990.png)
