### ISSUE TITLE
can I close a modal through vuex???

### ISSUE THREAD

**Issue by cocodrino** [lusaxweb/vuesax#281]
Hola @lusaxweb, como el problema es un poco enredado y se que hablas español, voy a explicartelo muy por encima....tengo varias tarjetas...cuando hago click en una tarjeta quiero que se muestre un modal (popup) con información complementaria de esa tarjeta...la idea es que exista un solo modal y su activación y llenado sea al darle click a la tarjeta...

entonces cree un store con vuex que tiene algo como "detallesTarjeta" y dentro de mi modal en una propiedad computed reviso si ese valor tiene algo o si no...perfecto...ahora al darle click 

algo como asi
```js

<template lang="pug">
  vs-popup(title="detalles" , :active.sync="popupActivo")
    p
    | ....
</template>

<script>
export default {
  computed : {
    

    popupActivo(){
      return this.$store.getters.popUpDetails != null;
    }
  }
 
}
</script>


```

todo bien...pero como cierro la factura ahora? :D ...tendría que implementar mi propio boton de cerrado no???...existe alguna forma más elegante de realizar esta tarea?...gracias

**Comment by luisDanielRoviraContreras** [comment]
We added a `@close="myFunctionCloseStoreVuex"` so you can do it in a more simple way, it is executed when you click on the x, thank you very much
