### ISSUE TITLE
Avatar component does not find relative src image

### ISSUE THREAD

**Issue by Deltalus** [lusaxweb/vuesax#286]
- Mac OSX Mojave
- Node 10.10.0
- Vuesax 3.4.16
- Safari 12.0
- npm used to install

`<vs-avatar>` tag, src attribute does not pull from relative paths. When given a full URL image, it works fine, but when trying to use a local asset from the src/assets directory, the image is never found.
`<vs-avatar alt="Avatar" size="120px" src="../assets/image-to-load.png"/>`

**Comment by Deltalus** [comment]
I was able to resolve the issue by adding this to my vue.config.js file

`// vue.config.js
module.exports = {
    chainWebpack: config => {
        config.module
          .rule('vue')
          .use('vue-loader')
            .loader('vue-loader')
            .tap(options => {
              options.transformAssetUrls = {
                'vs-avatar': 'src'       
              }
              return options
            })
    }
}`

I do believe however that there should be a more elegant solution to this problem. If this type of options can be done directly when importing the Vuesax library, it would be very helpful.

**Comment by brunokunace** [comment]
It's is only in your webpack config, sorry but, its no is a valid issue with a vuesax repo.
Great for you can find a correction and explain for all.

**Comment by brunokunace** [comment]
@luisDanielRoviraContreras i sure to you can close

**Comment by Shaif821** [comment]
@Deltalus 

I'm having the same issue, I tried what you did, but it didn't do anything...
