### ISSUE TITLE
vsLoading wrong reference to class name in DOMTokenList

### ISSUE THREAD

**Issue by bpiaskiewicz** [lusaxweb/vuesax#289]
Hey!

I think that there's wrong reference to class name when looking for the loading elements at: https://github.com/lusaxweb/vuesax/blob/master/src/functions/vsLoading/index.js#L31

According to the spec (https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) the classList property return a collection of DOMTokenList (https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList) where values dont have the dot, so the class name should be used without it.

Simple pen that reproduce the problem: https://codepen.io/anon/pen/MPpLqZ

- OS: Linux
- Node.js version: v10.11.0
- Vuesax version: 3.5.0
- Browser version: Chrome 69.0.3497.100
- Which package manager did you use for the install? NPM

**Comment by luisDanielRoviraContreras** [comment]
Can you make a PR solving this?
