### ISSUE TITLE
Duration on notifications

### ISSUE THREAD

**Issue by kevindesousa** [lusaxweb/vuesax#29]
Hello,

I can't find a option to configure a global or specific duration for the Notification components.

The option exist ?

**Comment by luisDanielRoviraContreras** [comment]
Ready buddy and add the support of time in the notifications thank you very much for the contribution 

[Release](https://github.com/lusaxweb/vuesax/releases/tag/v3.0.5)

**Comment by kevindesousa** [comment]
Thank's a lot !! :)

Congratulations for your work!!
