### ISSUE TITLE
Components in Prompt errors

### ISSUE THREAD

**Issue by alexflorea2** [lusaxweb/vuesax#291]
- Your OS: CentOs
- Node.js version: 6.4.1
- Vuesax version: 3.5.0
- Browser version: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
- Which package manager did you use for the install? : Yarn

I am trying to launch a Prompt component that has another component as it's content.
I am getting the following errors. The same errors occur even if Prompt content is simple text.

```
vue.common.js?a8a0:593 [Vue warn]: $attrs is readonly.

found in

---> <VsPrompt> at index.vue
```
```
vue.common.js?a8a0:593 [Vue warn]: $listeners is readonly.

found in

---> <VsPrompt> at index.vue
```
```
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "vsActive"

found in

---> <VsPrompt> at index.vue
```
```
[Vue warn]: Unknown custom element: <vs-button> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <VsPrompt> at index.vue
```

Code:

My component that I am using in another page:
```
<template>
  <div>
      <vs-button vs-color="success" @click="showMediaModal">Import media</vs-button>

      <vs-prompt
              @vs-cancel="val=false"
              @vs-accept="val=true"
              :vs-active.sync="activeMediaModal">
          <div>
              <media-page v-on:media-selected-media="selectedMedia"></media-page>
          </div>
      </vs-prompt>
  </div>
</template>
<script>
    import MediaPage from '~/pages/admin/media/index';

    export default {
        data: function () {
            return {
                val:false,
                activeMediaModal: false
            }
        },

        components:{
            MediaPage
        },

        methods: {
            selectedMedia(e){
              console.log(e)
            },
            showMediaModal(){
               this.activeMediaModal = true;
            }
        },
    }
</script>
```

**Comment by brunokunace** [comment]
@alexflorea2 Hi, all right?

I try to simulate your issue, but i could not have this alerts on console.
maybe it errors is on you `media-page` component.

Look my example it your code (only modified on media-page)

https://codesandbox.io/s/n3zq0l6zqj

**Comment by alexflorea2** [comment]
Thank you for the sandbox. After more research I think my issue is related to this  [https://stackoverflow.com/questions/49585845/attrs-is-readonly-listeners-is-readonly-avoid-mutating-a-prop-directly](https://stackoverflow.com/questions/49585845/attrs-is-readonly-listeners-is-readonly-avoid-mutating-a-prop-directly)

I will investigate further and get back.

**Comment by ashleymoogle** [comment]
Is it fixed? I got the same issue (Electron-vue, vuex)

**Comment by Luummii** [comment]
> @alexflorea2 Hi, all right?
> 
> I try to simulate your issue, but i could not have this alerts on console.
> maybe it errors is on you `media-page` component.
> 
> Look my example it your code (only modified on media-page)
> 
> https://codesandbox.io/s/n3zq0l6zqj

Your example not work. If change version vuesax on 3.9.0. 

This problem exists. 
https://codesandbox.io/embed/vuesax-prompt-ldcws
