### ISSUE TITLE
Card Footer Empty - flow issue

### ISSUE THREAD

**Issue by alxpereira** [lusaxweb/vuesax#293]
Hi team, 

We are working on several projects using Vuesax, and we find some issues. 
The first is the card footer component slot, 

When empty it breaks the flow. 
As shown below, if i'm not using the footer, the component is pushing anyway the footer slot, breaking the css. 

```html
<vs-col vs-type="flex" vs-justify="center" vs-align="center" vs-w="6">
            <vs-card>
                <div slot="header">
                    <h1>
                        Title
                    </h1>
                </div>
                <div>
                    ... my content
                </div>
            </vs-card>
        </vs-col>
```

I've fixed temporary by hiding the footer

Temporary fix 
```scss
.vs-card-footer {
    display: none;
  }
```

Can you help on that, did I missed something ?

Details : 
- Browser : Chrome 60.0.4
- OS : MacOS High Sierra
- Node > 8

Thanks !
Alex

**Comment by luisDanielRoviraContreras** [comment]
I understand I am going to review it and I want to thank you very much for using Vuesax and I hope I can help you
