### ISSUE TITLE
.centerx doesn't work

### ISSUE THREAD

**Issue by alxpereira** [lusaxweb/vuesax#294]
Hi, 

When I'm trying to use the `.centerx` class on my elements, it doesn't work. (css properties align center, flex, etc... aren't loaded)

Package.json
```json
"vuesax": "^3.5.0"
```

Main.js
```js
...
import Vuesax from 'vuesax'
import 'vuesax/dist/vuesax.css'
Vue.use(Vuesax)
...
```
Details :

Browser : Chrome 60.0.4
OS : MacOS High Sierra
Node > 8

Any tip ?
Thanks !

**Comment by luisDanielRoviraContreras** [comment]
`.centerx` is a classe that is only in the documents is not found as such in the framework, to center the elements you can use the vuesax grid

https://lusaxweb.github.io/vuesax/layout/#flex-layout
