### ISSUE TITLE
Multiple components - behaviour when disabled is not consistent

### ISSUE THREAD

**Issue by Jacrys** [lusaxweb/vuesax#298]
By convention, disabled components should have the CSS cursor property set to default so that on hover, the component is not construed to be an interactable element. The components `vs-button`, `vs-radio`, `vs-tab`, and `vs-breadcrumb` already implement this behaviour. The change should be a simple one.  The components currently noted as affected are:
- `vs-select`
- `vs-switch`
- `vs-checkbox`
- `vs-input`
- `vs-input-number` (specifically the `btn-plus` and `btn-minus` sub-components, this seems to be a special case, where the buttons have the disabled overlay but remain clickable, and pointer cursor remains, even when one has reached the max number)
- `vs-upload`
- `vs-dropdown-item` (Background color & text color change still happen on hover)
- `vs-collapse`

**Comment by Jacrys** [comment]
If the above is agreeable, I am willing to help out with implementing this.

**Comment by luisDanielRoviraContreras** [comment]
I think it's a clear contribution that you can help us and in all cases you have the reason, thank you very much for the contribution
