### ISSUE TITLE
Other components should support icon packs

### ISSUE THREAD

**Issue by Jacrys** [lusaxweb/vuesax#299]
Looking through the documentation, it seems `vs-input` is the only component that accepts an alternative icon pack.  I would like to see this extended to all components that use a vs-icon prop.  This de-coupling of the framework from specific icon fonts to a more general support model should increase adoptability, especially for sites that are moving to this framework.

**Comment by Jacrys** [comment]
If the above is agreeable, I am willing to help out with implementing this.

**Comment by luisDanielRoviraContreras** [comment]
support for Icon Pack - great contribution by @Jacrys , now you can use Vuesax with for example Font Awesome
https://lusaxweb.github.io/vuesax/theme/icon.html
