### ISSUE TITLE
How to use a custom font on the Input placeholder?

### ISSUE THREAD

**Issue by LibertQuinten** [lusaxweb/vuesax#302]
` OS: Windows 10 ` 
` Node.js version: 10.11.0 `  
` Vuesax version: latest`   
` Browser version: I'm using the latest release of Electronjs`   
` Package Manager: npm `  
 
I setted up VueSax via the [Get Started docs](https://lusaxweb.github.io/vuesax/development/#install-in-project-via-npm-or-yarn) and everything works fine.  

But I'm wondering how I can use my own fonts(fontface already declared in my stylesheet) in the placeholder.
Can someone help me with this?

Code:

- HTML: ` <vs-input id="NameInput" vs-label-placeholder="Label-placeholder" v-model="value1"/>`

**Comment by luisDanielRoviraContreras** [comment]
@LibertQuinten What happened ? How did you solve? or it's not a problem really

**Comment by LibertQuinten** [comment]
@luisDanielRoviraContreras It isn't really a problem, I just omitted the `<input>` with a div container and setted the `font-family` to my own font.

Thanks for your response and this great ui library!
