### ISSUE TITLE
Too much nesting in CSS (specificity issue)

### ISSUE THREAD

**Issue by byrnecode** [lusaxweb/vuesax#309]
I'm having a hard time customizing my own theme because of a badly written CSS that is nested too much. There's no doubt you're a good designer man, but please read about **CSS Specificity** or **CSS specificity-graph**

Code like this is a nightmare to override and maintain:
`.vs-sidebar .vs-sidebar-items .vs-sidebar-item a`
Not to mention I have found some **!important** declarations, which is a no no in a framework.

Please take a look at some of your CSS and make it more extendable by lowering specificity as much as possible.

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much I will improve that aspect so that the frame is more stable and easy to customize

**Comment by Jacrys** [comment]
> Not to mention I have found some !important declarations, which is a no no in a framework.

I am not sure that's true, @byrnecode.  Both Bootstrap and Foundation, the latter I see in your portfolio you have used, use !important. 

The important thing (pun intended) is not to use it in place of specificity, but to ensure that utility classes (such as the ones in a framework) do not break if/when a user defines a rule with a higher specifictiy[1](https://css-tricks.com/when-using-important-is-the-right-choice/)

**Comment by byrnecode** [comment]
Hi @brunokunace, @luisDanielRoviraContreras, thanks for the response! I really wanted to help and support this project because I truly love the aesthetics of the components. Too bad I still got my hands full with other projects.. When I got more time, I'll make sure to contribute! Thanks.

**Comment by luisDanielRoviraContreras** [comment]
@byrnecode great I hope you can help us, tieness all the reason and we are going to change the methodology and make it better so that the merco is more usable and customizable with respect to css

Thank you very much and if there is anything else, do not hesitate to advise the idea is to improve and fix the errors

**Comment by luisDanielRoviraContreras** [comment]
The specificity was improved in all the components for a better handling and change of them, almost all the important ones were eliminated (those that were found)

@byrnecode thank you very much for the contribution and contribute to make a change so necessary for the framework
