### ISSUE TITLE
After element disabled, change to disabled color ?

### ISSUE THREAD

**Issue by xiangwan** [lusaxweb/vuesax#310]
No change in the color of the disabled element may make the user feel confused.

**Comment by luisDanielRoviraContreras** [comment]
Could you explain me better, and what components do you mean?

**Comment by Jacrys** [comment]
@xiangwan, this may be related to an existing issue I am working on, #298.

**Comment by xiangwan** [comment]
@luisDanielRoviraContreras sorry about my poor english, @Jacrys is right, this issue is related #298
