### ISSUE TITLE
Custom close function in prompt

### ISSUE THREAD

**Issue by iagocavalcante** [lusaxweb/vuesax#315]
I'd like to custom close action in prompt

![image](https://user-images.githubusercontent.com/5131187/47127946-a1a0cd00-d265-11e8-8917-a778a4ff2c7a.png)

I'm building an application with a wrapper of prompt and I'll want to control the close event. I couldn't find props to control that, so I guess this is an interesting new feature in prompt.

**Comment by luisDanielRoviraContreras** [comment]
I think you mean this? `@close="myFunctionClose"`

**Comment by iagocavalcante** [comment]
Yes

> I think you mean this? `@close="myFunctionClose"`

Another thing I guess is essential in a dialog is a boolean to enable or disable click outside to close

**Comment by brunokunace** [comment]
@iagocavalcante when you make a wrapper with `.sync` atributte, this try to change a prop, (and the props is immutable), but you can make a computed with `get` and `set` to change this.

look a example with you code.

https://codesandbox.io/s/n3zq0l6zqj

**Comment by iagocavalcante** [comment]
I understand this now, in this case, I can call the method inside the computed to manipulate some states. 
But I think this is better to manipulate the event @close or @hide in the vs-prompt to pass the function I desire, what you think?

**Comment by luisDanielRoviraContreras** [comment]
it's a very good idea
