### ISSUE TITLE
Collapse component hides content on reduced width

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#316]
Hi There,

I just found out that in collapse when we open collapse item and then reduce the width of window content gets hidden because of max height(+ overflow:hidden;) given to collapse. It fixes it self after we close that collapse item and reopen it.

Collapse item should adjust height when we reduce width of window.

[Here](https://lusaxweb.github.io/vuesax/components/collapse.html)

Step to create this issue:
-  Go to link
-  Open any collapse item
-  Reduce the width of window

I am using your collapse in my project and lots of things depends on this collapse feature. So, I hope that you will fix this soon.

![capture](https://user-images.githubusercontent.com/31243533/47131943-181de900-d2bf-11e8-9e65-09b9b9d5ea64.PNG)

**Comment by luisDanielRoviraContreras** [comment]
was updated by fixing this problem, thank you very much for the contribution **v3.5.5**
![vuesax-collapse](https://user-images.githubusercontent.com/31676496/47185954-fd6a6500-d2fc-11e8-987f-5d4a5c288fb6.gif)

**Comment by GeorgeGomes** [comment]
My version is 3.11.10 but the same error

![image](https://user-images.githubusercontent.com/3782444/79371045-1b347c80-7f2a-11ea-8988-084cd6868ec4.png)

Collapse is hides contents.
