### ISSUE TITLE
tiny white stripe on buttons

### ISSUE THREAD

**Issue by mobayen** [lusaxweb/vuesax#317]
If reporting a bug, please make sure to provide the following:

- Your OS: Windows
- Node.js version: v8.11.2
- Vuesax version
- Browser version 
 -  - Firefox 62
 -  - chrome 69
 -  - MS Edge 42
 -  - IE 11

I noticed there are white gaps on some of the buttons (see attached images) when I use chrome and edge.
they are perfect on firefox but never try them on IE... many things will be gone :) the whole button disappeared

**Comment by mobayen** [comment]
I forgot to attach  the images!
here they are...

![4](https://user-images.githubusercontent.com/29548601/47167910-2f5fd500-d2c5-11e8-8243-6be507776feb.jpg)
![3](https://user-images.githubusercontent.com/29548601/47167911-2ff86b80-d2c5-11e8-9454-b687f924175b.jpg)
![2](https://user-images.githubusercontent.com/29548601/47167912-2ff86b80-d2c5-11e8-9eba-80fb857b6674.jpg)
![01](https://user-images.githubusercontent.com/29548601/47167913-2ff86b80-d2c5-11e8-95e8-e0b5c99f6a60.jpg)

**Comment by brunokunace** [comment]
@mobayen how to make this?

i try many times but nothing here..

On Chome  69.0.3497.100:
![image](https://user-images.githubusercontent.com/16597320/47170048-78228880-d2db-11e8-9ab8-9a819b91f79c.png)

**Comment by mobayen** [comment]
@brunokunace for example under the "Border" section click on of the buttons, there will be a white gap at the top!
and this will happen if you are in Chrome
for Edge the gap will appear top, bottom, left and right

**Comment by brunokunace** [comment]
@mobayen this?
I dont see anything

![gif](https://user-images.githubusercontent.com/16597320/47188991-d584fc80-d310-11e8-8389-5f9a50c3e869.gif)

**Comment by mobayen** [comment]
Haa, interesting!!!
well, I had that on windows but now on mac, it's gone!

**Comment by brunokunace** [comment]
i am on windows 10, maybe anything with your SO. 

Sure about its not a issue for vuesax? 
if yes,  i can close it. 

Thanks for dedication for explain.

**Comment by Jacrys** [comment]
@mobayen I1. I am upset that you actually made me open Edge :shudders:  😹   

But Il all seriousness... I cannot repro either..

Win 10

Microsoft Edge 42.17134.1.0
FF 64.0b1
Chrome Version 69.0.3497.100

**Comment by mobayen** [comment]
@brunokunace yes, if you don't have the same issue with buttons it might be my OS...!
plus I didn't have that at home on Mac!! so I guess it's a false alarm!!

And @Jacrys so sorry  I feel guilty about that! 😢

**Comment by mobayen** [comment]
@brunokunace @Jacrys 

sorry again 😅
but what about IE11?

some buttons are completely gone on IE11
have you tried that?

![2018-10-19_12-52-52](https://user-images.githubusercontent.com/29548601/47235368-740b6f00-d39e-11e8-8713-d1d046d9b412.jpg)
