### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by brandideamx** [lusaxweb/vuesax#32]
Hi, im getting this error after install vuesax via npm.

Failed to compile.
`./node_modules/vuesax/dist/fonts/MaterialIcons-Regular.ttf
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/css-loader!./node_modules/vuesax/dist/vuesax.css 7:13584-13628
 @ ./node_modules/vuesax/dist/vuesax.css
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js`

**Comment by brandideamx** [comment]
Thanks for your support.
OS: Mac os High Sierra
Node version: 8.11.1
vuesax version: 3.0.5
Browser: Google Chrome version 66.0.3359.117

**Comment by luisDanielRoviraContreras** [comment]
You can provide a reproduction repository. That eliminates the riddling work and saves us time.
