### ISSUE TITLE
Invisible Items in Reduce Sidebar

### ISSUE THREAD

**Issue by Spharxdevelopment** [lusaxweb/vuesax#323]
Hi, I would like to make a new feature request: 
It's about hiding items from reduced sidebars with closed sidebars. 
They should only be visible when the menu is open. 
Here is an example: 

https://image.prntscr.com/image/VP6duDTEQ4Gp6SQrScC-MA.png

This should only be displayed when the menu is expanded. :)

**Comment by brunokunace** [comment]
the image url receive 404, please reopen with more details
