### ISSUE TITLE
How to add Vuesax components on demand

### ISSUE THREAD

**Issue by duythang** [lusaxweb/vuesax#325]
**Is your feature request related to a problem? Please describe.**
I dont want to add all components of Vuesax in a Vue app. How to add components in Vue app, which i want to use, on demand ?. 

**Describe the solution you'd like**
Vuesax should support

**Comment by luisDanielRoviraContreras** [comment]
You can do it like that 
https://github.com/lusaxweb/vuesax#or-use-individual-components

**Comment by chidonna** [comment]
When doing something like this, how do I set my own theme ???

**Comment by luisDanielRoviraContreras** [comment]
same in the same way since they are global variables https://lusaxweb.github.io/vuesax/theme/
