### ISSUE TITLE
Buttons component is very weird

### ISSUE THREAD

**Issue by periscuelo** [lusaxweb/vuesax#331]
- OS Windows
- Node.js 8.12.0
- Vuesax 3.5.10
- Browser Chrome
- Which package manager did you use for the install? npm Vue CLI

The icons it's not centralized when i use vs-radius. When i remove the class below it's back to normal
`
.includeIconOnly {
    width: 38px!important;
    height: 38px!important;
}`

Maybe it has to do with using 'pixels' and 'important'. Should not be use 'rem' to be responsive and decrease along with the browser?

And when we click in the button the color be over the icon... You can see it in your own docs.

**Comment by periscuelo** [comment]
In version 3.5.12 the icon in button not appear anymore

**Comment by luisDanielRoviraContreras** [comment]
@periscuelo The acronyms were deleted in the properties vs for example of vs-icon now it is only icon please try to see

**Comment by periscuelo** [comment]
In version 3.5.7 The icons it's not centralized anymore. But yes, appear in 3.5.12 when i adjust the acronyms.
Thanks

**Comment by luisDanielRoviraContreras** [comment]
Could you pass me an image of the error?

**Comment by periscuelo** [comment]
I made a small project using vuesax. Maybe you can make download and run in localhost with Vue CLI 3 before update the version 3.5.6 and after in 3.5.12 Maybe it can be more pratice to you see if the problem exists or if i made something wrong. Can be?

**Comment by periscuelo** [comment]
[Vue Spotify](https://github.com/periscuelo/vuejs/tree/master/vuespotify)

**Comment by periscuelo** [comment]
I use `rem` and not `pixels` to get the sizes, to work better when its be responsive. That's the cause above.
When i seted material icons font size to 16px, everything works normaly. Thanks.
