### ISSUE TITLE
Loading does not work

### ISSUE THREAD

**Issue by Iopos** [lusaxweb/vuesax#337]
I wrote it in accordance with the example on the document, and the button does not respond.
![Screenshot_Chrome_20181029-214834~2.png](https://i.loli.net/2018/10/29/5bd7106e82906.png)

**Comment by Jacrys** [comment]
Can you provide your imports to eliminate that as a possible issue?

**Comment by brunokunace** [comment]
> I wrote it in accordance with the example on the document, and the button does not respond.
> ![Screenshot_Chrome_20181029-214834~2.png](https://camo.githubusercontent.com/902508214ee33828d5a6a862653be11ab970d889/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31302f32392f356264373130366538323930362e706e67)

Sure to you import css files too? vs-loading dont show if you dont import this.

Docs: https://lusaxweb.github.io/vuesax/development/#install-in-project-via-npm-or-yarn

`import 'vuesax/dist/vuesax.css' //Vuesax styles`

**Comment by brunokunace** [comment]
@Iopos you can send a feedback?
