### ISSUE TITLE
SideBar background width not respect vs-col

### ISSUE THREAD

**Issue by periscuelo** [lusaxweb/vuesax#341]
- Windows
- Node.js 10.14.1
- Vuesax 3.8.0
- Browser Chrome and Firefox @latest
- Which package manager did you use for the install? NPM

The background of SideBar ignores one `vs-row -> vs-col vs-w="2"` for example and uses 100% of space.

**Comment by brunokunace** [comment]
hi @periscuelo, you can send me a image with error? 

or implemented code? 

thanks

**Comment by periscuelo** [comment]
Sure.

https://jsfiddle.net/Ln2vchzq/

**Comment by periscuelo** [comment]
Yes i already do it. But i thinked this was not normal. Thanks.

**Comment by omerkaramanli** [comment]
how did you remove? I mean what is your full code to remove it?
