### ISSUE TITLE
[Vue warn]: Error in render: "TypeError: _vm.$withBase is not a function"

### ISSUE THREAD

**Issue by amka94amka** [lusaxweb/vuesax#346]
hey help me 
[Vue warn]: Error in render: "TypeError: _vm.$withBase is not a function"

**Comment by brunokunace** [comment]
@amka94amka you can call me when you have this warn?
With is more easy to me reproduce and debug.

Thanks for issue it, waiting you answer.

**Comment by brunokunace** [comment]
no response....

**Comment by NoahCardoza** [comment]
I'm also having the same issue when using NuxtJS.
