### ISSUE TITLE
Close Icon don't close Dialog

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#351]
Dialog's close button don't close dialog. However accept and cancle buttons in footer are working.

Extra: Footer button(Accept & cancel) dont have enough space.
Solution: Give Footer `padding: 10px` just like `.vs-dialog-text` so footer looks cleaner. I didn't check how close button works. So no idea.

- Your OS - windows 7
- Node.js version - 8.12.0
- Vuesax version - 3.7.1
- Which package manager did you use for the install? -> npm

**Comment by rbpaul2** [comment]
Fixed this in https://github.com/lusaxweb/vuesax/pull/368 

Waiting for approval
