### ISSUE TITLE
Close Dialog with vs-cancel

### ISSUE THREAD

**Issue by itafras** [lusaxweb/vuesax#353]
- Mac OS Sierra
- Node.js 8.6
- Vuesax 3.7.1
- Browser Google chrome 70.0.3538.77
- npm

USing vs-prompt I can't close it using @vs-close. Clicking on top right cross won't close the dialog

```js
           <vs-prompt
              @vs-cancel="isActive = false"
              @vs-accept="attachBlock"
              @vs-close="isActive = false"
              :vs-active.sync="isActive">
              hello
     </vs-prompt>
```

I observe the same behaviour in the vuesax documentation 
![close-dialog](https://user-images.githubusercontent.com/32681350/48075170-e1aefc00-e1e2-11e8-88f1-7b89399d2649.gif)

**Comment by rbpaul2** [comment]
https://github.com/lusaxweb/vuesax/blob/b596505d263b466e34fdc083fb5753771b0fde98/src/functions/vsDialog/index.vue#L26

Shouldn't this line be `@click="close"` ?
