### ISSUE TITLE
vs-chips v-model doesn't bind to local component data

### ISSUE THREAD

**Issue by itafras** [lusaxweb/vuesax#354]
* OS Sierra
* Node.js 8.6
* Vuesax 3.7.1
* Browser Google chrome 70.0.3538.77
* npm

Using vs-chips I try to bind the input to the local component data. 

```js
 <vs-chips
          style="margin-bottom: 10px;"
          v-model="search" 
          color="blue" 
          placeholder="Search for new chip">
...
data: () => ({
      search: 'Type your search',
```

here `search` won't be modified

<img width="1138" alt="screen shot 2018-11-07 at 13 09 21" src="https://user-images.githubusercontent.com/32681350/48131033-eaf5a280-e28e-11e8-94c3-cf1dc15f85a0.png">

**Comment by brunokunace** [comment]
hi @itafras,  your v-model need to be a array,  make sure it correctly.
