### ISSUE TITLE
error on focus on vs-select

### ISSUE THREAD

**Issue by webafra** [lusaxweb/vuesax#355]
hello .

- Mac Os Mojave
- Node.js version 10.7.0  
- Vuesax version : 3.7.1
- Browser version : Chrome 70.0.3538.77 
- Which package manager did you use for the install? NPM

I getting an error while clicking select, the error is

1 - Uncaught TypeError: _this2.$children[0].focusValue is not a function

In the sample code ( https://jsfiddle.net/vicvillalobos/gvczfyp0/ ) , this error exists.
please check console log after click on selectbox .

![image](https://user-images.githubusercontent.com/8689072/48200298-fa9ae700-e373-11e8-92e5-2341ce0248e4.png)

2 - after change tab , getting this error : 
![image](https://user-images.githubusercontent.com/8689072/48201475-86fad900-e377-11e8-80a2-7ccf5f7cec14.png)

**Comment by webafra** [comment]
@brunokunace : This problem is similar to the other problem, but with the difference that the error is also in the other part.

**Comment by yvescavalcanti** [comment]
@webafra @brunokunace i could not find the other one. The problem was solved? I'm having the same error.
