### ISSUE TITLE
New component: Sidebar

### ISSUE THREAD

**Issue by fergardi** [lusaxweb/vuesax#36]
Just like in https://material.io/guidelines/patterns/navigation-drawer.html

**Comment by luisDanielRoviraContreras** [comment]
same as in #40

**Comment by fergardi** [comment]
Why not use the same model that you use in the docs?

![image](https://user-images.githubusercontent.com/3602272/39766606-fe3fd174-52e4-11e8-9084-da799f76a7ac.png)

That could be a really good start point for a Sidebar component!

**Comment by luisDanielRoviraContreras** [comment]
I think it's a good idea

**Comment by luisDanielRoviraContreras** [comment]
I'm going to do this component 👍

**Comment by luisDanielRoviraContreras** [comment]
The component is already [sidebar](https://lusaxweb.github.io/vuesax/components/sideBar.html) muchas Thanks for the input
