### ISSUE TITLE
Feature request: Prop vs-icon to tabs

### ISSUE THREAD

**Issue by guastallaigor** [lusaxweb/vuesax#360]
**Is your feature request related to a problem? Please describe.**
This feature request is to add a new prop icon inside each `<vs-tab>` component.

**Describe the solution you'd like**
When passed a material-icon string, the icon is displayed in the left of the tab. The color is the same as the tab.

**Describe alternatives you've considered**
No icons if you don't think it's a good idea.

**Additional context**
I have the code already. See the docs updated below:

![image](https://user-images.githubusercontent.com/22016005/48287006-8f721300-e44e-11e8-9dd6-bc1e38f45b67.png)

**Comment by jsinhSolanki** [comment]
I can not see vs-icon prop in vuesax code or on the docs???

**Comment by guastallaigor** [comment]
@jsinhSolanki Hello. The PR for this issue is not merged yet. It's under review. See at #361 .
