### ISSUE TITLE
Popup background changes but close button stays same.

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#365]
https://lusaxweb.github.io/vuesax/components/popup.html#background

here when we changebackground of popup it changes the background color but background of close button stays white. Which should also change accordingly.

**Comment by luisDanielRoviraContreras** [comment]
could you pass me an image to understand you better thanks

**Comment by guastallaigor** [comment]
I think I get what @jsinhSolanki is saying.

Look the table below at the close button/icon:

|Actual|Expected|
|----|----|
|![screenshot from 2018-12-07 18-44-44](https://user-images.githubusercontent.com/22016005/49672356-f389f600-fa51-11e8-9fea-2cda00cfeef2.png)|![screenshot from 2018-12-07 18-54-08](https://user-images.githubusercontent.com/22016005/49672365-fa186d80-fa51-11e8-98dd-a2009a999d53.png)|

I will make a PR for this in a minute.

**Comment by jsinhSolanki** [comment]
Yeah, thats right @guastallaigor Thanks buddy. Great Job!
