### ISSUE TITLE
New component: Card

### ISSUE THREAD

**Issue by fergardi** [lusaxweb/vuesax#37]
Just like in https://material.io/guidelines/components/cards.html

**Comment by luisDanielRoviraContreras** [comment]
same as in #40

**Comment by fergardi** [comment]
Why not use the same model that you use in the docs?

![image](https://user-images.githubusercontent.com/3602272/39766515-c4a85f58-52e4-11e8-97be-1f85fd9e8ef5.png)

That could be a really good start point for a Card component!

**Comment by luisDanielRoviraContreras** [comment]
If I think it's a very good idea

**Comment by fergardi** [comment]
I will work in this new component now, ok?

**Comment by luisDanielRoviraContreras** [comment]
Perfect, I'll assign it to you :+1:

**Comment by fergardi** [comment]
#55

**Comment by luisDanielRoviraContreras** [comment]
@fergardi perfect, thank you very much, you are really contributing to vuesax I am going to review it to upload it 👍

**Comment by luisDanielRoviraContreras** [comment]
@fergardi Ready and the component is in production thank you very much for the contribution you are doing very well

just a detail that I would like you to fix we are using camelCase for the properties and so they are easier to understand then in the examples you add instead of `vsColor` /` vs-color` for a better understanding and thank you very much

**Comment by fergardi** [comment]
I'm glad you like my components.

Could you make a variant (called vsBordered boolean, for example) that makes the card header title looks like your Dialog?

![image](https://user-images.githubusercontent.com/3602272/40040625-46c91dfc-581b-11e8-8e3f-8f9beaef4af4.png)

With the left border and the font color. And the appearing animation as well.

Thanks in advance.

**Comment by thukuwanjiku** [comment]
@luisDanielRoviraContreras What happened to the previous beautiful vs cards? They changed with the last upgrade. I really loved the old ones. Please find a way of having the previous card back, so we can have liberty to choose either.

**Comment by luisDanielRoviraContreras** [comment]
@thukuwanjiku The component was updated in every sense the same in design, there is no possibility of having the previous design

**Comment by thukuwanjiku** [comment]
It's a pity. All the same thanks a lot.
