### ISSUE TITLE
Icon size inside vs-input

### ISSUE THREAD

**Issue by ziltonvasconcelos** [lusaxweb/vuesax#373]
I cannot define icon size when it is inside a vs-input.

**Comment by Pedrazl** [comment]
Maybe this can help you:
.your-input-class >>> .vs-input--icon {
  font-size: 0.8rem;
}

**Comment by ziltonvasconcelos** [comment]
Worked!

Thanks,
Z.
_____

Zilton Vasconcelos

Pesquisador em Saúde Pública
Fundação Oswaldo Cruz - FIOCRUZ
Instituto Fernandes Figueira - IFF
Laboratório de Alta Complexidade - LACIFF
Departamento de Pesquisa Clínica
zilton.vasconcelos@iff.fiocruz.br <zvasconcelos@iff.fiocruz.br>
Av. Rui Barbosa, 716 - Flamengo - Cep: 22250-020 - Rio de Janeiro/RJ -
Brasil
Office: (21)2554-1919
Lab: (21)2554-1967/1968
Celular: (21)99812-7196


Em sex, 14 de dez de 2018 às 10:41, Luis Pedraz <notifications@github.com>
escreveu:
