### ISSUE TITLE
Radio button when used with Electron

### ISSUE THREAD

**Issue by mas0061** [lusaxweb/vuesax#379]
When Vuesax is used with Electron, the following problem comes up.

- The data specified for v-model is not updated.
- If the name attribute is omitted, it will not be a radio button group.

### Environment
- Vuesax
- Vue CLI v3
- [electron-builder](https://nklayman.github.io/vue-cli-plugin-electron-builder/)

- Your OS : macOS Mojave 10.14
- Node.js version : v11.2.0
- Vuesax version : 3.7.1
- Browser version : Electronic rather than browser
- Which package manager did you use for the install? : yarn

### Code
[Same as the example in this document](https://lusaxweb.github.io/vuesax/components/radio.html#default)

**Comment by brunokunace** [comment]
Hi @mas0061, electron use a chromium based browser,  and it dont have all features required of best function of vuesax.  I dont know if you can a great experience using this package for it. 
We can try to accept old/smaller browsers with ours functions. 

Thanks for the disclaimer.

**Comment by mas0061** [comment]
Thank you for your answer.
I also try to solve it.
If I resolve it, I will send a Pull request.

**Comment by mas0061** [comment]
This problem was solved.
In my project, I used Electron's v2, but when I updated to v3, it worked correctly without changing Vuesax.

**Comment by luisDanielRoviraContreras** [comment]
@mas0061 :+1:
