### ISSUE TITLE
New component: Chip

### ISSUE THREAD

**Issue by fergardi** [lusaxweb/vuesax#38]
Just like in https://material.io/guidelines/components/chips.html

**Comment by luisDanielRoviraContreras** [comment]
same as in #40

**Comment by fergardi** [comment]
Why not use the same model that you use in the docs for InputNumber?

![image](https://user-images.githubusercontent.com/3602272/39766697-2bea6184-52e5-11e8-9fa3-234fd6d950d2.png)

That could be a really good start point for a Chip component!

**Comment by luisDanielRoviraContreras** [comment]
@fergardi thank you very much this great but wait a moment that I am migrating almost all the documentation and when I upload it I approve the function to save the work I will upload what I have and I would like to thank you very much for the contribution

**Comment by fergardi** [comment]
#42

**Comment by luisDanielRoviraContreras** [comment]
Ready and the component is ready with some improvements thank you very much already in the documentation
