### ISSUE TITLE
Table component gives 'querySelectorAll' consoloe error

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#382]
Thanks you so much that you fixed table head alignment problem.
But there's another problem which gives __console__ error `TypeError: Cannot read property 'querySelectorAll' of undefined` in table component.

Here's image to checkout.
![tbl](https://user-images.githubusercontent.com/31243533/49065090-f5c6a600-f242-11e8-839d-cdd2c38d9823.PNG)

one more thing state style is not properly implemented. __color get cut__ on sides.
![tblstl](https://user-images.githubusercontent.com/31243533/49065978-a7ff6d00-f245-11e8-906c-927c6763a8d2.PNG)

**Comment by dker92** [comment]
@jsinhSolanki 
I got the same error  "TypeError: Cannot read property 'querySelectorAll' of undefined",
Did you find a solution ?

**Comment by theAlchemist-dev** [comment]
I'm having the same problem.
Trying to load the table data using axios, but can't seem to get past this error...

**Comment by dker92** [comment]
@theAlchemist-dev 
I did some digging and and found the html tag colgroup from VsTable.vue is not showing when I do an inspect ... 
I think if I change this that will work but I would like a better solution

**Comment by richterdennis** [comment]
I have the same problem
![vuesax_table_fail](https://user-images.githubusercontent.com/6861243/49584488-ce1ac080-f95b-11e8-810a-e6a65219d2a5.png)

**Comment by dker92** [comment]
@richterdennis 
Did you find any solution ? Downgrading the package vuesax is not working for me

**Comment by guastallaigor** [comment]
Just made a PR addressing this.

```javascript
let colgroup = this.$refs.colgroup
      let cols = colgroup.querySelectorAll('.col')
      cols.forEach((col, index) => {
        col.setAttribute('width', tdsx[index].widthx)
      });
```

This code was removed because the HTML part that uses this at VsTable.vue component is commented out.

**Comment by ccalvarez** [comment]
> Just made a PR addressing this.
> 
> ```js
> let colgroup = this.$refs.colgroup
>       let cols = colgroup.querySelectorAll('.col')
>       cols.forEach((col, index) => {
>         col.setAttribute('width', tdsx[index].widthx)
>       });
> ```
> 
> In my PR, this code is removed because the HTML that uses this at `VsTable.vue` component is commented out.

Hi.  Was that PR merged?  I'm having the same problem with vuesax@3.8.0
