### ISSUE TITLE
New component: Table

### ISSUE THREAD

**Issue by fergardi** [lusaxweb/vuesax#39]
Just like in https://material.io/guidelines/components/data-tables.html

**Comment by luisDanielRoviraContreras** [comment]
same as in #40

**Comment by fergardi** [comment]
I noticed there is already a started vsTable component. I don't want to mess with your code, so I'll close this and wait for it to be finished.

**Comment by luisDanielRoviraContreras** [comment]
If the component is advanced but it is somewhat complicated because I want to make it have support for editable
