### ISSUE TITLE
vs-avatar with local images

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#391]
When I try to use local image with vs-avtar component it is not showing. However if use same path for `img` tag that image is showing.

`<img src="../../assets/images/logo/logo-80x80.png" alt=""> <!-- works -->`
`<vs-avatar src="../../assets/images/logo/logo-80x80.png" /> <!-- not working -->`

In network tab it gives type: text/html
![img vs-avtar](https://user-images.githubusercontent.com/31243533/49632430-ac810e00-fa1b-11e8-89ae-4ad5ca51be5c.PNG)

gives:
![vs](https://user-images.githubusercontent.com/31243533/49632500-f669f400-fa1b-11e8-81da-41625df2a662.PNG)

- Your OS - windows 7
- Node.js version - 8.12.0
- Vuesax version - 3.8.0
- Browser version - chrome Version 70.0.3538.110
- Which package manager did you use for the install? - npm

**Comment by FelipeFernandesLeandro** [comment]
I don't know why this happen but i found a work around.

```
<template>
  <vs-avatar size="small" :src="localSrc"></vs-avatar>
</template>

<script>
export default {
  data () {
    return {
      localSrc: require('../../assets/images/logo/logo-80x80.png')
    }
  }
}
</script>

<style scoped>
</style>

```

**Comment by guastallaigor** [comment]
I don't think this is a workaround @FelipeFernandesLeandro , this is as expected because webpack doesn't know that it should handle the prop string as a dependency, so your code is correct in my opinion. 

But I think this should be at `<vs-avatar>` and not handled outside. If the mantainers agree, you should make a PR with this.

**Comment by jsinhSolanki** [comment]
I found solution to this.
`<vs-avatar :src="require(`@/assets/images/portrait/small/${contact.img}`)"></vs-avatar>`

However if pass full path
`<vs-avatar :src="require(contact.img)"></vs-avatar>`
this doesn't work. But this is not related to vuesax. I think this is webpack issue.
