### ISSUE TITLE
height of vs-textarea component

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#392]
When we give height to `vs-textarea` component. It applys style to div instead of textarea.

`<vs-textarea counter="120" label="About" :counter-danger.sync="counterDanger" v-model="about" class="h-64" />`
this result in cutted text.
![textarea](https://user-images.githubusercontent.com/31243533/49643805-afd8c180-fa3c-11e8-9d82-ec876f5bb7d1.PNG)

- Your OS-  windows 7
- Node.js version - 8.12.0
- Vuesax version - 3.8.0
- Browser version - chrome Version 70.0.3538.110
- Which package manager did you use for the install? - npm

**Comment by guastallaigor** [comment]
I can fix this by creating two new props `height: String` and `width: String` to let you set the `<div>` and `<textarea>` size.

**Comment by jsinhSolanki** [comment]
thank u so much @guastallaigor
