### ISSUE TITLE
New component: Toolbar

### ISSUE THREAD

**Issue by fergardi** [lusaxweb/vuesax#40]
Just like in https://material.io/guidelines/components/toolbars.html

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much for the contribution to the project right now I am in the process of migrating the documentation from vue normal to vuepress when I finish that I start again to add components and improve the previous ones.

**Comment by fergardi** [comment]
I want to help you with a few components as well.

**Comment by luisDanielRoviraContreras** [comment]
Well I would love clear without any problem, the component you want to help doing first take it on the same issues to not re-work on them

**Comment by luisDanielRoviraContreras** [comment]
#12 Ready, the component is added
