### ISSUE TITLE
Dropdown Dialog box close when tapped/clicked outside the element

### ISSUE THREAD

**Issue by thepepperone** [lusaxweb/vuesax#401]
Hi I'd like to suggest a behavior to the dropdown feature. 
On most examples, the behaviors tend to favor more on hover (mouse clicks/hovers), so that's good. 
But on one hand, as we are into using screen taps (mobile), the custom click event (vs-trigger-event) uses button to open the dialog box works, but every time the user wishes to just close the dialog, they assume to just click anywhere outside that dialog box. 

![image](https://user-images.githubusercontent.com/43367090/49781361-5b3f8a00-fd4d-11e8-8475-95053b3cf810.png)

This can be addressed using a custom JS to close that element when tap events is detected outside. 
But this can be an improvement to the current updates of your great framework. 

Cutting this short, we'd like to see a dropdown dialog behavior that closes when a tap outside is detected the dialog element. Thanks

**Comment by guastallaigor** [comment]
Hello @thepepperone I thought in a way to fix this behavior, but not sure if the code is good enough. 

I will also have to test it on mobile and I can't right now, but I will make a PR to you and the mantainers check the code if it's viable to be accepted. 

Thank you.
