### ISSUE TITLE
Classes don't apply to input element when given to component

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#404]
Hey, I am creating input element which have `border-radius` style but when I apply class attribute to component. 
`<vs-input class="w-full mx-5 rounded-full" placeholder="Search" v-model="search"/>`

input field don't get affected with border-radius.
There's also feature request to give prop if dev want line between icon and text field(optional). Because clean input field with only icon and text looks cleaner than `icon` + `|` pipe

Your OS - windows 7
Node.js version - 8.12.0
Vuesax version - 3.7.1
Which package manager did you use for the install? - npm

**Comment by guastallaigor** [comment]
My thoughts on this _(I'm not a member of the core team, just a contributor)_:

> input field don't get affected with border-radius.

You will have to change the class `vs-input--input`

**Example:**

```css
.vs-input--input {
  border-radius: 50%;
}
```

Not sure if a prop would be good here for `border-radius` property, it doesn't feel right.

> There's also feature request to give prop if dev want line between icon and text field(optional). Because clean input field with only icon and text looks cleaner than icon + | pipe

My english is not the best so I can not understand this. Could you please point me to the issue's feature request or share a image of what you want to change?

Thank you.

**Comment by jsinhSolanki** [comment]
I was saying in input with icon gives line(vertical dash) `|`  between icon and text.
![pipe](https://user-images.githubusercontent.com/31243533/49923315-16e0f500-fed9-11e8-9fd1-b86c29963d6d.PNG)

So, I think there should be prop to ommit that line like in image below.
![no pipe](https://user-images.githubusercontent.com/31243533/49923307-10527d80-fed9-11e8-8b90-02d60a64dda2.PNG)
