### ISSUE TITLE
Vue build not working

### ISSUE THREAD

**Issue by Pedrazl** [lusaxweb/vuesax#405]
Hi, 
I'm experimenting problems trying to compile the project. When I ran `npm run build`, the console throws me that message: 

> We are slimming down vue-cli to optimize the initial installation by removing the `vue build` command.
  Check out Poi (https://github.com/egoist/poi) which offers the same functionality!

Maybe documentation of project contribution is outdated?

Thanks,

**Comment by brunokunace** [comment]
@Pedrazl say me more...
You import vuesax with npm?
Create a project with vue-cli-3 before?
When you import a lib, the scripts in package.json dont change, you use the build for the project created and not to libraries included.

**Comment by Pedrazl** [comment]
Any idea @brunokunace ? What steps should I follow to work in the project and make a PR?

**Comment by luisDanielRoviraContreras** [comment]
I think it may be because you are missing some global library, do you have global Vue Cli? and you can pass the error the console gives you

**Comment by Pedrazl** [comment]
Thanks @luisDanielRoviraContreras,
finally I've had it working. As you say, I have to install the Vue Cli globally: 
`npm install -g @vue/cli`
`npm install -g @vue/cli-service-global`

But still some errors pop on `npm run build`. A reference to 'autoprefixer' is lost. 
I installed it...
`npm i autoprefixer`
...and now everything seems to be ok. 

Shouldn't be the reference to autoprefixer on package.json?

**Comment by luisDanielRoviraContreras** [comment]
Great that good that you already did it, and well I had it added and then I eliminated it! I'll see if I implement it again or completely remove it

Thank you very much for the contribution
