### ISSUE TITLE
Pressing enter + Button in form tag submits form on enter

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#408]
Hey, I am having trouble when I use form + button in my app.
When I press enter after entering data in input field. Form gets submitted.
Which I dont want.
In my example I am using chips to add multiple chips to data property. But when I hit enter key form get submitted and reloads the whole page.

here's js fiddle: [http://jsfiddle.net/jsinh0001/bxcy348a/](url)

**Comment by brunokunace** [comment]
@jsinhSolanki Hi!
this error about html tag <form> inside your code.
For default, <form> take a method get and when you submit a event click inside, the method actived. 

Tip: You dont need form when using vuejs, set the method on @click of you send button

**Comment by Petercopter** [comment]
https://alligator.io/vuejs/vue-form-handling/

You should be able to submit the form using enter

**Comment by 4UForever** [comment]
confirm this error too.
Seems the vuesax has generated every buttton to type 'submit' if we put this code in form tag.
e.g.
`<form @submit.prevent="loggg">
some input elements....
<vs-input class="inputx" placeholder="Placeholder" v-model="value"/>
<vs-button color="primary" type="filled" @click="test">Primary</vs-button>
</form>`
`methods: {
    test() {
      console.log('test click primary');
    }
}`
then if we submit by enter on any input element (not click on the button Primary) then the method "test" has been processed. (console shows "test click primary" without click the button).
This should be FIX., but I don't know why this issue has been closed. I still found this issue.
