### ISSUE TITLE
when checkbox is binded to v-model vuex set property executes two time

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#411]
When I use checkbox with v-model(array) and vuex with get and set property. Get works fine but if I change value of any checkbox(when i click on any checkbox). Set property's function executes two time.
First time it receives value as event and second time array which I want.

code:
```
currentMailLabels: {
	get() {
		return this.$store.getters.getMail(this.openMailId).labels;
	},
	set(value) {
		console.log(value);
		console.log("hi");
		// const payload = { mailId: this.openMailId, value: value }
		// this.$store.dispatch('updateMailLabels', payload)
	}
}
```

```
<vs-dropdown vs-custom-content>

	<feather-icon icon="TagIcon" class="cursor-pointer ml-3"></feather-icon>

	<vs-dropdown-menu style="z-index: 999999999999">

			<vs-dropdown-item v-for="(label, index) in emailTags" :key="index">
				<vs-checkbox @click.stop :vs-value="label.value" v-model="currentMailLabels">{{ label.text }}</vs-checkbox>
			</vs-dropdown-item>
	</vs-dropdown-menu>
</vs-dropdown>
```

what I receive:

![mail](https://user-images.githubusercontent.com/31243533/50212157-56f41c00-03a0-11e9-8066-30d38376f59f.PNG)

Your OS - windows 7
Node.js version - 8.12.0
Vuesax version - 3.7.1
- Which package manager did you use for the install? - npm

**Comment by luisDanielRoviraContreras** [comment]
I could not solve the repetition of the event, but now the event does not return but the array from the first instance

what you can do to solve is to use only the get and the change event in the component to simulate the set

I hope I help you
