### ISSUE TITLE
Closable Alert  animation on first close

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#412]
Hey, in here [https://lusaxweb.github.io/vuesax/components/alert.html#closable](url) on first click of close button. Alert don't get animated(heigth animation). But from first close next time we open and close alert shows perfect transition. But why not first.

**Comment by luisDanielRoviraContreras** [comment]
Ready, the problem is fixed, thanks for the contribution, apologies for the delay
