### ISSUE TITLE
Disable tooltips evaluating expression (dynamic)

### ISSUE THREAD

**Issue by Pedrazl** [lusaxweb/vuesax#413]
**Is your feature request related to a problem? Please describe.**
If you want to disable a tooltip based on a condition, the only way now is to duplicate code. See that case:

` <vs-tooltip :text="layer.description"
                  position="bottom">
        <label for=""
               class="switch-label"> {{ layer.alias }}</label>
      </vs-tooltip>`

If some layers has no "description", I have to surround all in a div and duplicate code to disable the tooltip on that cases:
`<div v-if="layer.description">
      <vs-tooltip :text="layer.description"
                  position="bottom">
        <label for=""
               class="switch-label"> {{ layer.alias }}</label>
      </vs-tooltip>
    </div>
    <label v-else
           for=""
           class="switch-label"> {{ layer.alias }}</label>`
**Describe the solution you'd like**
Tooltip component should have a property to enable / disable tooltip evaluating the condition. Pseudo code:
`<vs-tooltip :text="layer.description" :active="condition">
        <label for=""> {{ layer.alias }}</label>
 </vs-tooltip>`

**Describe alternatives you've considered**

**Additional context**

**Comment by luisDanielRoviraContreras** [comment]
Ready and added the property in the latest version, thank you very much for the contribution

Sorry for the delay
