### ISSUE TITLE
CSS style is not the same as shown in Vuesax Home Page

### ISSUE THREAD

**Issue by ccalvarez** [lusaxweb/vuesax#416]
- OS: macOS High Sierra Version 10.13.6
- Node.js version:  10.14.1
- Vuesax version:  3.8.0
- Browser version:  Google Chrome 71.0.3578.98 (Official Build) (64-bit)
- Which package manager did you use for the install?:  npm

Reproduction repository:  https://github.com/ccalvarez/vuesax-style

Issue:  I have installed Vuesax in my project with `npm install vuesax`.  Then I've added it with:

```
import Vue from 'vue'
import Vuesax from 'vuesax'

import 'vuesax/dist/vuesax.css' //Vuesax styles
Vue.use(Vuesax)
```

Then I have added a list with headers as explained here:  https://lusaxweb.github.io/vuesax/components/list.html#header

But when I run the application, my list doesn't have the same style as the list shown in the components showcase.

My list shows in Times font, while in your home page the list uses OpenSans font:

**My project on localhost:8080:**
![image](https://user-images.githubusercontent.com/2665104/50461891-48c97100-0947-11e9-9a46-6a1e6c23a09b.png)

**Vuesax home page:**

![image](https://user-images.githubusercontent.com/2665104/50461898-58e15080-0947-11e9-8163-0682d8ff6ce4.png)

**Comment by luisDanielRoviraContreras** [comment]
Vuesax has a source in the documents that is shown (Open Sans) but as such the framework is a default source so as not to cause problems in the use, if you want you can simply add the source and it should work

**Comment by tiokouBrice** [comment]
!,,
