### ISSUE TITLE
Collapse Item overflows when type is bordered.

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#417]
I recently found that when collapse type is bordred and when we open an item content gets outside of border as show in below image. + Text is white(another bug).
![coll-overflow](https://user-images.githubusercontent.com/31243533/50536461-e48ef300-0b7a-11e9-8ab5-972f097d22a0.PNG)

**Comment by luisDanielRoviraContreras** [comment]
Ready already fixed in the latest version, thank you very much for the contribution
