### ISSUE TITLE
Dialog cancel button not displayed on IE & Edge

### ISSUE THREAD

**Issue by meast-ev** [lusaxweb/vuesax#419]
Someone know why the cancel button of $vs.dialog is not displayed on internet explorer and edge?

<img width="423" alt="capture d ecran 2018-12-31 a 10 35 39" src="https://user-images.githubusercontent.com/24526688/50557707-048ff500-0ce8-11e9-8bd7-4283817ec58c.png">

I inspected this problem and safari told my this:

<img width="296" alt="capture d ecran 2018-12-31 a 10 38 19" src="https://user-images.githubusercontent.com/24526688/50557738-3903b100-0ce8-11e9-97d1-0cebf90c6f6e.png">

**Comment by luisDanielRoviraContreras** [comment]
I do not have a mac to verify and solve the problem, if you can do a PR on this it would be great

**Comment by meast-ev** [comment]
I can check it for safari but the problem is also exist on internet explorer and edge. Can you check it for this part? 
I guess, if you fix it or those browser, it will be ok for safari
