### ISSUE TITLE
Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by leo0828** [lusaxweb/vuesax#427]
Hello, I used vuexsax for the first time in a new Vue project today. I placed a select component on the home page, but I got this error when I switched routes.
```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```
And when I switched routes on your [official website](https://lusaxweb.github.io/vuesax/components/selects.html#select-update) my chrome got the same error. Is that a bug?
How can I fix it?

- Your OS
macOS 10.12
- Node.js version
v8.11.2
- Vuesax version
3.8.0
- Browser version
Chrome(71.0.3578.98)
- Which package manager did you use for the install?
npm

**Comment by ccalvarez** [comment]
It is a bug, it has been already fixed as you can see in this issue:  https://github.com/lusaxweb/vuesax/issues/345

But the fix has't already being published on npm repository by the mainteiners of the project.

Maybe @lusaxweb could help us, actually I have an application in production with the bug :(

**Comment by Pedrazl** [comment]
Yeah, I have an application in production with the bug too. Hope they release a version with the patch...
