### ISSUE TITLE
New component: Progress

### ISSUE THREAD

**Issue by fergardi** [lusaxweb/vuesax#43]
Just like in https://material.io/develop/web/components/linear-progress/

**Comment by luisDanielRoviraContreras** [comment]
@fergardi When you want to help in a component notify me to assign it and not do it

**Comment by fergardi** [comment]
Can I start with this component?

**Comment by luisDanielRoviraContreras** [comment]
Of course yes

**Comment by fergardi** [comment]
#46

**Comment by luisDanielRoviraContreras** [comment]
@fergardi It is already implemented with some changes, thank you very much for the contribution
