### ISSUE TITLE
Use css-grid instead of flex for grid

### ISSUE THREAD

**Issue by atilkan** [lusaxweb/vuesax#430]
Css-grid should be default choice for grid. It is made by MS and  supported on IE11+.

**Comment by brunokunace** [comment]
we use flex, dont have time to change core for grid (i dont like grid 😄 )

**Comment by atilkan** [comment]
It is not about liking or personal preference. It is about what is best for what. And you are not using the correct one.

**Comment by luisDanielRoviraContreras** [comment]
Let's take it into account for upcoming updates

thank you
