### ISSUE TITLE
[important] vs-upload - Automatic mode with mutliple doesn't send data

### ISSUE THREAD

**Issue by shide1989** [lusaxweb/vuesax#431]
Using the vs-upload component, 
the automatic mode with mutliple doesn't send any file or data :

![capture d ecran 2019-01-11 a 12 10 25](https://user-images.githubusercontent.com/7138331/51030571-27e55a80-159a-11e9-801c-bca324d8c98e.png)
![capture d ecran 2019-01-11 a 12 10 52](https://user-images.githubusercontent.com/7138331/51030572-27e55a80-159a-11e9-8809-c57013421b27.png)

code : 
```
 <vs-upload multiple automatic action="https://{your_url}" @on-success="successUpload" />
```
Environment
- OSX High Sierra 10.13.6
- Node.js version : none used
- Vuesax version: you tell me, i can download version 3.5.7 but vuesax.umd.js from CDN says 2.5.7 ... For my test i used the one from the CDN
- Browser version : Firefox Developer Edition 65.0b9
- Which package manager did you use for the install? none

JSFiddle available here for my test : https://jsfiddle.net/shide1989/e13x4g5u/2/
Also tested with local project

PS: js from CDN says `var core = module.exports = { version: '2.5.7' };` - https://cdn.jsdelivr.net/npm/vuesax/dist/vuesax.umd.js

**Comment by meast-ev** [comment]
Up

**Comment by alxpereira** [comment]
+1 (no file sent during the first automatic POST), however it works on manual.
@luisDanielRoviraContreras

**Comment by luisDanielRoviraContreras** [comment]
@shide1989 @meast-ev @alxpereira Ready already fixed, let me know if it works as it should, thank you very much
