### ISSUE TITLE
Tooltip sticks When Element is destroyed

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#435]
Hey, I am using tooltip in my navbar and I have two layout.
1. With navbar
2. No Navbar

I have button in navbar which navigates to another layout which dont have any navbar.(So, when I click on btn, btn it self and navbar gets destroyed). But that tooltip which I used on button still remain.

i have created simillar demo for you.
[jsfiddle](https://jsfiddle.net/jsinh0001/cqavtm13/)

**Comment by luisDanielRoviraContreras** [comment]
thanks for notifying me I will review the problem and fix it in a next update

**Comment by luisDanielRoviraContreras** [comment]
ready already fixed in the latest version please verify, thank you very much for the contribution

**Comment by jsinhSolanki** [comment]
Hi, @luisDanielRoviraContreras. I cross checked tooltip on jsfiddle it flickers constently. You can see that in above jsfiddle of this issue.

Thanks.

**Comment by Pedrazl** [comment]
I am having problems with the tooltips too. It goes in and out constantly, this issue should be opened again @luisDanielRoviraContreras

**Comment by Pedrazl** [comment]
I tried to fix this bug, but no luck. I has something to do with the way vsTooltip set {'after-none': noneAfter} class. For some reason the div containing the tooltip, automatically has a "display:none" on his style, thats why we can only see it for a millisecond. 
Hope this helps to get this fixed.

**Comment by plasebo** [comment]
I've used the router js file to remove all tooltip on either the afterEach or befooreEach event. The afterEach event is better. Example in the router.js file:

`router.afterEach(() => {
  // Remove initial loading
  const appLoading = document.getElementById('loading-bg')
    if (appLoading) {
        appLoading.style.display = "none";
    }
  const Stickedtooltips =  document.querySelectorAll(".vs-tooltip")
    for (const tooltip of Stickedtooltips) {
      tooltip.remove();
    }
})`

**Comment by Tofandel** [comment]
Now you can see the tooltip doesn't even show on the fiddle... Great testing before deployment..

I made a PR fixing this issue by checking the content of the default slot, if there is no content the tooltip is deactivated correctly
