### ISSUE TITLE
Button don't support Object Path feature

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#438]
hi, I was testing my app and I found that button with object path don't work.

`<vs-button color="primary" type="filled" :href="{url: 'https://lusaxweb.github.io/vuesax/'}">Object Path</vs-button>`

Above code is not working. Not even on docs site.
But next button which also have href as object path works fine.(which is used to demonstrate target)
`<vs-button color="primary" type="filled" target :href="{url: 'https://lusaxweb.github.io/vuesax/'}">Open Current Tab</vs-button>`

However I later checked your src code for docs and I found that somone has written plain href `href='url'` in button instead of `:href='{}'` which is shown as object path in docs.

**So my point is:**
1. Object Path is not supported
2. Code for last button need to be updated

Thank you

**Comment by luisDanielRoviraContreras** [comment]
Ready the problem is solved and now it should work as expected, thank you very much for the contribution
