### ISSUE TITLE
Dropdown component gives error when leaving page

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#439]
Hey, in latest update we have new error in console when we left page with dropdown component.

This also happens in docs so you can check right now.

![capture](https://user-images.githubusercontent.com/31243533/51422598-5507bd80-1bd7-11e9-93a8-d73518a76d81.PNG)

**Comment by luisDanielRoviraContreras** [comment]
Ready, it's fixed, thank you very much for the contribution
