### ISSUE TITLE
Filled button and Border button size

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#444]
hi, I have found little UI issue that when we place `filled` button and `border` button side by side.
![button](https://user-images.githubusercontent.com/31243533/51823050-28a11f00-2304-11e9-9118-f379acd4de1c.PNG)

`border` button look large because of it's border whereas `filled` button dont have any border so it's looking smaller in size.

Fix:
apply border to filled button(other buttons also e.g. gradient)

**Comment by luisDanielRoviraContreras** [comment]
What browser are you using, because in chrome it works perfect and they all have the same high

**Comment by jsinhSolanki** [comment]
Ok. Vuesax buttons are perfect. I tested with jsfiddle.

Maybe this have to do with my css.
Closing this.
