### ISSUE TITLE
All locations of the uploader should support drag and drop

### ISSUE THREAD

**Issue by CheyenneForbes** [lusaxweb/vuesax#445]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I forget not all parts of the uploader supports drag and drop and the file I drag gets opened instead

**Describe the solution you'd like**
I'd like for the area where the added files thumbnails are to support drag and drop, I want when I drag and drop a file there its added and not opened

**Comment by luisDanielRoviraContreras** [comment]
I do not understand exactly what you mean and what component, if it is the upload works properly when dragging an image

**Comment by CheyenneForbes** [comment]
For convenience and user experience, the area where the thumbnails are displayed should also accept "drop" just as the area where it says "Click or drag files here"

![image](https://user-images.githubusercontent.com/8251976/52684440-441b4500-2f14-11e9-82e9-181e4c660a80.png)

it would even be better if it...

![ertgygterh](https://user-images.githubusercontent.com/8251976/52685235-0835af00-2f17-11e9-9a28-e455b94d4cc2.jpg)

**Comment by CheyenneForbes** [comment]
Also, when when the file limit is reached the upload area should be hidden until one or more items get removed

In the example below where the file limit is set to 1, "click here to upload photo" should be hidden until the file is remove (by clicking the X) instead of being disabled.

![image](https://user-images.githubusercontent.com/8251976/52934039-4ec64780-3323-11e9-8f6d-e2697c713875.png)

**Comment by CheyenneForbes** [comment]
From a UX/UI perspective, these tips increase visual appeal

**Comment by luisDanielRoviraContreras** [comment]
was updated and added many of the features, thank you very much for the contribution and help in the ux and ui

We did it similar to what you suggested, very good idea
![Screenshot_1](https://user-images.githubusercontent.com/31676496/54872705-d11cae00-4d9e-11e9-8eb3-43cb5ba3b65b.jpg)
