### ISSUE TITLE
Collapse > Accordion open first element/parent

### ISSUE THREAD

**Issue by thepepperone** [lusaxweb/vuesax#449]
**Is your feature request related to a problem? Please describe.**
I have used Vuesax in most of my projects and I must say, it's really good.
The reason I'm writing this one is to have a feature request on Collapse > Accordion

Is it possible if we can add a pre-open/open state of collapse/accordion on first/specified item or parent item. 

Please let me know what you think.

Thanks!

**Comment by luisDanielRoviraContreras** [comment]
Ready and a new property is added for the items in the components

the property is (open)

It would be something like this

```
<vs-collapse>
     <vs-collapse-item open > // <-----
       <div slot="header">
         Collapse item
       </div>
       Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rhoncus eros tortor, non fringilla lectus cursus et. Fusce vel nisi ante. Aliquam sit amet lectus pharetra, luctus mi sed, aliquet felis. Mauris a tortor viverra, ornare tellus in, consectetur leo.
        <br><br>
        Etiam nec nunc nec nisl luctus tincidunt efficitur vitae elit. Vestibulum iaculis nibh commodo neque ultrices lobortis. Cras magna massa, pretium vitae mattis varius, pharetra nec massa. Aliquam ac ex enim. Quisque consequat dui libero, vel blandit lorem porttitor sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam sed lobortis nisl, quis eleifend metus.
     </vs-collapse-item>
</vs-collapse>
```

Thank you very much for the contribution

**Comment by thepepperone** [comment]
Thank you so much. I appreciate it. 👍
