### ISSUE TITLE
cannot paginate with search results

### ISSUE THREAD

**Issue by trangianhuan** [lusaxweb/vuesax#451]
I use <vs-table search pagination :data="users">.
 i have 200 record, 5record / 1page.
first its show OK.. 40page
i start search.. when finish search (100 record return) => All data is displayed in one page.
I wish it were paginated

----------------------------------
- OS: Ubuntu
- Node.js version : 11.6.0
- Vuesax version : "vuesax": "^3.8.16"
- Browser version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- use npm

**Comment by luisDanielRoviraContreras** [comment]
If you can do an example to fix the error, it would be easier

**Comment by luisDanielRoviraContreras** [comment]
Ready and the functionality of search with page is added please check the latest version

Thank you very much for the contribution
