### ISSUE TITLE
File Globbing

### ISSUE THREAD

**Issue by atilkan** [lusaxweb/vuesax#452]
Just a question. 
Why not using file globing in this file? Unlike Sass, Stylus support it. I wonder if there is any particular reason.
https://github.com/lusaxweb/vuesax/blob/9bfe8d915a0b636aacfc0286174554658138312b/src/style/components.styl#L2

it could be just like this and it would not require to update anymore?
```
@import './components/**
```

Actually, if you put this line to vuesax.styl then **components.styl** file would be redundant. Less file to worry.

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much the truth happened to us, I did exactly what you say and it worked perfect

Thanks for the input
