### ISSUE TITLE
Switch -> Array Value's switch toggles all at once in firefox

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#466]
When we use [array values](https://lusaxweb.github.io/vuesax/components/switch.html#array-value) and if I open page in firefox. it toggles all swtiches.
Tested with: Firefox 65.0.1 (64-bit)

As you can see in below image from vuesax docs:
![temp](https://user-images.githubusercontent.com/31243533/52781306-3ed40c80-3072-11e9-8049-9010d2ed0526.PNG)

**Comment by luisDanielRoviraContreras** [comment]
The error has been fixed in the latest Vuesax version. Thanks for the contribution.  vuesax@3.8.34^
