### ISSUE TITLE
Dialog components last example gives console error

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#467]
hi, In your last example of dialog component when we open dialog of `run prompt inputs`, it gives console error of alert.
![ff-dialog](https://user-images.githubusercontent.com/31243533/52857179-67303980-314c-11e9-96b6-912713ffb3e2.PNG)

**Comment by luisDanielRoviraContreras** [comment]
The error has been fixed in the latest Vuesax version. Thanks for the contribution.
