### ISSUE TITLE
How to set rowspan for table

### ISSUE THREAD

**Issue by mobility2015** [lusaxweb/vuesax#468]
Dear
How can I set the rowspan to vs-td element?
I want the result as follows:
<html>
<body>
<table width="100%" border="1">
  <tr>
    <th>Month</th>
    <th>Savings</th>
  </tr>
  <tr>
    <td>January</td>
    <td rowspan="2">test</td>
  </tr>
  <tr>
    <td>February</td>
  </tr>
</table>
</body>
</html>

please help urgently, thank you very much

**Comment by brunokunace** [comment]
you can't use rolspan, the vs-td its a component and dont have this sintax, maybe on future

**Comment by luisDanielRoviraContreras** [comment]
The table component has already been changed and now it has the support for rowspan

Thank you very much for the contribution

```
<vs-table :data="users">
      <template slot="header">
        <h3>
          Users
        </h3>
      </template>
      <template slot="thead">
        <vs-th>
          Email
        </vs-th>
        <vs-th>
          Name
        </vs-th>
        <vs-th>
          Website
        </vs-th>
        <vs-th>
          Nro
        </vs-th>
      </template>

      <template slot-scope="{data}">
        <vs-tr :key="indextr" v-for="(tr, indextr) in data" >
          <vs-td :data="data[indextr].email">
            {{data[indextr].email}}
          </vs-td>

          <vs-td :data="data[indextr].username">
            {{data[indextr].name}}
          </vs-td>

          <vs-td :data="data[indextr].website">
            {{data[indextr].website}}
          </vs-td>

          <vs-td v-if="indextr == 1" rowspan="2" :data="data[indextr].id"> // <-----
            {{data[indextr].id}}
          </vs-td>
        </vs-tr>
      </template>
    </vs-table>
```

**Comment by mobility2015** [comment]
Ok, thank you very much.

**Comment by parth0025** [comment]
I have the same question but only change the value of colspan. When you inspect the element table in the browser at that time table has default colspan "2" but I can't able to change it. Please help me
