### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by pearofducks** [lusaxweb/vuesax#47]
There are some really nice UI ideas here, but quite a few UX misses - especially when one considers accessibility.

Just thought I'd list some I found quickly looking at components:

- Almost no components have a `focus` state
- Button fonts are too small/light
- Select has no keyboard navigability
- Slider doesn't implement/hide an `input`
- Hardly any `aria` annotations on any elements

[Vuetify](https://github.com/vuetifyjs/vuetify/) does a pretty good job of accessibility, so you could reference some of their implementations for possible improvements.

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much for the contribution friend if you want you can help in any of these problems we would love

we are going to put enfacis in the creation and improvement of components

**Comment by luisDanielRoviraContreras** [comment]
Would you like to make one on the list to assign it to you?

**Comment by pearofducks** [comment]
@luisDanielRoviraContreras - unfortunately I don't have time to contribute to this right now. But your labels are dead-on, and someone should be able to help with this who wants to help contribute even if they aren't as experienced!

**Comment by tomagladiator** [comment]
A quick win should be to find all &:hover and add &:focus, on top.

**Comment by luisDanielRoviraContreras** [comment]
You are already fixing and improving all the components in this aspect with their respective $listeners and $attrs thanks

**Comment by kumaraksi** [comment]
Hi team, what is the current status of this issue. 
If it is still to be solved, I can take this up. I would be really happy to contribute to this project.

**Comment by luisDanielRoviraContreras** [comment]
Well already working on each of the components to solve the accessibility and support ssr for now the components are ready in that aspect:

- bottom
- select
- check box
- radio
- switch
- inputs (in process)

If you want to contribute the gia regarding accessibility and support, these can already be improved, thanks for the contribution

**Comment by luisDanielRoviraContreras** [comment]
All the components were updated and now have total accessibility, thank you very much
