### ISSUE TITLE
theme colors support for Navbar color 

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#471]
**Is your feature request related to a problem? Please describe.**
Hi, in my app I have property from which navbar's color is changed. I want to use primary and success as my navbar color instead of hardcoded hax value how can I do that.

**Describe the solution you'd like**
Navbar color should also support theme colors like other components.

**Describe alternatives you've considered**
There's temporary I hard coded my color which is not dynamic and not good.

**Comment by luisDanielRoviraContreras** [comment]
In the last update the support for the main colors was added

Thank you very much for the contribution
![Screenshot_2](https://user-images.githubusercontent.com/31676496/54861530-d88d7a00-4d00-11e9-9537-2adaa0e8eb4e.jpg)
