### ISSUE TITLE
Individual component import with individual CSS

### ISSUE THREAD

**Issue by atilkan** [lusaxweb/vuesax#472]
Currently individual component import supported but not for CSS. We have to import all CSS which is heavy and not ideal.

**Comment by atilkan** [comment]
It can be actually done with little setup.

**Comment by luisDanielRoviraContreras** [comment]
@atilkan If you want you can help in this

**Comment by atilkan** [comment]
I don't have time, sorry.

**Comment by ACVis** [comment]
@atilkan Can you outline how you would solve this issue if you _did_ have the time? This is something that may be worth it for me to tackle.

**Comment by atilkan** [comment]
@ACVis By separating Stylus files each by component. They are copied to dist folder at build at the moment. To be able do this, project have to use stylus. And this is a problem if the project uses other preprocessor. To support all cases element-ui approach can be used.
