### ISSUE TITLE
Table collapsed data should open when we click on row instead of arrow.

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#473]
Hi, I would like report UX issue of table with collapsed data feature.

Right now in vuesax if we want to open collpased data then I have to click on arrow on right but UX wise that collapsed data should open if I click anywhere in that table row.

https://lusaxweb.github.io/vuesax/components/table.html#expandable-data

**Comment by luisDanielRoviraContreras** [comment]
The functionality was added in the latest version

**Comment by piotrm73** [comment]
it should be possible to choose, because when you want to use inside vs-td custom component to edit inline, there is a confllict with expandable slot
TypeError: Cannot read property 'classList' of null
    at VueComponent.clicktd (vuesax.common.js?fb9a:10384)

**Comment by plasebo** [comment]
I can no more combine select checkbox and expanded table now. On click on the row, expanded table does not appear, instead the checkbox is checked. Please provide a fix to permit both to be used at the same time.

**Comment by clopezpro** [comment]
En el ejemplo al hacer click, el area expandible no muestra nada
