### ISSUE TITLE
vs-input with placeholder doesn't support Paste

### ISSUE THREAD

**Issue by ccalvarez** [lusaxweb/vuesax#486]
When a vs-input has the `placeholder` attribute, it doesn't show the Paste option in the contextual menu, neither in the desktop or mobile browsers.

**Comment by brunokunace** [comment]
i check this in docs, but dont have any issue, please if continues, bring here more details

**Comment by luisDanielRoviraContreras** [comment]
Fixed and now is the option to paste

Thank you very much for the contribution
