### ISSUE TITLE
Dialog component with alert gives console error

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#487]
When we use alert component to display validation with dialog component. Alert component throws error in console.

This can be found in demo of `vs-dialog` component's last demo.

![d](https://user-images.githubusercontent.com/31243533/53389109-01e21100-39b4-11e9-9a9f-4ea2892d72cf.PNG)
https://lusaxweb.github.io/vuesax/components/dialog.html#prompt

**Comment by luisDanielRoviraContreras** [comment]
I already repaired this error, thank you very much.
