### ISSUE TITLE
user get successful upload notification when clicked on upload without uploading any file.

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#488]
Why upload component gives, successful upload notifications even if I don't upload anything and hit upload button.
![s](https://user-images.githubusercontent.com/31243533/53389864-14aa1500-39b7-11e9-99ba-8bcff70677cd.png)

**Comment by brunokunace** [comment]
with's because an example, the api response success to me, you need to make a method ou resolver to use on you project.

**Comment by luisDanielRoviraContreras** [comment]
you added disabled to the component if you do not have files to upload
