### ISSUE TITLE
Awkward First Column Spacing on Table

### ISSUE THREAD

**Issue by ACVis** [lusaxweb/vuesax#489]
- OS: Windows 10
- Vuesax version: 3.8.20
- Browser version: Chrome
- Which package manager: npm

In the examples on the [Vuesax website](https://lusaxweb.github.io/vuesax/components/table.html#default), the table columns seem to be spaced in an even way, sharing space like Flex items would. But when I use this component, it always makes the first column take up all the space possible. This creates an awkward and hard to read table, especially if the first table column is typically small data. After inspecting table headers with Chrome devtools, it looks like if I disable `width: 100%` in the `.col` class, then the columns space evenly. 

Am I doing something wrong, or is this a bug?

Example
```javascript          

<div class="FCol">
    <vs-table max-items="15" :data="Upc.variations" stripe>
        <template slot="thead">
            <vs-th sort-key="sku">Sku</vs-th>
            <vs-th sort-key="size">Size</vs-th>
            <vs-th sort-key="price">Price</vs-th>
            <vs-th sort-key="weight">Weight</vs-th>
            <vs-th sort-key="onHand" class="Text--nowrap" >On Hand</vs-th>
            <vs-th sort-key="allocated"
                >Allocated</vs-th
            >
            <vs-th sort-key="sold">Sold</vs-th>
            <vs-th class="Text--nowrap" sort-key="">On Order</vs-th>
        </template>
        <template slot-scope="{ data }">
            <vs-tr
                v-for="(current, index) in data"
                :key="index"
            >
                <vs-td :data="data[index].sku">
                    <span class="Text--nowrap">{{ current.sku }}</span>
                </vs-td>
                <vs-td :data="data[index].size">
                    <span class="Text--nowrap">{{
                        current.size
                    }}</span>
                </vs-td>
                <vs-td :data="data[index].price">
                    <span class="Text--nowrap">{{
                        current.price
                    }}</span>
                </vs-td>
                <vs-td :data="data[index].weight">
                    <span>{{
                        current.weight
                    }}</span>
                </vs-td>
                <vs-td :data="data[index].onHand">
                    <span>{{
                        current.onHand
                    }}</span>
                </vs-td>
                <vs-td :data="data[index].allocated">
                    <span>{{
                        current.allocated
                    }}</span>
                </vs-td>
                <vs-td :data="data[index].sold">
                    <span>{{
                        current.sold
                    }}</span>
                </vs-td>
                <vs-td :data="data[index].onOrder">
                    <span>{{
                        current.onOrder
                    }}</span>
                </vs-td>
            </vs-tr>
        </template>
    </vs-table>
</div>
```
This code and similar code produces this:
![screenshot-localhost-50187-2019 02 26-13-49-24](https://user-images.githubusercontent.com/17129355/53438198-6198e600-39cd-11e9-9720-31bc7a53e22d.png)

Notice how the column for Sku is huge.

**Comment by AndyChuang1** [comment]
I have same issue!!

**Comment by luisDanielRoviraContreras** [comment]
the problem should be resolved now

please let me know if you continue with the problem and if you can have an example to make it easier to solve

**Comment by marcschneider123** [comment]
Having the same issue with v3.8.59.

**Comment by FearHeim** [comment]
Having the same issue with v4.0.1

**Comment by stephridnell** [comment]
Not sure if this will help anyone else but I get weird col width issues when mounting the vs-table component before the table data loads. I just used a v-if to display the component only once the data exists and I get much more even cols.

**Comment by felexkemboi** [comment]
Thank you @stephridnell , this trick worked very well for me.
