### ISSUE TITLE
tooltip don't work

### ISSUE THREAD

**Issue by stpnov** [lusaxweb/vuesax#490]
tooltip don't work
v3.8.24

[JSFiddle](https://jsfiddle.net/yv12nrbm/2/)

**Comment by thepepperone** [comment]
I'm also having this issue. 

vue@2.5.22
vuesax@3.8.24

It's like flickering everytime I hover to any object.

**Comment by javierrdzm** [comment]
Same problem.
Any update on this?

vue@2.6.8
vuesax@3.8.24

**Comment by ashleymoogle** [comment]
Same issue

Vue@2.6.7
Vuesax@3.8.24

**Comment by ashleymoogle** [comment]
So I copied the source code of vsTooltip.vue into a new component, linted it and replaced all warnings and errors like using `==` instead of `===` and it just... works?
Maybe its due to webpack having trouble transpiling `==` ?

**Comment by luisDanielRoviraContreras** [comment]
We change the component with the suggestions and some details should work as expected, please notify if there is any problem

**Comment by PaulKangLI** [comment]
@luisDanielRoviraContreras 
vue@2.6.10
vuesax@3.8.59

the tooltip still flicks every time when I hover to any object.

**Comment by jsinhSolanki** [comment]
Still not working.

**Comment by luisDanielRoviraContreras** [comment]
it works for me, please can do an example or a gif to see the problem better

**Comment by jsinhSolanki** [comment]
You can check here 
https://jsfiddle.net/jsinh0001/cqavtm13/

**Comment by lk77** [comment]
Hello,

same issue here, tooltip is flashing half a second, and disapear.

**Comment by Pedrazl** [comment]
Still not working on 3.8.61...

**Comment by kamaladenalhomsi** [comment]
Same Issue for,
Still waiting for a fix

**Comment by ashleymoogle** [comment]
On the component vsTooltip.vue, if you remove the updated() hook it works
```js
updated () {
   let nodes = this.$refs.convstooltip.childNodes.length
   if (nodes === 1) {
     // this.activeTooltip = false  //Comment this line
   }
},
```
And it works, that's how i fixed it anyway

**Comment by pedropcruz** [comment]
Hello,

I'm currently using vuesax on our project. I'm trying to implement vuesax components, and I have a question

Why you dont export the components for using? Because this is not a good solution to change on node_modules/vuesax. Anyone have more solution to this?

Many thanks

**Comment by liudonghua123** [comment]
> On the component vsTooltip.vue, if you remove the updated() hook it works
> 
> ```js
> updated () {
>    let nodes = this.$refs.convstooltip.childNodes.length
>    if (nodes === 1) {
>      // this.activeTooltip = false  //Comment this line
>    }
> },
> ```
> 
> And it works, that's how i fixed it anyway

I tried your suggestions, it worked. Thanks!

**Comment by mrhammadasif** [comment]
I have also discovered that **tooltip** only works if it contains two child nodes.

Following Snippet works:

```
<vs-tooltip>
    <vs-button>Buttom</vs-button>
    <span>&nbsp;</span>
</vs-tooltip>
```

**Comment by rannmann** [comment]
The DOM does update with only one child node, but it looks like it's set to `display: none;` until you add a second node.

Tested in `3.11.13`

**Comment by Tofandel** [comment]
Could we just remove this updated hook?... It serves no purpose except to annoy us..

In the meantime just wrap components within html nodes
```
<vs-tooltip>
    <span><vs-button>Buttom</vs-button></span>
</vs-tooltip>
```
