### ISSUE TITLE
VsInput with VeeValidate not working on first input

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#492]
`vs-input` with `veeValidate` not working on first time.
If I use 
```
<vs-input v-validate="'alpha'" label="Only alphabetic characters" name="alpha" v-model="alpha"  />
<span class="text-danger">{{ errors.first('alpha') }}</span>
```
when I first type other character than alpha error want show up. But if I remove that character and retype that same character error shows up....:disappointed_relieved: 

However if I use HTML5 input
```
<input v-validate="'alpha'" name="alpha" v-model="alpha"  />
<span class="text-danger">{{ errors.first('alpha') }}</span>
```
This pure HTML5 input works fine!

Why???

**Comment by luisDanielRoviraContreras** [comment]
Is there any other framework that works for you? Pass it to see how they handle this problem because when adding the property inheritAttr: false and not being a direct input the directive does not work
