### ISSUE TITLE
Responsive Column Offset 

### ISSUE THREAD

**Issue by markhermano** [lusaxweb/vuesax#493]
Can we have a responsive setting of column offset?
It would be nice if we can set specific offset based on the device's size.
I'm not able to see any example in the documentation so it seems it is not yet added.

**Comment by jsinhSolanki** [comment]
Besides component framwork you will also need CSS framework.(just like most people).
I don't know about when vuesax will implement this.
So, if you are going to use css framework, why dont you try tailwind css?? Their's grid is awesome. Check that out.[link](https://tailwindcss.com/docs/examples/grids/)

**Comment by daviuz** [comment]
Cool! That's a good idea.
But yeah hopefully in the future it will be implemented with the other necessary features as well so we can avoid having more dependencies.

**Comment by luisDanielRoviraContreras** [comment]
In next updates we will take this into account, thank you very much

**Comment by juanbrujo** [comment]
I can make this a PR if there's interest. Just reply and I'll submit it, I'm working on right now but for my proyect
