### ISSUE TITLE
vs-checkbox can't click when adding v-model

### ISSUE THREAD

**Issue by LaughingCoy** [lusaxweb/vuesax#496]
vs-checkbox can't click when adding v-model

**Comment by jsinhSolanki** [comment]
I think this is the problem with incompatibility of Vuesax framework with the latest vue release. Try downgrading vue to 2.5.19

**Comment by LaughingCoy** [comment]
@jsinhSolanki thanks for the suggestion :D

**Comment by LaughingCoy** [comment]
@jsinhSolanki does vs-checkbox has an event? like @change?
