### ISSUE TITLE
Vs-select-item do not show properly in vs-popup

### ISSUE THREAD

**Issue by yqgit** [lusaxweb/vuesax#500]
I'm still experiencing the z-index issue as in [#207](https://github.com/lusaxweb/vuesax/issues/207) with version 3.8.24. The select items show up under the popup even when copy/pasting the example code. Am I missing something?

**Comment by brunokunace** [comment]
working fine here, you can make a jsFiddle with a example @yqgit ?

**Comment by renjurajwm** [comment]
I am also facing the same issue in vs-popup, I am using "vuesax": "^3.8.20"
@brunokunace which version are you using.

**Comment by luisDanielRoviraContreras** [comment]
I already fixed this error

Thank you very much for the contribution
