### ISSUE TITLE
vs-pagination with programmatic increment of current page not working

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#503]
Hey,

If I use button and give increment to var, provided to `vs-pagination` component, `vs-pagination` does not increase that value in component.

I looked into the code of `vs-pagination` component, it is because of value is not in sync with provided value.(Vuesax used `mounted` hook to accept value). So when change that value using outside button, it doesn't effect in pagination.

```
<vs-pagination :color="colorx" :total="20" v-model="currentx"></vs-pagination>
<vs-button @click="currentx++">{{ currentx }}</vs-button>
````

Try clicking in button. The value will increase but it is not in sync with pagination component.(due to mounted hook)

**Comment by danyakov** [comment]
Hi. I found next solution. Forced update of vs-pagination component with help of :key.
<vs-pagination :color="colorx" :total="20" v-model="currentx" :key=keyx></vs-pagination>
keyx++ in some action. It will re-render component and use latest currentx value.
