### ISSUE TITLE
Sidebar appears for a fraction and closes automatically

### ISSUE THREAD

**Issue by manujk** [lusaxweb/vuesax#505]
OS: Windows 10
Node : v8.12.0
Vuesax: 3.8.29
Browser: Chrome 72.0.3626.121 (Official Build) (64-bit)
Package manager: npm

Hello Lusaxweb team,
the sidebar is having some issue, it shows for a fraction and then disappears,
I can see the same problem on https://lusaxweb.github.io/vuesax/components/sideBar.html#default when I click on open sidebar

Thanks

![vuesax](https://user-images.githubusercontent.com/15279738/54498077-ef188780-4934-11e9-9f56-f4a41a0eb1c2.gif)

**Comment by manujk** [comment]
Update: It works with vue version  **2.5.2** but not working with vue version **_2.6.9_**

**Comment by RamsesMartinez** [comment]
It works actually on the website, is this issues resolved or returned to an old version of the page?

**Comment by luisDanielRoviraContreras** [comment]
it was updated and the problem was fixed, thank you very much for the contribution and advise
