### ISSUE TITLE
vs-select add clear button

### ISSUE THREAD

**Issue by LaughingCoy** [lusaxweb/vuesax#506]
![84op4](https://user-images.githubusercontent.com/44988408/54504803-248e9680-4970-11e9-86e3-0ca749c7f4cc.png)

**Comment by luisDanielRoviraContreras** [comment]
The functionality was added in the latest version

Thank you very much for the contribution
![Screenshot_3](https://user-images.githubusercontent.com/31676496/55203679-9d78c400-51a2-11e9-902a-992c52ab03a7.jpg)

**Comment by LaughingCoy** [comment]
thank you for response 👍
