### ISSUE TITLE
Little UI Modification on the Home Page

### ISSUE THREAD

**Issue by eyedeceiver03** [lusaxweb/vuesax#51]
So, I saw that the feature section is looking not right on mobile devices. So instead of the img-feature's width going 0 on mobile devices, i suggest that it must be on [top or bottom?] of the text-feature and center the content. The graphics are nice so we mustn't hide it.

[UI Plan](https://user-images.githubusercontent.com/17470909/39963408-fea6a21c-569c-11e8-84f5-c7895c2aeb6e.jpg)

I would be glad if i can help with this little modification 😄

**Comment by luisDanielRoviraContreras** [comment]
It is clear that if you can help in this, the responsive is still in process I have not put in that why so many bugs

**Comment by eyedeceiver03** [comment]
[Updated version of the website.](https://user-images.githubusercontent.com/17470909/39965122-f6d12f7a-56c5-11e8-9ee0-493859194ac5.png) 😃

**Comment by luisDanielRoviraContreras** [comment]
@eyedeceiver03 Ready is already in production thank you very much for the contribution

https://lusaxweb.github.io/vuesax/
