### ISSUE TITLE
checkbox  Array Values don't work

### ISSUE THREAD

**Issue by webafra** [lusaxweb/vuesax#510]
- Your OS : MacOS Mojave
- Node.js version : 10.15.0
- Vuesax version: ^3.8.31
- Browser version : chrome & mozilla latest version
- Which package manager did you use for the install? npm

checkbox  Array Values don't work and not checked after click on checkbox .

please visit this page : 
https://lusaxweb.github.io/vuesax/components/checkbox.html#array-values

**Comment by LaughingCoy** [comment]
@webafra  check sulotion here #496

**Comment by webafra** [comment]
@LaughingCoy : test this version but not worked

**Comment by jsinhSolanki** [comment]
Hey @LaughingCoy use vuesax 3.8.20 latest vuesax still have some issue with vue. and if you can try using latest vue release I haven't tested latest vue release and vuesax 3.8.20

If latest vue and vuesax 3.8.20 dont work then use **vue 2.5.19 & vuesax 3.8.20**

**Comment by brunokunace** [comment]
hum.... i check today why bug with new releases of vuejs and new version of chrome

**Comment by jsinhSolanki** [comment]
As @luisDanielRoviraContreras commented in above pull(Change is reverted). So, issue is still not solved.  This issue should re-open.
