### ISSUE TITLE
vs-switch calls double function when @change

### ISSUE THREAD

**Issue by danyakov** [lusaxweb/vuesax#518]
The problem with the latest vuesax release ^3.8.39.
When I use vs-switch, I need to call function. I use @change="someFunction".
During switching this function calls and executes 2 times.
Occurs in Chrome 73.0.3683.86
Package manager Yarn.

<vs-switch v-model="switchToggle" @change="StatusSwitch(objectId)" />
methods:{
StatusSwitch (objectId) {
console.log("Check");
}
}

Will show in console
Check
Check

**Comment by LuisHCK** [comment]
Same problem here
![Screen Shot 2019-03-26 at 11 39 43 AM](https://user-images.githubusercontent.com/5175137/55020186-f3d7de00-4fbb-11e9-90c5-49be190c5e1d.png)

**Comment by jsinhSolanki** [comment]
I haven't seen code. So, i dont know why thats working but you can use @input for changes. This will be triggered only once.
Cheers ~

**Comment by danyakov** [comment]
> I haven't seen code. So, i dont know why thats working but you can use @input for changes. This will be triggered only once.
> Cheers ~

Thank you! Seems works fine.
