### ISSUE TITLE
Dark-theme doesn't work with tables.

### ISSUE THREAD

**Issue by danyakov** [lusaxweb/vuesax#519]
The problem with the latest vuesax release ^3.8.39.

Tables doesn't swich their color to black in Dark-theme.

**Comment by jsinhSolanki** [comment]
Dark theme?? Which one??

**Comment by danyakov** [comment]
In classic dark mode.
https://pixinvent.com/demo/vuesax-vuejs-admin-dashboard-template/demo-1/ui-elements/table

Everything works here if you switch to Dark Mode.

In my version - only table keeps white (normal) mode.

**Comment by jsinhSolanki** [comment]
This issue is related to Vuesax Admin Template not Vuesax Component Framework. Please contact pixinvent at their [support portal](https://pixinvent.ticksy.com/)

**Comment by danyakov** [comment]
Talked with Vuesax Admin Template developers.
Changes must be done manually by updating scss file of dark Theme.

**Comment by Johnnyevans32** [comment]
please did you fix this, if yes, help please
@danyakov
