### ISSUE TITLE
Sidebar group no icon

### ISSUE THREAD

**Issue by AngelAngelov** [lusaxweb/vuesax#522]
Hi,
In the API for the sidebar it is written:

icon | String |   | Add the icon to the item or group label.

But in the source I can not find any logic for adding icon to group item.
My case is that I want to have group item but it should look like common item with icon in front of it and down arrow in the other side to show that it is a group.

Is there any way to achieve this ?

Vue CLI: 3.5.1
vuesax: 3.8.39

**Comment by jd-0001** [comment]
You are right group **don't** have icon support.

**Comment by luisDanielRoviraContreras** [comment]
@AngelAngelov explain me better what you need and if you can make an example or image would be perfect, I will close the problem if you still persist warn me to reopen it
