### ISSUE TITLE
Tab alignments not working

### ISSUE THREAD

**Issue by javierrdzm** [lusaxweb/vuesax#523]
Tabs alignments are not working.
[JSFiddle](https://jsfiddle.net/zua0kmy9/)

vuesax@3.8.49

**Comment by jd-0001** [comment]
This issue is fixed in my latest PR. https://github.com/lusaxweb/vuesax/pull/521
Fix will be available on a merger.

**Comment by javierrdzm** [comment]
I just updated to version 3.8.52 and this issue is fixed.
