### ISSUE TITLE
Little bug on button (present demo tooltip)

### ISSUE THREAD

**Issue by RALMAZ** [lusaxweb/vuesax#53]
- Windows 7
- 10.0.0
- Current on documentation
- Yandex Browser 18.1
- Yarn

**Comment by RALMAZ** [comment]
![2018-05-13_21-31-58](https://user-images.githubusercontent.com/26162860/39970510-598a74d0-56f5-11e8-9b53-b814806dd05d.gif)

**Comment by luisDanielRoviraContreras** [comment]
@RALMAZ I think that problem is because the edge of the button is very narrow and it is not displayed well in some cases, with 2px it may improve I will review it thank you very much for the contribution

**Comment by luisDanielRoviraContreras** [comment]
@RALMAZ Would you like to do a PR to solve this problem?

**Comment by RALMAZ** [comment]
@luisDanielRoviraContreras Unfortunately i do not have enough time for this now :crying_cat_face:

**Comment by fergardi** [comment]
I think its the `overflow: hidden;` of the button. Try to change it to `overflow: visible;` and see if that helps.

**Comment by luisDanielRoviraContreras** [comment]
@fergardi if we change to `overflow: visible;` the clicking effect would overflow out of the button, look for another solution, would you like to address this problem? or do I? Thank you very much for the contribution

**Comment by luisDanielRoviraContreras** [comment]
Ready already solved the problem was by `backface-visibility: hidden;` or that I think please try with the latest version to see if it works as it should thanks for the contribution.
