### ISSUE TITLE
vs-select not working in Safari

### ISSUE THREAD

**Issue by YkkJeff** [lusaxweb/vuesax#536]
vs-select does not allow to select an item in Safari.

To reproduce the issue :
- go to https://lusaxweb.github.io/vuesax/components/selects.html#single-selection
- try to select "IT" instead of "Blade Runner" for example.

Teste on Safari version 12.0.1 (14606.2.104.1.1).

**Comment by bci24** [comment]
The same problem here in Chrome Version 73.0.3683.103 (Official Build) (64-bit) - ubuntu

**Comment by Jacrys** [comment]
@bci24  this is a separate issue.  Below is a gif showing behaviour.  @lusaxweb/vuesax, does anyone have a Mac?  I have an iPhone, but compiling and testing that way is difficult, to say the least.
![RPReplay_Final1555613070](https://user-images.githubusercontent.com/3784287/56384122-379bbd00-61e1-11e9-976a-c9a2c569da89.gif)
