### ISSUE TITLE
vs-upload - what data is sent to the action?

### ISSUE THREAD

**Issue by JeancarloPerez** [lusaxweb/vuesax#544]
Hello, I'm trying to use the vs-upload component and I want to save it with laravel. But I don't know what data is sent, I need to save the file on my project. Do you have any idea?

**Comment by manu144x** [comment]
I just did this, you need to specify it with the property fileName.

If you want to upload multiple files, keep in mind that PHP wants the name to look like an array, something like fileName="files[]" for example.

**Comment by JeancarloPerez** [comment]
Thank you for your answer @manu144x

Also I should send a csrf_token, and I'm not sending it. I think that's the reason why I'm getting an 409 error. Do you have any suggestion for it?

**Comment by manu144x** [comment]
I have no idea.

This is a pretty limited component in my opinion, I think it should have the option to let you handle the uploads yourself, or at least to have an event to intercept the request in case you want to do something with it.

**Comment by JeancarloPerez** [comment]
Thanks a lot @manu144x, I think I'm gonna find another plugin for this feature.
