### ISSUE TITLE
How can I disable autocomplete for email fields

### ISSUE THREAD

**Issue by jgirgis85** [lusaxweb/vuesax#558]
I can't disable the autocomplete feature for email input fields and there is also no option for that in the input options list.

If I add autocomplete to the input it still doesn't work
<vs-input size="large" name="email" v-model="email"  **autocomplete="off"** />

![image](https://user-images.githubusercontent.com/2014964/58015063-34eafb00-7af2-11e9-82b6-e05388437150.png)

Is there a way to achieve that?

Thanks

**Comment by brunokunace** [comment]
Hi @jgirgis85 , this is a browser issue, look

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

TL;DR;
_**"...For this reason, many modern browsers do not support autocomplete="off" for login fields..."**_
