### ISSUE TITLE
Pagination max prop is not updating dynamically

### ISSUE THREAD

**Issue by jsinhSolanki** [lusaxweb/vuesax#564]
Hi, I would like to submit new issue regrading pagination component. This component can not update max page numbers to show dynamically. Once we provide `max` and try to update dynamically/grammatically  pagination don't get affected.
It has same problem as current-page in pagination as described in this [issue](https://github.com/lusaxweb/vuesax/issues/503).

**Comment by jefryts** [comment]
Hey @jsinhSolanki , @Alexeykhr . I have already answered that question in other issue.  I hope this can help you.

[https://github.com/lusaxweb/vuesax/issues/554](url)
