### ISSUE TITLE
Support VeeValidate with VsInput

### ISSUE THREAD

**Issue by lk77** [lusaxweb/vuesax#569]
Hello,

there is a bug with vee validate on VsInput.
When adding a v-validate attribute on a VsInput, nothing happens, the field is not validated.

When replacing VsInput by a normal input, validation is working correctly.

On the input, vee validate add aria-* attributes, so we can see that it's working, and if we type an invalid value, the field become red. 
But for the input generated by VsInput, there is no such attribute and validation is not working,
the field is not becoming red when invalid data is entered.

- Your OS : Ubuntu 18.10
- Node.js version : 11.10.1
- Vuesax version : 3.8.74
- Browser version : chrome 74
- Which package manager did you use for the install? npm

Thanks.

**Comment by clopezpro** [comment]
Esto funciona para mi
```
<ValidationProvider vid="imei"  rules="required|numeric|max:15|length:15|min:15" v-slot="{ errors,valid }">
 <vs-input 
                                icon-after="true"  
                                maxlength="11"   
                                icon="fingerprint" 
                                label-placeholder="Imei "  
                                v-model="gps.imei"
                                :danger="!valid"
                                :danger-text="errors[0]"
                                />
   </ValidationProvider>   
```
