### ISSUE TITLE
VsSelect wrong value submitted

### ISSUE THREAD

**Issue by lk77** [lusaxweb/vuesax#571]
Hello,

there is a bug with VsSelect,
the text of the selected element is submitted instead of the value

```
<form method="post" action="/url/to/backend">
    <vs-select name="language_id" label="Language">
        <vs-select-item :key="index" :value="item.id" :text="item.text" v-for="item,index in languages"></vs-select-item>
    </vs-select>
</form>
```
with data : 
```
languages: Array(2)
0: {text: "english", id: 1}
1: {text: "french", id: 2}
```
result in backend :
```
[
    'language_id' => 'english'
]
```

thanks

- Your OS : Ubuntu 18.10
- Node.js version : 11.10.1
- Vuesax version : 3.8.74
- Browser version : chrome 74
- Which package manager did you use for the install? npm

**Comment by azamanaza** [comment]
It doesn't look like you have a model on the element...
try this:
```
<vs-select
  v-model="language_id"  // <----- added
  name="language_id" 
  label="Language">
```

**Comment by lk77** [comment]
Hello,
i do not need a v-model

**Comment by azamanaza** [comment]
Well then it looks like your first attempt was just the incorrect approach, as <select> elements do not have native redirection.

**Comment by lk77** [comment]
The form itself has a redirection, not the select.
