### ISSUE TITLE
Table Data Does not Updating  (vuex)

### ISSUE THREAD

**Issue by Canser** [lusaxweb/vuesax#580]
Hello. I am trying to list data computed by vuex state.

When you refresh the page and call the getter action; which is mapped in the methods, it's working with the initial data.

However; when you change the data, ie. add a new record, even I recall the action and manipulate the data (re-set the data); the table data remains still the same.

I have even tried to reset the data with object spreading method but could not get succeed.

Am I missing something or is this a known bug/problem.

**Vue Template:**

`<vs-table search :data="categories.data" pagination max-items="10">
                <template slot="thead">
                    <vs-th sort-key="id">ID</vs-th>
                    <vs-th>Title</vs-th>
                    <vs-th>Description</vs-th>
                    <vs-th sort-key="type">Type / Target</vs-th>
                    <vs-th>
                        <vs-row vs-type="flex" vs-justify="flex-end">Actions</vs-row>
                    </vs-th>
                </template>

                <template slot-scope="{ data }">
                    <vs-tr :key="indextr" v-for="(tr, indextr) in data">
                        <vs-td :data="data[indextr].id">
                            {{ data[indextr].id }}
                        </vs-td>
                        <vs-td :data="data[indextr].name">
                            {{ data[indextr].name }}
                        </vs-td>
                        <vs-td :data="data[indextr].description">
                            {{ data[indextr].description }}
                        </vs-td>
                        <vs-td :data="data[indextr].type">
                            {{ data[indextr].type }}
                        </vs-td>
                    </vs-tr>
                </template>
            </vs-table>
`

**Script:**

`<script>
    import { mapActions, mapState } from 'vuex'
    import Form from './components/Form'

    export default {
        async beforeMount() {
            await this.getCategories()
        },
        components: {
            Form
        },
        computed: {
            ...mapState({
                categories: state => state.category.categories
            })
        },
        methods: {
            ...mapActions({
                getCategories: 'adminCategory/getCategories'
            }),
        }
    }
</script>
`

- macOS Mojave
- Node.js v10.15.0
- Vuesax v3.8.39
- Chrome v74.0.3729.169 
- Npm

**Comment by Pedrazl** [comment]
Actually I am working with tables and it works fine. In my case I send the list through props and it updates normally when the list changes. If you provide a Codepen I can try to help you.

**Comment by Canser** [comment]
> Actually I am working with tables and it works fine. In my case I send the list through props and it updates normally when the list changes. If you provide a Codepen I can try to help you.

Do you provide the data from vuex?
