### ISSUE TITLE
Checkbox does not work correctly on Microsoft Edge.

### ISSUE THREAD

**Issue by felipefreitasweb** [lusaxweb/vuesax#589]
In the Microsoft Edge browser the checkbox does not work correctly, when checking it does not change the value of the checkbox

`<input type = "checkbox" class = "vs-checkbox - input" `value="**true**">`

It seems to me that it does not trigger an event by dialing and unchecking, it impacts when it's time to validate.

To test in this theme that uses vuesax, in the edge it goes through the validation even without marking the checkbox of the terms, being it is mandatory. In other browsers it works.

Test: https://pixinvent.com/demo/vuesax-vuejs-admin-dashboard-template/demo-1/pages/register

- Windows 10
- Ubuntu 18
- Node.js v8.10.0
- Vuesax 3.8.75
- Browser Microsoft Edge 18

**Comment by stockarea** [comment]
Yeah I am also facing the same error above. Any fixes for it.

**Comment by tongyifan** [comment]
Same issue...

**Comment by Marekkon5** [comment]
You can workaround this by listening to change event  (`@change='test'`) and later updating manually 
```
test(e) {
  this.myVar = e.target.checked;
}
```
