### ISSUE TITLE
vs-select - the options list does not close when it is out of focus

### ISSUE THREAD

**Issue by cstriuli** [lusaxweb/vuesax#598]
- OS: macOS Mojave 10.14.5
- Node.js: 12
- Vuesax: 3.8.75
- Browser version: Chrome  75
- Which package manager did you use for the install? NPM

v-select with model empty
![Example](https://i.ibb.co/DYwQ5K0/select-without-item-selected-1.gif)
https://i.ibb.co/DYwQ5K0/select-without-item-selected-1.gif

v-select with model filled
![Example](https://i.ibb.co/r7Kh7Z8/select-with-item-selected-1.gif)
https://i.ibb.co/r7Kh7Z8/select-with-item-selected-1.gif

Codesandox example:
https://codesandbox.io/embed/vuesax-vs-select-bug-78i0u

On the official docs also has the same behavior: 
![Example](https://i.ibb.co/KrRPS1b/Screen-Shot-2019-07-04-at-12-26-25-PM.png)

**Comment by thepepperone** [comment]
Same issue here. Are we missing something? :(

**Comment by joewitchy** [comment]
same issue!!!!!

**Comment by ngekoding** [comment]
Same here, need help.

**Comment by davehowson** [comment]
Same. Had to start using [Vue-Select](https://vue-select.org/) instead of the default select.

**Comment by tiagosimoesdev** [comment]
Same here  ..

**Comment by ibnuh** [comment]
Any updates on this issue?

**Comment by lk77** [comment]
same issue here, and blur event is broken...

**Comment by Tsquared** [comment]
still same issue.

**Comment by ramyaksingh** [comment]
Have there been any updates on this anywhere? Still encountering this issue.
