### ISSUE TITLE
AgGrid issue with lazy loading of images in chrome 75

### ISSUE THREAD

**Issue by lk77** [lusaxweb/vuesax#605]
- Your OS : Ubuntu 18.10
- Node.js version : 11.10.1
- Vuesax version : 3.8.75
- Browser version : chrome 75
- Which package manager did you use for the install? npm

Hello,

there is a issue when we enable the lazy loading feature of chrome 75 (in chrome://flags),
The checkboxes of the ag-grid are not displayed correctly on the demo page of the admin template. When selecting, the checkbox disappear. it seems that the background image is not loaded. 

It's working correclty on ag-grid demo, so perhaps it's related to the customization done by the vuesax admin template.

thanks.

![Peek 2019-07-09 14-15 (1)](https://user-images.githubusercontent.com/9606882/60899562-f90b2100-a26a-11e9-934a-70c63ba0d1b3.gif)

**Comment by jsinhSolanki** [comment]
Hello,
This is github repo of vuesax framework. Please raise ticket at Template's support portal.
[Support Portal](https://pixinvent.ticksy.com/)

**Note: Vuesax Admin Template is not created by creators of vuesax framework. Please close this issue and raise support ticket at their portal**
~ Regards

**Comment by lk77** [comment]
Ok, honestly i will not. I report issues on github or i don't report them.
