### ISSUE TITLE
Carousel seems to be missing here

### ISSUE THREAD

**Issue by kamleshkatpara** [lusaxweb/vuesax#61]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fergardi** [comment]
I like to use [https://wlada.github.io/vue-carousel-3d](https://wlada.github.io/vue-carousel-3d/) for my VueJS projects. It can be integrated easily, just by wrapping components on it. There is no need to reinvent the wheel in every new UI framework, in my opinion.

**Comment by luisDanielRoviraContreras** [comment]
Well that clear component that must be done either by relieving programmers with a single framework to create an application and also because that component does not have the style of Vuesax would be something more minimalist

@kamleshkatpara you want to help in this component?

**Comment by luisDanielRoviraContreras** [comment]
I would love for you to help us then do you want to do this component?

**Comment by kamleshkatpara** [comment]
@luisDanielRoviraContreras  Not clear by what you mean to say. But Yes I am looking to use Carousel in Vuesax

**Comment by luisDanielRoviraContreras** [comment]
@kamleshkatpara 
I do not know if I made myself misunderstand the idea is that you make the carousel for Vuesax a new component that you create and make the documents about the

**Comment by kamleshkatpara** [comment]
@luisDanielRoviraContreras  I thought you would help me

**Comment by luisDanielRoviraContreras** [comment]
@kamleshkatpara clear that if friend what I want is that you get involved in the creation of the component that is what you need and if you can help in code would be great. quiet you do not need to commit to doing so you can help with ideas and examples of what vuesax lacks
