### ISSUE TITLE
Input icons are displaced

### ISSUE THREAD

**Issue by fergardi** [lusaxweb/vuesax#62]
The icon CSS appears a bit displaced to the bottom.

- Windows 10
- Node 8.9.3
- Vuesax 3.0.8
- Chrome 66.0.11
- NPM 6.0.0

https://lusaxweb.github.io/vuesax/components/input.html#icons

![image](https://user-images.githubusercontent.com/3602272/40054497-4f864e68-5845-11e8-8b5f-a17404d24341.png)

**Comment by luisDanielRoviraContreras** [comment]
I'm going to check it to see for sure it's something with the padding of the icon, thank you very much, anything, let me know if you see the solution

**Comment by eyedeceiver03** [comment]
I had a solution for this bug 😄
