### ISSUE TITLE
New component: List

### ISSUE THREAD

**Issue by fergardi** [lusaxweb/vuesax#63]
Just like in https://material.io/design/components/lists.html

This will be my next component.

**Comment by luisDanielRoviraContreras** [comment]
Excellent I am in the Avatar component after we integrate the two then I will assign you this

**Comment by luisDanielRoviraContreras** [comment]
@fergardi Now the [Avatar](https://lusaxweb.github.io/vuesax/components/avatar.html) component is ready now you can implement it together with list anything you tell me thank you very much for the contribution

**Comment by luisDanielRoviraContreras** [comment]
Ready and the list component is in production thank you very much! and add avatar support plus some details of form
