### ISSUE TITLE
Using vuejs-tips/vue-the-mask with vs-input

### ISSUE THREAD

**Issue by joelpiccoli** [lusaxweb/vuesax#653]
Hello, I was wondering if it possible to use the both plugin together to handle masked inputs more easily, specially with label placeholder option.

I've tried to implement this, but the result wasn't satisfactory, there is any way to do this?

**Comment by vittis** [comment]
Import vue-the-mask locally on the component as a directive:

```javascript
import {mask} from 'vue-the-mask'
export default {
  directives: {mask}
}
```

Then use it in the input like that:

```
<vs-input v-mask="['(##) ####-####', '(##) #####-####']" />
```
