### ISSUE TITLE
How to conditionally render the sidebar menu items based on User Permissions?

### ISSUE THREAD

**Issue by vnayak-bhatt** [lusaxweb/vuesax#658]
Hello, I am working on a project which is using this theme, but when I am managing the permissions, I cannot render the menus based on the user privileges.
I have role attribute in the meta tag of router.js which will be crosschecked from the store(privileges of that particular user), and based on that I have to conditionally render the sidebar menu items, and as the menu items are written in sidebarmenuitems.js, so it is difficult for me to manipulate them.
Help is needed and appreciated.

**Comment by jsinhSolanki** [comment]
This issue is related to Vuesax Admin Template, not Vuesax Component Framework. Please contact pixinvent at their [support portal](https://pixinvent.ticksy.com/)
