### ISSUE TITLE
Click-Event vs-icon

### ISSUE THREAD

**Issue by CaptainCannabis** [lusaxweb/vuesax#661]
How to bind a method to the click event of a vs-icon-component?

None of these works

`<vs-icon icon="backspace" size="medium" color="primary" @click="alert('Test');"></vs-icon>`

`<vs-icon icon="backspace" size="medium" color="primary" v-on:click="alert('Test');"></vs-icon>`

`<vs-icon icon="backspace" size="medium" color="primary" click="alert('Test');"></vs-icon>`

**Comment by luisDanielRoviraContreras** [comment]
solved in the latest version, thanks

**Comment by CaptainCannabis** [comment]
> solved in the latest version, thanks

awesome!
