### ISSUE TITLE
Tooltip misplacement

### ISSUE THREAD

**Issue by fergardi** [lusaxweb/vuesax#67]
When you scroll down after a tooltip has been shown the next time it appears in the same position as before, but without the new scrolled calculation.

![image](https://user-images.githubusercontent.com/3602272/40101194-fce9036a-58e6-11e8-9e79-85dc18e9964c.png)

![image](https://user-images.githubusercontent.com/3602272/40101220-106df3a0-58e7-11e8-9bc6-54373c7afe27.png)

**Comment by luisDanielRoviraContreras** [comment]
I already checked and if the problem happens to me too I'm going to check it to see if I fix it thank you very much if you find the way warn me.

**Comment by luisDanielRoviraContreras** [comment]
@fergardi Ready and the error is solved thank you very much

![screenshot_47](https://user-images.githubusercontent.com/31676496/40241244-84a2297e-5a88-11e8-95cd-bf87dd01de81.png)
