### ISSUE TITLE
Button text missing

### ISSUE THREAD

**Issue by eyedeceiver03** [lusaxweb/vuesax#69]
OS: Windows 10
Browser: Firefox Developer Edition 61.0b5 (64-bit)

The first load of the page, the text of the button still appears but when I refresh the page the text of the button disappears.

![screenshot_1](https://user-images.githubusercontent.com/17470909/40155264-4b162de0-59c5-11e8-9320-da8454ae756c.jpg)

**Comment by eyedeceiver03** [comment]
I reproduced the problem

I think it's VuePress? (Correct me if I'm wrong)

![Reproduce](https://user-images.githubusercontent.com/17470909/40155678-adbdc4d8-59c7-11e8-9c75-34e8cd9809cc.gif)

**Comment by fergardi** [comment]
When you enter directly on a page it seems to have a stranger behaviour. As soon as you change the route, it solves.

**Comment by luisDanielRoviraContreras** [comment]
@eyedeceiver03 Ready and the problem is solved apparently it was something concerning the `v-if` and` v-else` that had some delay with `v-html` thanks for the contribution

Please check if everything works as it should

**Comment by eyedeceiver03** [comment]
It's now working! 🎉 Thanks!
