### ISSUE TITLE
Get current sort item

### ISSUE THREAD

**Issue by hassan-mohagheghian** [lusaxweb/vuesax#696]
When use sort in tables, a very useful think is get sorted key and use it to send to server for next queries. Is there such a possibility?

**Comment by aabiabdallah** [comment]
This can be achieved by using the @sort property.

```
<vs-table :sst="true" @sort="handleSort" ...>

methods:{
    handleSort(key, active) {
      // call a server API or something
    }
}
```

**Comment by MOHAGHEGHIYAN** [comment]
this is perfect. there is no information about in document clearly.
