### ISSUE TITLE
Feature Request - Navigation (Menus)

### ISSUE THREAD

**Issue by coldsun1187** [lusaxweb/vuesax#7]
This design is very nice.  I think this framework could really grow and be a major part of the vue family.  It really needs the basics like the information on grid/layout and navigation controls (menu).

Great work so far!

**Comment by luisDanielRoviraContreras** [comment]
thank you very much friend that I hope, well I am in process in that aspect to deliver a complete job thank you very much for the support as soon as you finish notice by my twitter so you can try it and implement it
