### ISSUE TITLE
Adding more theme color options

### ISSUE THREAD

**Issue by VicGUTT** [lusaxweb/vuesax#70]
I think it would be great if we had more theme color options or kinda like two group of options.

### Let me explain
When I work, I usually like having two groups of color themes :
- The *app level* themes (danger, success, warning). Those colors will pretty much be always the same no matter the project.
- The *brand* themes which will be customized to suit every project branding

### I would suggest the following
- App level :
    - Success (green)
    - Info (blue or maybe purple)
    - Warning (orange)
    - Danger (red)
- Brand colors :
    - Primary
    - Secondary

**Aside**
Since we have a `Dark` color, shouldn't we also have a `light` one ?

**Comment by VicGUTT** [comment]
Yes pretty much. And also an `info` color which would be **blue**.
The primary color for Vuesax will therefore be **purple** since that's the colors that's primarily used on the docs site and logo.

The `primary` and `secondary` colors should be the ones that should be highly customizable in order to apply the project's branding colors. The other ones can be customizable as well but they won't change much from projects to projects (Meaning the `danger` color will always be a shade of red)

**Comment by luisDanielRoviraContreras** [comment]
You have all the right friend but you have to define the color **primary** as blue initially in vuesax the user would change the color for each use case to his preference and an example in the vuesax documents would be **purple** me love the idea of ​​adding them you can do a PR of this without any question question me, thank you very much for the contribution

**Comment by ziadzadeh** [comment]
If you like I can help you with that!

**Comment by luisDanielRoviraContreras** [comment]
@ziadzadeh clear you can always help the only thing is that now I'm migrating all the components to stylus for support issues in SSR and better functioning

If you want to more or less understand the change, the buttons were made completely from 0 in the migration that is the approach that is going to be done in all the components

https://github.com/lusaxweb/vuesax/blob/master/src/components/vsButton/vsButton.vue

thank you very much for wanting to help and the contribution

**Comment by luisDanielRoviraContreras** [comment]
All the components have the same language and it is much better understood thanks to the contribution
