### ISSUE TITLE
VsPrompt Not Closing and hangs the screen when someone presses back button

### ISSUE THREAD

**Issue by Apoorv-Bhatnagar** [lusaxweb/vuesax#717]
On pressing back button Vs-Prompt gets stuck on the screen and it does not respond.
While that is not the case for dialog ( function extended by using Vs-Prompt) ,The reason is `  ```
instance.vm = instance.$mount();

  props.accept?instance.vm.$on('accept', props.accept):null
  props.cancel?instance.vm.$on('cancel', props.cancel):null
`
```
As When using the function you are mounting the entire thing in the vue instance and listening for the event listener,therefore it works properly.

While In Vs-Prompt it is being specific to that page only and when some other Vue page renders on the screen, The Prompt gets stuck and locks the entire DOM.

Please Fix this as soon as possible because we are using your framework in the production mode.

**Comment by shivamguys** [comment]
https://github.com/lusaxweb/vuesax-next/issues/20
