### ISSUE TITLE
dist/ directory was removed

### ISSUE THREAD

**Issue by aunpyz** [lusaxweb/vuesax#764]
the whole directory was removed in version 3.11.12 causing the **can't resolve 'vuesax' error**
Error when run `npm run development -- --watch`
![image](https://user-images.githubusercontent.com/14342782/73868960-fc57a100-487b-11ea-9bf9-4ee1c04b29cb.png)
themeConfig.js :
![image](https://user-images.githubusercontent.com/14342782/73869325-adf6d200-487c-11ea-8fca-de292f5bb218.png)
dist/ was removed in this commit 3fbf44c1f4487ba83d2074161865ec15a8ed7f9d
![image](https://user-images.githubusercontent.com/14342782/73868406-f90fe580-487a-11ea-961c-df13ca26f6c1.png)

**Comment by l2aelba** [comment]
This project is not active anymore ? Even I paid for Vuexy :D

**Comment by dker92** [comment]
Yeah, I got the same issue

**Comment by luisDanielRoviraContreras** [comment]
Ready solved

**Comment by luisDanielRoviraContreras** [comment]
@l2aelba @dker92  Vuesax has nothing to do with Vuexy. They just grabbed the framework to make money.

If I buy your admin it has nothing to do with us

**Comment by dker92** [comment]
@luisDanielRoviraContreras  Yeah I know that.
So the directory dist has been added and there is the vuesax.css inside  ?

**Comment by luisDanielRoviraContreras** [comment]
yes

**Comment by dker92** [comment]
@luisDanielRoviraContreras cool
Was there a reason why this folder was removed ?

**Comment by luisDanielRoviraContreras** [comment]
a compiling error that did not generate the dist

**Comment by l2aelba** [comment]
> 
> 
> @l2aelba @dker92 Vuesax has nothing to do with Vuexy. They just grabbed the framework to make money.
> 
> If I buy your admin it has nothing to do with us

Wooooot!!!!! Bad to hear. I did not know that before
