### ISSUE TITLE
Pagination total in sst table

### ISSUE THREAD

**Issue by Oipnet** [lusaxweb/vuesax#772]
The pagigation is not correct when using sst table.
Number of pages is 1 in the pagination because he is based on length of data props and not the total props
```js
getTotalPages() {
  return Math.ceil(this.data.length / this.maxItemsx)
},
```

you can test this code : https://github.com/Oipnet/vuesax-sst-table

**Comment by ibrahimyu** [comment]
Any workaround on this? I'm surprised so few people affected...

**Comment by borntodive** [comment]
this should be

`getTotalPages() {
  return Math.ceil(this.total/ this.maxItemsx)
},`

hope on an update

thank you so much
