### ISSUE TITLE
vs-table multiple select box not working

### ISSUE THREAD

**Issue by shivamguys** [lusaxweb/vuesax#773]
![Screenshot from 2020-02-18 16-46-10](https://user-images.githubusercontent.com/25263989/74731772-bf71ae00-526e-11ea-8d96-2658ae4e269b.png)

**Comment by shivamguys** [comment]
Fix this team as we are using this in production, kindly stabilize it.

**Comment by shivamguys** [comment]
any updates?

**Comment by ChronicStone** [comment]
Hi man, I was wondering if you happened to find out a solution ? I've been trying to solve the same problem for a week and did not find anything ...

**Comment by mehniyarif** [comment]
my solution render function editing. 

copy and import components inside the repository in the project
https://github.com/mehniyarif/Vs-table-select-all-solution
