### ISSUE TITLE
Help: How can i use font awesome brands icons?

### ISSUE THREAD

**Issue by securisec** [lusaxweb/vuesax#775]
I was trying to follow along on how to use font-awesome icons, but I simply cant seem to make it work. 

In my `main.js`, I am importing the css correctly with `import 'font-awesome/css/font-awesome.css'`, and trying to set the the icon with:

```vue
<vs-button
	size="small"
	type="gradient"
	color="danger"
	icon-pack="fa"
	icon="close"
></vs-button>
```

but nothing seems to pick up the icons. The same issue applies with brands. It would be really helpful if someone could share a working example on how they are implementing fontawesome with vuesax.

**Comment by crimsonalba** [comment]
@securisec 

Not sure if youre still having this issue, but I think you have a couple problems here:
1) "close" does not seem to be a free font awesome icon, you can search for htem here: https://fontawesome.com/icons?d=gallery&q=close

2) I found you need to prefix in the icon name with "fa"

This works for me:
```
	<vs-button
		size="small"
		type="gradient"
		color="danger"
		icon-pack="fa"
		icon="fa-times-circle"
	></vs-button>
```

**Comment by securisec** [comment]
Thanks @crimsonalba ! That was it!
