### ISSUE TITLE
Issue with collapse component on resizing

### ISSUE THREAD

**Issue by west1609** [lusaxweb/vuesax#787]
I get this error every time I resize my browser. It's an error from the collapse component.

![image](https://user-images.githubusercontent.com/49612344/76964374-345f0300-6955-11ea-9598-a554257f654a.png)

Compilation error: 
```
Uncaught TypeError: Cannot read property 'scrollHeight' of undefined
    at VueComponent.changeHeight (vuesax.common.js?fb9a:11118)
changeHeight @ vuesax.common.js?fb9a:11118
```

**Comment by Aleemcode** [comment]
Is there any solution for this? I'm also having similar error

**Comment by maximesahagian** [comment]
Same.. @west1609 did u find any solution?

**Comment by antoinececchi** [comment]
Hello, 
I found a work around, which is to edit the vuesax.common.js and add these lines from line 10911. 

`beforeDestroy() {
    window.removeEventListener('resize', this.changeHeight);
  },`

Another solution is to add it to every file in which you use a vs-collapse and call `window.removeEventListener('resize', this.changeHeight)`. Obviously you have to replace this by the instance of vs-collapse-item. 
``` vuejs
<vs-collapse>
   <vs-collapse-item ref="vsCollapseItem">
    Your code 
 </vs-collapse-item>
</vs-collapse>

  export default {

beforeDestroy() {
if (this.$refs.vsCollapseItem) {
    for (let collapseItem of this.$refs.vsCollapseItem){
    window.removeEventListener('resize', collapseItem);
   }
   }
  },
}
```

**Comment by knhmb** [comment]
Hi, Can someone walk me through how to solve this error, I have been struggling with it.
Thank you in advance
