### ISSUE TITLE
Sliders don't slide on Android 

### ISSUE THREAD

**Issue by captainswain** [lusaxweb/vuesax#8]
Hi,

I have encountered an issue where you can not drag the sliders on Android. You can tap on the slider and change the value, but not actually move it. Also, if you long press on the slider it returns NaN for the value.

Android 8.1.0
Chrome webbrowser
Vuesax documentation page

**Comment by luisDanielRoviraContreras** [comment]
thank you very much friend for the contribution I will review it and fix it when I have it I notice

**Comment by luisDanielRoviraContreras** [comment]
friend and fix the slider and the touch works I would love to try it to see if it works thanks for the contribution v2.0.49
[Slider](https://lusaxweb.github.io/vuesax/#/docs/slider)
