### ISSUE TITLE
New component: Autocomplete

### ISSUE THREAD

**Issue by qiandongyq** [lusaxweb/vuesax#80]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by qiandongyq** [comment]
Can be something like this:
![image](https://user-images.githubusercontent.com/24208956/40270552-5d9dbf66-5b5d-11e8-9464-31fb5841fda4.png)

**Comment by luisDanielRoviraContreras** [comment]
It's a very good idea, would you like to help with this component? and you just found also a bug should not show `<! - # update ->` I'll fix it thank you very much

**Comment by luisDanielRoviraContreras** [comment]
the functionality to the select component is already ready, thank you very much for the contribution
![screenshot_13](https://user-images.githubusercontent.com/31676496/40819677-49bbd786-652a-11e8-85a6-177661f4b7c1.png)

http://localhost:7070/vuesax/components/selects.html#autocomplete

**Comment by mn113** [comment]
This component is able to overwrite your bound text data with an InputEvent object if you force-trigger an update (e.g. with a save button on the page) during the stage when you are typing in some text and a specific value has not been selected.

I'd prefer it if, in such a case, it would always fall back to the original selected value until a new valid value has been selected with or without the help of typing.

**Comment by luisDanielRoviraContreras** [comment]
thank you very much for the contribution if you want to help in this improvement would be great
