### ISSUE TITLE
Add ability to programmatically close vs-dropdown

### ISSUE THREAD

**Issue by mreall** [lusaxweb/vuesax#831]
**Is your feature request related to a problem? Please describe.**
When opening a dropdown menu, the only way to close it is to click on a menu item, click on the button that was used to open the menu, or to click on something else on the page.  However, it would be useful to also force the dropdown menu to close when some other action happens on the page, especially when using the vs-custom-content attribute.

**Describe the solution you'd like**
Perhaps bind the menu visibility to an optional prop so we can manually set it when needed.

**Describe alternatives you've considered**
Using a v-if on the dropdown menu component, but that will also remove the main menu button.

**Comment by zatziky** [comment]
Hi, you can do this by assigning a random key to `<vs-dropdown>`.
```
<template> 
   <vs-dropdown @click="closeDropdown" :key="dropdownKey">
      ...
</template>

<script>
    ...
    data() {
      return { dropdownKey: 0 }
    },

    methods: {
       closeDropdown() {
             this.dropdownKey = Math.random()
       }
    ...
</script>

```
