### ISSUE TITLE
3.11.16 Is broken

### ISSUE THREAD

**Issue by Tofandel** [lusaxweb/vuesax#845]
The latest deploy commit deleted all the dist files and as such the published npm package is broken.

As a result:

This dependency was not found:

* vuesax in ./resources/js/themeConfig.js, ./resources/js/src/main.js

Please unpublish this version until it is solved or force a republish with the correct files

**Comment by Capellan29** [comment]
I'm having the same problem, please fix that :(

**Comment by djvicio** [comment]
Same problem here, this version doesnt generate the dist folder with the css styles :(

**Comment by dipanshunagar** [comment]
Same issue, reverted to 3.11.15 for now

**Comment by KayJay89** [comment]
Ditto.

**Comment by wasinr** [comment]
Same problem.

**Comment by Tofandel** [comment]
https://github.com/lusaxweb/vuesax/tree/2d85cddbc90d32bd356c996e8df88606f209a75f
