### ISSUE TITLE
Navbar component?

### ISSUE THREAD

**Issue by focussing** [lusaxweb/vuesax#86]
That is the only one I would be missing right now.
Currently I use the [this one](https://bootstrap-vue.js.org/docs/components/navbar) which is easy and works fine, but that is the only reason for importing bootstrap / bootstrap-vue...

**Comment by luisDanielRoviraContreras** [comment]
Well, it's not exactly a navBar or it was not the initial objective but I think this can work for you and if you do not want to let us know what are the improvements you need and some properties that you would like to add

https://lusaxweb.github.io/vuesax/components/topbar.html
