### ISSUE TITLE
vsCheckbox not working properly with objects

### ISSUE THREAD

**Issue by Marcellofabrizio** [lusaxweb/vuesax#884]
- Ubuntu 20.04
- v12.18.3
- Vuesax 3.11.1
- Chrome 84.0.4147.105
- NPM used for install

I'm trying to use an array of objects as values to my checkboxes, as specified in the [Vuesax documentation](https://lusaxweb.github.io/vuesax/components/checkbox.html#array-object-values). But I stumbled upon an error, that I managed to recreate on a [Codesandbox](https://codesandbox.io/s/checkbox-ug-h811i). The error is that once there's already a value in my v-model array, the same is not selected in the checkbox, and when it's added, I end up with two of them.

**Comment by lichen404** [comment]
@Marcellofabrizio Because even they are equal, they are different in memory.you need ensure the two variables are the same in memory like this
[Codesandbox](https://codesandbox.io/s/checkbox-ug-forked-7gx90?file=/src/App.vue).

**Comment by Marcellofabrizio** [comment]
Thanks, that solved it!
