### ISSUE TITLE
Checkbox -> item.indexOf is not a function

### ISSUE THREAD

**Issue by Google-Mac** [lusaxweb/vuesax#89]
- OS: Mac High Sierra 10.13.4
- Node.js: v8.9.4
- Vuesax: ^3.0.46
- Browser: Chrome 67.0.3396.62 (Official Build) (64-bit)
- Package Manager: npm

When using a checkbox component (Vuesax is globally registered), I get the item.indexOf is not a function error.

<vs-checkbox v-model="editDepartmentForm.user_ids" :vs-value="user.id" :key="user.id">{{ user.first_name }} {{ user.last_name }}</vs-checkbox>

The checkboxes are correctly styled and can be checked. This issue occurs when clicking to remove the check.

**Comment by luisDanielRoviraContreras** [comment]
You could pass me a sample of the code to verify how the error occurs and fix it, thank you very much for the contribution

**Comment by luisDanielRoviraContreras** [comment]
Already the problem is solved thank you very much for the contribution, please check if it works as it should thanks
