### ISSUE TITLE
Dependencies were not found: * vuesax in ./themeConfig.js, ./src/main.js

### ISSUE THREAD

**Issue by vatslavzoltan** [lusaxweb/vuesax#897]
- MacOS
- Node.js v10.19.0
- Vuesax version ^3.11.18
- NPM

I can`t run the project. Error text: Dependencies were not found: * vuesax in ./themeConfig.js, ./src/main.js.
I tried to change vuesax version but got the same error. There was no such problem yesterday.
After installing  node_modules/vuesax looks like incomplete:
![image](https://user-images.githubusercontent.com/21958549/92953511-7e3f2680-f46a-11ea-83e8-18d0e7679f02.png)

**Comment by Dead-Master** [comment]
There is a problem in version 3.11.18, use 3.11.17
the problem is in this commit)))
https://github.com/lusaxweb/vuesax/commit/39ac70a8f370afe50d5a31e92449e3c184d3bebe

I hope the author will correct it quickly, it's not difficult there

**Comment by vatslavzoltan** [comment]
Thanks, bud)

**Comment by vinniehat** [comment]
Also having this issue. Appreciate it Dead-Master, I'll downgrade!

**Comment by victorybiz** [comment]
I'm having the same issue in 3.11.18...

**Comment by ShehryarKh** [comment]
@Dead-Master downgrading is throwing the same error. I've removed the node_modules dir and ran into the same issue.

**Comment by luisDanielRoviraContreras** [comment]
v3.12.0
