### ISSUE TITLE
Missing dependencies with latest vuesax

### ISSUE THREAD

**Issue by ajitgoel** [lusaxweb/vuesax#898]
After generating the project with the latest version, I get the following error:

These dependencies were not found:
* vuesax in ./src/plugins/vuesax.js
* vuesax/dist/vuesax.css in ./src/plugins/vuesax.js

To install them, you can run: npm install --save vuesax vuesax/dist/vuesax.css
When I check the vuesax folder in my node_modules folder, I found that the /dist folder does not exist
I also deleted the node modules folder and recompiled it and get the same error.

windows 10
vuesax : 3.11.18

**Comment by ajitgoel** [comment]
Thank you @Dead-Master , I tried downgrading to 3.11.14, 3.11.15, 3.11.17 but I have the same issue.  Before each downgrade I ensured that the node_modules folder was deleted.

**Comment by ShehryarKh** [comment]
@ajitgoel do the following:
`npm remove vuesax`
`npm install vuesax@3.11.17`

**Comment by ajitgoel** [comment]
I still have the same issue, This is on Windows 10.
I do not have the same issue on ubuntu. 

![image](https://user-images.githubusercontent.com/6394444/93387728-4d2a7180-f82f-11ea-8fe6-7fdab1f38169.png)

**Comment by luisDanielRoviraContreras** [comment]
v3.12.0

**Comment by ajitgoel** [comment]
Thank you @luisDanielRoviraContreras , v3.12.0 fixed the issue on windows 10.
