### ISSUE TITLE
When clicked the side menu at mobile phone, it does not hide the side menu.

### ISSUE THREAD

**Issue by javapad** [lusaxweb/vuesax#9]
Hi! I am using the pixel phone,
Please check the side menu,  I want same function like https://admin.vuebulma.com/#/
thanks

**Comment by luisDanielRoviraContreras** [comment]
You can tell me in what version and in what device thank you very much

**Comment by javapad** [comment]
Chrome 64.0.3282, android 8.1.0 google pixel xl

**Comment by luisDanielRoviraContreras** [comment]
Ready friend already add the functionality thank you very much for the help
