### ISSUE TITLE
Font Issue - My app font is overridden by Vuesax's font

### ISSUE THREAD

**Issue by bojanxmk** [lusaxweb/vuesax#90]
Hello,

First of all i would like to say thank you for such an awesome package. There was already an issue reported about this. You had font-family applied to the * selector, then you removed it but now the same issue happens because you applied font-family to the body selector in [index.css](https://github.com/lusaxweb/vuesax/blob/master/src/css/index.css). 

Is there any way you could remove these selectors from your css files? using *, body, button selectors in your package makes other css applied to one's application being overridden by yours. Also, its a bad practice to use !important to override your css. 

Kind regards

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much! I will review the problem and I will notify you so that you can verify it

**Comment by luisDanielRoviraContreras** [comment]
Ready is already solved thank you very much for the contribution review in the latest version to see if everything works as it should
