### ISSUE TITLE
Theme variables not working

### ISSUE THREAD

**Issue by DeehSlash** [lusaxweb/vuesax#91]
I'm using Vuesax with Nuxt.js.
This issue happened both with Dialog and Notification. When I try to call them and pass 'color' as some theme variable (like success), it doesn't work, it shows as white.

I had to manually define the default theme for this to work.

**Comment by DeehSlash** [comment]
Sure, it's a college job, so no problems: https://github.com/DeehSlash/OAC-FrontEnd

**Comment by luisDanielRoviraContreras** [comment]
A new methodology has already been added to change the variables by means of stylus for SSR support

https://lusaxweb.github.io/vuesax/theme/#change-colors-ssr
