### ISSUE TITLE
Support RTL direction

### ISSUE THREAD

**Issue by barakat-turki** [lusaxweb/vuesax#93]
there're lots of projects that are based on both RTL and LTR directions.

most of the frameworks do'not care about that feature.

that will be a good advantage of ur framework.

It will likely use some tool similar to https://cssjanus.github.io/ or https://github.com/MohammadYounes/rtlcss

**Comment by luisDanielRoviraContreras** [comment]
I'm going to review to see I like the idea if you want to help doing a PR on this would be great thank you very much for the proposal
