### ISSUE TITLE
Error in mounted hook: "TypeError: Invalid attempt to spread non-iterable instance"  when using VsTable

### ISSUE THREAD

**Issue by u007** [lusaxweb/vuesax#940]
- Your OS: POPOS 20.04
- Node.js version 12.19.0
- Vuesax version: github:jd-0001/vuesax#1d6c70c6e9813d50d01982733b828a63b712acb6
- Browser version: firefox 83.0 (64-bit)
- Which package manager did you use for the install?
npm

i tried to embed the simplest vstable code and getting error stated in title

```
<template>
  <div>
      <vs-table>
    <template #thead>
      <vs-tr>
        <vs-th>
          Name
        </vs-th>
        <vs-th>
          Email
        </vs-th>
        <vs-th>
          Id
        </vs-th>
      </vs-tr>
    </template>
  </vs-table>
</div>
</template>
```

haven't even tried to insert body yet

error:
```
[Vue warn]: Error in mounted hook: "TypeError: Invalid attempt to spread non-iterable instance"

found in

---> <VsTable>
       <Index> at src/views/orders/Index.vue
         <Main> at src/layouts/main/Main.vue
           <App> at src/App.vue
             <Root>
```

**Comment by margot-vogo** [comment]
You must use `<vs-table v-if="data && data.length">` for check if data is loaded.

**Comment by u007** [comment]
thank you , works fine now
