### ISSUE TITLE
Table is missing

### ISSUE THREAD

**Issue by rajanmagar** [lusaxweb/vuesax#96]
Why I can't see any option for table?

**Comment by luisDanielRoviraContreras** [comment]
Still that component is not created, would you like to help do it?

**Comment by roonie007** [comment]
@luisDanielRoviraContreras I can help with that

**Comment by luisDanielRoviraContreras** [comment]
@roonie007 If you want you can help in a somewhat easier component or with some existing ones, thanks for the contribution.

**Comment by ziadzadeh** [comment]
I can help you to do it.

**Comment by luisDanielRoviraContreras** [comment]
It would be great the only thing is that this component is somewhat complicated if you want you can do something simpler to start and then this something like Collapse (Accordion) clear if you think you can do this component well forward and thank you very much

**Comment by pitchinnate** [comment]
I have a basic table component created if you are interested in seeing it I can create a branch on my fork.

**Comment by luisDanielRoviraContreras** [comment]
Of course no problem, this component is not done because I want it to have all the functionalities such as editable, add row, add colum, checked row, filter, pagination, remove row, disabled value, to be really functional and necessary

**Comment by pitchinnate** [comment]
Mine is a basic table for displaying an array of objects. You can specify the headers, data source, and columns. Has built in functionality to display an edit and/or delete button. So it sounds like it is lacking a lot of the features you are looking for.

**Comment by luisDanielRoviraContreras** [comment]
Well thank you very much for the contribution you are giving to Vuesax and the community

**Comment by fergardi** [comment]
This is the las component I would need this framework to have in order to use it for my personal projects. Any progress on this?

For me, the minimum features should be:

* Column sorting
* Column filtering
* Global search
* Action buttons
* Row selection for batch actions (checkboxes)
* Pagination

This could be a good start point: https://vuematerial.io/components/table

**Comment by luisDanielRoviraContreras** [comment]
Well for now I am in stabilizing all the components for support ssr and better accessibility as soon as I finish that I put in this component that really is important thanks to all

**Comment by luisDanielRoviraContreras** [comment]
Added the vs-table component in the latest version, thank you very much

https://lusaxweb.github.io/vuesax/components/table.html#default
