### ISSUE TITLE
Navbar dropdown glitches when dropdown item and dropdown content are hovered at the same time

### ISSUE THREAD

**Issue by dumptyd** [lusaxweb/vuesax#97]
https://gfycat.com/FrightenedShamelessFirebelliedtoad

**Comment by luisDanielRoviraContreras** [comment]
I do not really think that it is a problem, but I would like to thank you very much for the contribution and to clarify it would be a vuepress problem since the documents are made with it.

**Comment by dumptyd** [comment]
Thanks. By the way, do you guys have any plans to create a navbar component? I searched the site but couldn't find anything.

**Comment by luisDanielRoviraContreras** [comment]
If I'm doing the sidebar now and when I finish it, I'll use that
