### ISSUE TITLE
Spanish Console Logs

### ISSUE THREAD

**Issue by lukasbrand-ebcont** [lusaxweb/vuesax#98]
When using the Vuesax library i found some weird (spanish) console logs in development.

At startup:
![image](https://user-images.githubusercontent.com/29281937/40983111-2d835248-68df-11e8-89a0-23a8d4fbb1d5.png)

whenever the value of a select changes:
![image](https://user-images.githubusercontent.com/29281937/40983162-4ad38d7c-68df-11e8-876b-f29b0c039d69.png)

could that be fixed? :)

Gracias

- Your OS: MacOS 10.13.3
- Node.js: 10.0.0
- Vuesax: 3.0.50
- Browser version: Chrome 66.0.3359.181

**Comment by luisDanielRoviraContreras** [comment]
Thank you very much sometimes the logs are passed to me

I will verify and fix it thank you very much for the contribution

**Comment by luisDanielRoviraContreras** [comment]
Ready, the console.log has been removed thank you very much
